/* parser generated by rip-parser */
const parser = (() => {
  const parser = {
    trace: () => {},
    yy: {},
    symbols_: {"error":2,"Root":3,"Expression":4,"+":5,"-":6,"*":7,"/":8,"(":9,")":10,"NUMBER":11,"$end":1},
    terminals_: {"2":"error","5":"+","6":"-","7":"*","8":"/","9":"(","10":")","11":"NUMBER"},
    productions_: [0,[3,1],[4,3],[4,3],[4,3],[4,3],[4,3],[4,2],[4,1]],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
this.$ = $$[$0];
break;
case 2:
this.$ = $$[$0-2] + $$[$0];
break;
case 3:
this.$ = $$[$0-2] - $$[$0];
break;
case 4:
this.$ = $$[$0-2] * $$[$0];
break;
case 5:
this.$ = $$[$0-2] / $$[$0];
break;
case 6:
this.$ = $$[$0-1];
break;
case 7:
this.$ = -$$[$0];
break;
case 8:
this.$ = Number($$[$0]);
break;
}
},
    table: [{3:1,4:2,6:[1,4],9:[1,3],11:[1,5]},{1:[3]},{1:[2,1],5:[1,6],6:[1,7],7:[1,8],8:[1,9]},{4:10,6:[1,4],9:[1,3],11:[1,5]},{4:11,6:[1,4],9:[1,3],11:[1,5]},{1:[2,8],5:[2,8],6:[2,8],7:[2,8],8:[2,8],10:[2,8]},{4:12,6:[1,4],9:[1,3],11:[1,5]},{4:13,6:[1,4],9:[1,3],11:[1,5]},{4:14,6:[1,4],9:[1,3],11:[1,5]},{4:15,6:[1,4],9:[1,3],11:[1,5]},{5:[1,6],6:[1,7],7:[1,8],8:[1,9],10:[1,16]},{1:[2,7],5:[2,7],6:[2,7],7:[2,7],8:[2,7],10:[2,7]},{1:[2,2],5:[2,2],6:[2,2],7:[1,8],8:[1,9],10:[2,2]},{1:[2,3],5:[2,3],6:[2,3],7:[1,8],8:[1,9],10:[2,3]},{1:[2,4],5:[2,4],6:[2,4],7:[2,4],8:[2,4],10:[2,4]},{1:[2,5],5:[2,5],6:[2,5],7:[2,5],8:[2,5],10:[2,5]},{1:[2,6],5:[2,6],6:[2,6],7:[2,6],8:[2,6],10:[2,6]}],
    defaultActions: {},
    parseError: (str, hash) => {
      if (hash.recoverable) {
        this.trace(str);
      } else {
        const error = new Error(str);
        error.hash = hash;
        throw error;
      }
    },
    parse(input) {
      let stack = [0];
      const tstack = [];
      let vstack = [null];
      let lstack = [];
      const table = this.table;
      let yytext = '';
      let yylineno = 0;
      let yyleng = 0;
      let recovering = 0;
      const TERROR = 2;
      const EOF = 1;

      const args = lstack.slice.call(arguments, 1);
      // Use parser.lexer instead of this.lexer to avoid context issues
      const lexer = Object.create(parser.lexer);
      const sharedState = { yy: {} };

      for (const k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
          sharedState.yy[k] = this.yy[k];
        }
      }

      lexer.setInput(input, sharedState.yy);
      sharedState.yy.lexer = lexer;
      sharedState.yy.parser = this;
      if (typeof lexer.yylloc === 'undefined') lexer.yylloc = {};
      let yyloc = lexer.yylloc;
      lstack.push(yyloc);

      const ranges = lexer.options && lexer.options.ranges;

      if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
      } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
      }

      const popStack = (n) => {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
      };

      const lex = () => {
        let token = lexer.lex() || EOF;
        if (typeof token !== 'number') {
          token = this.symbols_[token] || token;
        }
        return token;
      };

      let symbol, preErrorSymbol, state, action, r, yyval = {}, p, len, newState, expected;
      while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
          action = this.defaultActions[state];
        } else {
          if (symbol === null || typeof symbol === 'undefined') {
            symbol = lex();
          }
          action = table[state] && table[state][symbol];
        }
        if (typeof action === 'undefined' || !action.length || !action[0]) {
          let error_rule_depth;
          let errStr = '';
          const locateNearestErrorRecoveryRule = (state) => {
            let stack_probe = stack.length - 1;
            let depth = 0;
            while (true) {
              if ((TERROR.toString()) in table[state]) return depth;
              if (state === 0 || stack_probe < 2) return false;
              stack_probe -= 2;
              state = stack[stack_probe];
              ++depth;
            }
          };
          if (!recovering) {
            error_rule_depth = locateNearestErrorRecoveryRule(state);
            expected = [];
            for (p in table[state]) {
              if (this.terminals_[p] && p > TERROR) {
                expected.push(`'${this.terminals_[p]}'`);
              }
            }
            if (lexer.showPosition) {
              errStr = `Parse error on line ${yylineno + 1}:\n${lexer.showPosition()}\nExpecting ${expected.join(', ')}, got '${this.terminals_[symbol] || symbol}'`;
            } else {
              errStr = `Parse error on line ${yylineno + 1}: Unexpected ${symbol === EOF ? 'end of input' : `'${this.terminals_[symbol] || symbol}'`}`;
            }
            this.parseError(errStr, {
              text: lexer.match,
              token: this.terminals_[symbol] || symbol,
              line: lexer.yylineno,
              loc: yyloc,
              expected: expected,
              recoverable: error_rule_depth !== false
            });
          } else if (preErrorSymbol !== EOF) {
            error_rule_depth = locateNearestErrorRecoveryRule(state);
          }
          if (recovering === 3) {
            if (symbol === EOF || preErrorSymbol === EOF) {
              throw new Error(errStr || 'Parsing halted while starting to recover from another error.');
            }
            yyleng = lexer.yyleng;
            yytext = lexer.yytext;
            yylineno = lexer.yylineno;
            yyloc = lexer.yylloc;
            symbol = lex();
          }
          if (error_rule_depth === false) {
            throw new Error(errStr || 'Parsing halted. No suitable error recovery rule available.');
          }
          popStack(error_rule_depth);
          preErrorSymbol = symbol === TERROR ? null : symbol;
          symbol = TERROR;
          state = stack[stack.length - 1];
          action = table[state] && table[state][TERROR];
          recovering = 3;
        }
        if (action[0] instanceof Array && action.length > 1) {
          throw new Error(`Parse Error: multiple actions possible at state: ${state}, token: ${symbol}`);
        }
        switch (action[0]) {
          case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
              yyleng = lexer.yyleng;
              yytext = lexer.yytext;
              yylineno = lexer.yylineno;
              yyloc = lexer.yylloc;
              if (recovering > 0) recovering--;
            } else {
              symbol = preErrorSymbol;
              preErrorSymbol = null;
            }
            break;
          case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
              first_line: lstack[lstack.length - (len || 1)].first_line,
              last_line: lstack[lstack.length - 1].last_line,
              first_column: lstack[lstack.length - (len || 1)].first_column,
              last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
              yyval._$.range = [lstack[lstack.length - (len || 1)].range[0], lstack[lstack.length - 1].range[1]];
            }
            r = this.performAction.apply(yyval, [yytext, yyleng, yylineno, sharedState.yy, action[1], vstack, lstack].concat(args));
            if (typeof r !== 'undefined') {
              return r;
            }
            if (len) {
              stack = stack.slice(0, -1 * len * 2);
              vstack = vstack.slice(0, -1 * len);
              lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
          case 3:
            return true;
        }
      }
      return true;
    }
  };

  

  // Minimal fake lexer for token arrays
const fakeLexer = {
  setInput(tokens) { this.tokens = tokens; this.pos = 0; },
  lex() { return this.tokens && this.pos < this.tokens.length ? this.tokens[this.pos++] : 1; }, // 1 = EOF
  // Stubs for compatibility
  yylloc: {},
  yylineno: 0,
  yytext: '',
  yyleng: 0,
  options: {},
  setInput: function(tokens) { this.tokens = tokens; this.pos = 0; },
  showPosition: function() { return ''; },
  match: '',
  more: function() {},
  unput: function() {},
  less: function() {},
  pastInput: function() { return ''; },
  upcomingInput: function() { return ''; },
  test_match: function() {},
  next: function() {},
  begin: function() {},
  popState: function() {},
  _currentRules: function() {},
  topState: function() {},
  pushState: function() {},
};
parser.lexer = fakeLexer;

  class Parser {
    constructor() {
      this.yy = {};
      // Ensure this.lexer is always set to the parser's lexer
      this.lexer = parser.lexer;
    }
  }

  Parser.prototype = parser;
  parser.Parser = Parser;

  return new Parser();
})();
if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
  exports.parser = parser;
  exports.Parser = parser.Parser;
  exports.parse = function () { return parser.parse.apply(parser, arguments); };
  exports.main = function() {};
}