// The runnable serving layer, exercised for real: startServer binds
// an actual Bun.serve listener on an ephemeral port and every
// assertion rides a real HTTP request — static serving with
// containment on a real disk (symlinks included), the App bundle
// preset, the SSE watch transport (handshake plus a revision event),
// TLS with a certificate GENERATED BY THIS TEST (nothing committed),
// the v3 port-conflict scan, and graceful shutdown. The port-scan
// POLICY (EACCES fallback, window exhaustion) drives through the
// injected listen seam, where the error codes are deterministic.
import { afterAll, describe, expect, test } from 'bun:test';
import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { scanListen, startServer } from '@rip-lang/server';

const roots = [];
const handles = [];
const scratch = () => {
  const dir = mkdtempSync(join(tmpdir(), 'rip-serve-'));
  roots.push(dir);
  return dir;
};
const start = (opts) => {
  const handle = startServer(opts);
  handles.push(handle);
  return handle;
};
afterAll(async () => {
  for (const handle of handles) await handle.stop().catch(() => {});
  for (const dir of roots) rmSync(dir, { recursive: true, force: true });
});

const siteDir = () => {
  const dir = scratch();
  writeFileSync(join(dir, 'index.html'), '<h1>home</h1>');
  writeFileSync(join(dir, 'app.js'), 'console.log(1)');
  mkdirSync(join(dir, 'docs'));
  writeFileSync(join(dir, 'docs', 'index.html'), '<h1>docs</h1>');
  return dir;
};

describe('static serving over a real listener', () => {
  test('files serve with content types, indexes, and 404 fallthrough', async () => {
    const handle = start({ root: siteDir(), httpPort: 0, quiet: true });
    expect(handle.port).toBeGreaterThan(0);

    const index = await fetch(`${handle.url}/`);
    expect(index.status).toBe(200);
    expect(await index.text()).toBe('<h1>home</h1>');

    const js = await fetch(`${handle.url}/app.js`);
    expect(js.headers.get('Content-Type')).toBe('application/javascript');

    const nested = await fetch(`${handle.url}/docs/`);
    expect(await nested.text()).toBe('<h1>docs</h1>');

    expect((await fetch(`${handle.url}/nope.css`)).status).toBe(404);
    await handle.stop();
  });

  test('containment holds on a real disk: encoded traversal and symlink escape both refuse', async () => {
    const dir = scratch();
    const root = join(dir, 'site');
    mkdirSync(root);
    writeFileSync(join(root, 'index.html'), 'public');
    writeFileSync(join(dir, 'secret.txt'), 'TOP SECRET');
    symlinkSync(join(dir, 'secret.txt'), join(root, 'leak.txt'));

    const handle = start({ root, httpPort: 0, quiet: true });
    // The URL layer collapses literal '..' and '%2e%2e'; an encoded
    // slash is what smuggles '..' past it, and resolveWithin catches
    // it — a hard 403 over the real wire.
    const traversal = await fetch(`${handle.url}/..%2Fsecret.txt`);
    expect(traversal.status).toBe(403);
    // No spelling ever serves the secret, whatever its status.
    for (const attack of ['/../secret.txt', '/%2e%2e/secret.txt', '/..%5Csecret.txt']) {
      expect(await (await fetch(`${handle.url}${attack}`)).text()).not.toBe('TOP SECRET');
    }
    const symlink = await fetch(`${handle.url}/leak.txt`);
    expect(symlink.status).toBe(403);
    expect((await fetch(`${handle.url}/index.html`)).status).toBe(200);
    await handle.stop();
  });

  test('sites route by Host header: exact beats wildcard beats catch-all; mounts strip their prefix', async () => {
    const a = scratch(); writeFileSync(join(a, 'index.html'), 'site-a');
    const b = scratch(); writeFileSync(join(b, 'only.txt'), 'site-b-docs');
    const handle = start({
      sites: [
        { host: 'a.test', routes: [{ mountPath: '/', root: a }, { mountPath: '/docs', root: b }] },
        { host: '*.test', routes: [{ mountPath: '/', root: b }] },
      ],
      httpPort: 0,
      quiet: true,
    });
    const at = async (host, path) => handle.fetchHandler(new Request(`http://${host}${path}`));
    expect(await (await at('a.test', '/index.html')).text()).toBe('site-a');
    expect(await (await at('a.test', '/docs/only.txt')).text()).toBe('site-b-docs');
    expect(await (await at('wild.test', '/only.txt')).text()).toBe('site-b-docs');
    expect((await at('other.example', '/index.html')).status).toBe(404); // no catch-all configured
    await handle.stop();
  });
});

describe('the App bundle preset over a real listener', () => {
  test('bundle endpoint with ETag revalidation, shell for HTML navigations, assets, secure headers', async () => {
    const root = scratch();
    writeFileSync(join(root, 'style.css'), 'body{}');
    const bundle = { modules: {}, data: { user: 'ada' } };
    const handle = start({ root, bundle, title: 'S1 App', httpPort: 0, quiet: true });

    const bundleRes = await fetch(`${handle.url}/bundle.json`);
    expect(bundleRes.status).toBe(200);
    expect(await bundleRes.json()).toEqual(bundle);
    const etag = bundleRes.headers.get('ETag');
    expect(etag).toBeTruthy();
    const cached = await fetch(`${handle.url}/bundle.json`, { headers: { 'If-None-Match': etag } });
    expect(cached.status).toBe(304);

    const shell = await fetch(`${handle.url}/dashboard`, { headers: { Accept: 'text/html' } });
    expect(shell.status).toBe(200);
    const html = await shell.text();
    expect(html).toContain('<title>S1 App</title>');
    expect(html).toContain('"user":"ada"'); // the bundle data is the boot state
    expect(shell.headers.get('X-Content-Type-Options')).toBe('nosniff'); // secureHeaders ride the preset

    expect((await fetch(`${handle.url}/style.css`)).status).toBe(200);
    await handle.stop();
  });
});

describe('the SSE watch transport over a real listener', () => {
  test('handshake, one revision event from the manual bump hook, and a stale client reloads at once', async () => {
    const handle = start({ root: siteDir(), httpPort: 0, watch: true, quiet: true });

    const readFrame = async (reader, decoder) => {
      const { value } = await reader.read();
      return decoder.decode(value);
    };

    const controller = new AbortController();
    const res = await fetch(`${handle.url}/_rip/watch`, { signal: controller.signal });
    expect(res.status).toBe(200);
    expect(res.headers.get('Content-Type')).toBe('text/event-stream');
    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    expect(await readFrame(reader, decoder)).toContain('retry:');

    handle.watch.reload(); // the manual revision bump — the file watcher arrives with S6
    const frame = await readFrame(reader, decoder);
    expect(frame).toContain('event: reload');
    expect(frame).toContain('id: 1');
    controller.abort();

    // A reconnecting client behind the current revision reloads at once.
    const stale = new AbortController();
    const behind = await fetch(`${handle.url}/_rip/watch`, {
      headers: { 'Last-Event-ID': '0' },
      signal: stale.signal,
    });
    const staleReader = behind.body.getReader();
    let text = await readFrame(staleReader, decoder);
    if (!text.includes('event:')) text += await readFrame(staleReader, decoder);
    expect(text).toContain('event: reload');
    stale.abort();
    await handle.stop();
  });

  test('without watch mode the endpoint does not exist', async () => {
    const handle = start({ root: siteDir(), httpPort: 0, quiet: true });
    expect(handle.watch).toBeNull();
    expect((await fetch(`${handle.url}/_rip/watch`)).status).toBe(404);
    await handle.stop();
  });
});

describe('TLS with a certificate generated by this test', () => {
  test('an explicit cert/key pair terminates TLS; HSTS rides only when asked', async () => {
    const dir = scratch();
    const cert = join(dir, 'cert.pem');
    const key = join(dir, 'key.pem');
    const made = spawnSync('openssl', [
      'req', '-x509', '-newkey', 'rsa:2048', '-keyout', key, '-out', cert,
      '-days', '2', '-nodes', '-subj', '/CN=localhost',
    ], { encoding: 'utf8' });
    expect(made.status).toBe(0); // openssl is part of the test environment contract

    const root = scratch();
    writeFileSync(join(root, 'index.html'), 'secure');
    const handle = start({
      root, httpsPort: 0, tls: { certPath: cert, keyPath: key }, hsts: true, quiet: true,
    });
    expect(handle.url.startsWith('https://')).toBeTrue();
    const res = await fetch(`https://localhost:${handle.port}/index.html`, { tls: { rejectUnauthorized: false } });
    expect(res.status).toBe(200);
    expect(await res.text()).toBe('secure');
    expect(res.headers.get('Strict-Transport-Security')).toBe('max-age=31536000; includeSubDomains');
    await handle.stop();

    const plain = start({ root, httpPort: 0, hsts: true, quiet: true });
    const plainRes = await fetch(`${plain.url}/index.html`);
    expect(plainRes.headers.get('Strict-Transport-Security')).toBeNull(); // never taught over plaintext
    await plain.stop();
  });

  test('https with no explicit material is a loud startup failure, never silent plaintext', () => {
    expect(() => startServer({ root: scratch(), httpsPort: 0, tls: {}, quiet: true }))
      .toThrow(/explicit certificate material/);
  });
});

describe('the port scan', () => {
  test('an occupied port walks forward to the next free one (real sockets)', async () => {
    const first = start({ root: siteDir(), httpPort: 0, quiet: true });
    const second = start({ root: siteDir(), httpPort: first.port, quiet: true });
    expect(second.port).toBeGreaterThan(first.port);
    expect(second.port).toBeLessThan(first.port + 100);
    expect((await fetch(`${second.url}/`)).status).toBe(200);
    await second.stop();
    await first.stop();
  });

  test('EACCES on a privileged port falls back to 3000 (3443 under TLS) and scans from there', () => {
    const attempts = [];
    const attempt = (port) => {
      attempts.push(port);
      if (port < 1024) throw Object.assign(new Error('denied'), { code: 'EACCES' });
      if (port === 3000) throw Object.assign(new Error('busy'), { code: 'EADDRINUSE' });
      return { port };
    };
    expect(scanListen(80, attempt, { quiet: true }).port).toBe(3001);
    expect(attempts).toEqual([80, 3000, 3001]);

    const tlsAttempts = [];
    const tlsAttempt = (port) => {
      tlsAttempts.push(port);
      if (port < 1024) throw Object.assign(new Error('denied'), { code: 'EACCES' });
      return { port };
    };
    expect(scanListen(443, tlsAttempt, { tls: true, quiet: true }).port).toBe(3443);
  });

  test('a full window is a loud failure; unexpected errors rethrow untouched', () => {
    const busy = () => { throw Object.assign(new Error('busy'), { code: 'EADDRINUSE' }); };
    expect(() => scanListen(9000, busy, { quiet: true })).toThrow(/no available port found \(tried 9000–9099\)/);
    const broken = () => { throw Object.assign(new Error('bad interface'), { code: 'EADDRNOTAVAIL' }); };
    expect(() => scanListen(9000, broken, { quiet: true })).toThrow(/bad interface/);
  });
});

describe('the worker pool seam', () => {
  test('requests dispatch through the pool: recycling is observable, capacity is bounded', async () => {
    const handle = start({
      root: siteDir(), httpPort: 0, quiet: true,
      workers: 1, concurrency: 1, maxRequestsPerWorker: 1,
    });
    await fetch(`${handle.url}/`);
    await fetch(`${handle.url}/`);
    const stats = handle.pool.stats();
    expect(stats.recycled).toBeGreaterThanOrEqual(1); // a one-request budget recycles per request
    expect(stats.size).toBe(1);
    await handle.stop();
  });
});

describe('graceful shutdown', () => {
  test('stop() drains, closes held-open streams, refuses new work, and is idempotent', async () => {
    const handle = start({ root: siteDir(), httpPort: 0, watch: true, quiet: true });

    const controller = new AbortController();
    const sse = await fetch(`${handle.url}/_rip/watch`, { signal: controller.signal });
    const reader = sse.body.getReader();
    await reader.read(); // the retry handshake — the stream is live

    const stopping = handle.stop();
    await stopping;
    await handle.stop(); // second call resolves to the same settled shutdown
    controller.abort(); // release the client half of the closed stream

    // The listener no longer accepts connections.
    const refused = await fetch(`${handle.url}/`).then(() => false, () => true);
    expect(refused).toBeTrue();

    // Work arriving after shutdown answers 503, the drain vocabulary.
    const late = await handle.fetchHandler(new Request(`${handle.url}/`));
    expect(late.status).toBe(503);
    expect(await late.text()).toBe('Server shutting down');
  });
});
