# Revolutionary RIP Application Server Configuration
# Enables .rip language transpilation across the entire server architecture

preload = ["/Users/shreeve/Data/Code/rip/bun-rip/bun-rip.ts"]

[project]
# Workers will auto-discover the application entry point

[install]
# Fast installs for development
auto = "auto"