// Generated by Rip Simple Bootstrap Compiler

// Rip Language - Main entry point
// Multi-runtime support: Bun (primary), Deno, Node.js, Browser

export { compile, compileFile, Compiler } from './compiler.js';
export { Lexer } from './lexer.js';
export * as nodes from './nodes.js';
export { version } from '../package.json';

// Platform detection helper
export const getPlatform = ->;
  if (typeof Bun isnt 'undefined') {
    { runtime: 'bun', version: Bun.version }
  else if typeof Deno isnt 'undefined'
    { runtime: 'deno', version: Deno.version.deno }
  else if typeof process isnt 'undefined'
    { runtime: 'node', version: process.version }
  else if typeof window isnt 'undefined'
    { runtime: 'browser', version: navigator.userAgent }
  } else {
    { runtime: 'unknown', version: 'unknown' }

// Export default compile function for convenience
export default compile from './compiler.js';
