import { expect, test } from '@playwright/test'
import { isModal } from './support.mjs'

const parts = (page) => ({
  input: page.getByRole('combobox', { name: 'Fruit' }).first(),
  popup: page.locator('main [popover="manual"][data-part="Popup"]').first(),
  selected: page.getByRole('group', { name: 'selected', exact: true }),
  heading: page.getByRole('heading', { level: 1 }),
})
let errors = []
test.beforeEach(({ page }) => {
  errors = []
  page.on('pageerror', (e) => errors.push(e.message))
})
test.afterEach(() => expect(errors).toEqual([]))
const boot = async (page) => {
  await page.goto('/combobox')
  await expect(parts(page).input).toBeVisible()
  return parts(page)
}
const isOpen = (page) => page.evaluate(() => document.querySelector('main [popover="manual"][data-part="Popup"]:popover-open') !== null)
const active = (input) => input.getAttribute('aria-activedescendant')
const options = (scope) => scope.locator('[role="option"]')
const settled = (popup) => popup.evaluate((el) => Promise.allSettled(el.getAnimations().map((a) => a.finished)))

// The demo passes sideOffset 6 and the popup takes the input's width
// through anchor-size().
const anchored = async (input, popup) => {
  await settled(popup)
  const i = await input.boundingBox()
  const p = await popup.boundingBox()
  expect(Math.abs(p.x - i.x)).toBeLessThan(1)
  expect(Math.abs(p.y - (i.y + i.height + 6))).toBeLessThan(1)
  expect(Math.abs(p.width - i.width)).toBeLessThan(1)
  await expect(popup).toHaveAttribute('data-side', 'bottom')
}

test('the input carries the combobox wiring, the label names it, and typing opens a manual popover under the input at its width', async ({ page }) => {
  const { input, popup } = await boot(page)
  await expect(input).toHaveAttribute('aria-autocomplete', 'list')
  await expect(input).toHaveAttribute('aria-haspopup', 'listbox')
  await expect(input).toHaveAttribute('aria-expanded', 'false')
  await expect(input).not.toHaveAttribute('data-popup-open')
  const inputId = await input.getAttribute('id')
  expect(inputId).toMatch(/^rip-combobox-input-/)
  await expect(page.locator(`label[for="${inputId}"]`)).toHaveText('Fruit')
  await expect(popup).toHaveAttribute('popover', 'manual')
  await expect(popup).toHaveAttribute('data-closed', 'true')
  expect(await isOpen(page)).toBe(false)
  const list = popup.locator('[role="listbox"]')
  expect(await input.getAttribute('aria-controls')).toBe(await list.evaluate((el) => el.id))
  await input.fill('ap')
  await expect.poll(() => isOpen(page)).toBe(true)
  await expect(popup).toHaveAttribute('data-open', 'true')
  await expect(input).toHaveAttribute('aria-expanded', 'true')
  await expect(input).toHaveAttribute('data-popup-open', 'true')
  await expect(options(popup)).toHaveText(['Apple', 'Apricot', 'Grape', 'Grapefruit', 'Papaya'])
  await expect(popup.getByRole('status')).toHaveText('')
  await anchored(input, popup)
  expect(await popup.evaluate((el) => el.style.getPropertyValue('--transform-origin'))).toBe('center top')
})

test('the arrows highlight through aria-activedescendant and wrap, the page keys jump, and Enter clicks the highlighted option, closes, and keeps focus in the input', async ({ page }) => {
  const { input, popup, selected } = await boot(page)
  await input.fill('ap')
  await expect(options(popup)).toHaveCount(5)
  const ids = await options(popup).evaluateAll((els) => els.map((el) => el.id))
  expect(await active(input)).toBeNull()
  await page.keyboard.press('ArrowDown')
  expect(await active(input)).toBe(ids[0])
  await expect(options(popup).nth(0)).toHaveAttribute('data-highlighted', 'true')
  await expect(options(popup).nth(0)).toHaveAttribute('aria-selected', 'true')
  await expect(options(popup).nth(1)).toHaveAttribute('aria-selected', 'false')
  await page.keyboard.press('ArrowUp')
  expect(await active(input)).toBe(ids[4])
  await page.keyboard.press('ArrowDown')
  expect(await active(input)).toBe(ids[0])
  await page.keyboard.press('PageDown')
  expect(await active(input)).toBe(ids[4])
  await page.keyboard.press('PageUp')
  expect(await active(input)).toBe(ids[0])
  await page.keyboard.press('ArrowDown')
  expect(await active(input)).toBe(ids[1])
  await page.keyboard.press('Enter')
  await expect(selected).toContainText('Apricot')
  await expect.poll(() => isOpen(page)).toBe(false)
  await expect(input).toBeFocused()
  await expect(input).toHaveValue('ap')
  expect(await active(input)).toBeNull()
})

test('Escape closes the popup, then clears the text, then is left alone; a Tab away closes it', async ({ page }) => {
  const { input, popup } = await boot(page)
  await input.fill('ap')
  await expect.poll(() => isOpen(page)).toBe(true)
  await page.keyboard.press('Escape')
  await expect.poll(() => isOpen(page)).toBe(false)
  await expect(popup).toHaveAttribute('data-closed', 'true')
  await expect(input).toHaveValue('ap')
  await expect(input).toHaveAttribute('aria-expanded', 'false')
  await page.keyboard.press('Escape')
  await expect(input).toHaveValue('')
  await input.fill('ap')
  await expect.poll(() => isOpen(page)).toBe(true)
  await page.keyboard.press('Tab')
  await expect.poll(() => isOpen(page)).toBe(false)
  await expect(input).not.toBeFocused()
})

test('a click on a blank input opens the popup when the list has options, and so does ArrowDown; focus alone does not', async ({ page }) => {
  const { input, popup } = await boot(page)
  await input.focus()
  await page.waitForTimeout(100)
  expect(await isOpen(page)).toBe(false)
  await input.click()
  await expect.poll(() => isOpen(page)).toBe(true)
  await expect(options(popup)).toHaveCount(20)
  await page.keyboard.press('Escape')
  await expect.poll(() => isOpen(page)).toBe(false)
  await page.keyboard.press('ArrowDown')
  await expect.poll(() => isOpen(page)).toBe(true)
  await expect(options(popup).nth(0)).toHaveAttribute('data-highlighted', 'true')
})

test('a click on a blank input whose list is empty opens nothing', async ({ page }) => {
  await boot(page)
  const input = page.getByRole('combobox', { name: 'Fruit search' })
  await input.click()
  await page.waitForTimeout(100)
  expect(await isOpen(page)).toBe(false)
  await page.keyboard.press('ArrowDown')
  await page.waitForTimeout(100)
  expect(await isOpen(page)).toBe(false)
})

test('a press outside closes the popup; a click on the input keeps it open, and reopens it', async ({ page }) => {
  const { input, heading } = await boot(page)
  await input.fill('ap')
  await expect.poll(() => isOpen(page)).toBe(true)
  await input.click()
  await page.waitForTimeout(100)
  expect(await isOpen(page)).toBe(true)
  await heading.click()
  await expect.poll(() => isOpen(page)).toBe(false)
  await input.click()
  await expect.poll(() => isOpen(page)).toBe(true)
})

test('Enter with nothing highlighted takes the only option, and a query matching nothing says so in the live region', async ({ page }) => {
  const { input, popup, selected } = await boot(page)
  await input.fill('kiwi')
  await expect(options(popup)).toHaveText(['Kiwi'])
  expect(await active(input)).toBeNull()
  await page.keyboard.press('Enter')
  await expect(selected).toContainText('Kiwi')
  await expect.poll(() => isOpen(page)).toBe(false)
  await input.fill('zzz')
  await expect.poll(() => isOpen(page)).toBe(true)
  await expect(popup.getByRole('status')).toHaveText('No matching fruit')
  await expect(options(popup)).toHaveCount(0)
})

test('the async stage runs through a search: the list is busy until the matches land, and a trailing action is an option, taken by Enter as the only one', async ({ page }) => {
  await boot(page)
  const input = page.getByRole('combobox', { name: 'Fruit search' })
  const popup = page.locator('main [popover="manual"][data-part="Popup"]').nth(1)
  const selected = page.getByRole('group', { name: 'selected', exact: true })
  await input.fill('ap')
  await expect.poll(() => isOpen(page)).toBe(true)
  await expect(options(popup)).toHaveText(['Apple', 'Apricot', 'Grape', 'Grapefruit', 'Papaya', 'Add “ap”'])
  await expect(popup.getByRole('listbox')).not.toHaveAttribute('aria-busy', 'true')
  await input.fill('zzz')
  await expect(popup.getByRole('status')).toHaveText('No matching fruit')
  await expect(options(popup)).toHaveText(['Add “zzz”'])
  expect(await active(input)).toBeNull()
  await page.keyboard.press('Enter')
  await expect(selected).toContainText('Add zzz')
  await expect.poll(() => isOpen(page)).toBe(false)
})

test('the pointer highlights an option only when it moves: a keyboard scroll under a resting pointer keeps the keyboard highlight, and leaving the list clears it', async ({ page }) => {
  const { input, popup, heading } = await boot(page)
  await input.fill('a')
  await expect(options(popup)).toHaveCount(12)
  await settled(popup)
  const ids = await options(popup).evaluateAll((els) => els.map((el) => el.id))
  await options(popup).nth(1).hover()
  await expect.poll(() => active(input)).toBe(ids[1])
  for (let i = 0; i < 8; i++) await page.keyboard.press('ArrowDown')
  expect(await active(input)).toBe(ids[9])
  await page.waitForTimeout(200)
  expect(await active(input)).toBe(ids[9])
  const box = await heading.boundingBox()
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2, { steps: 8 })
  await expect.poll(() => active(input)).toBeNull()
})

test('a touch press highlights its option before the release clicks it, and a touch move highlights nothing', async ({ page }) => {
  const { input, popup } = await boot(page)
  await input.fill('a')
  await expect(options(popup)).toHaveCount(12)
  await settled(popup)
  const ids = await options(popup).evaluateAll((els) => els.map((el) => el.id))
  const touch = (el, type) => el.dispatchEvent(new PointerEvent(type, { pointerType: 'touch', bubbles: true, cancelable: true, clientX: 1, clientY: 1 }))
  await options(popup).nth(2).evaluate(touch, 'pointermove')
  await page.waitForTimeout(50)
  expect(await active(input)).toBeNull()
  await options(popup).nth(2).evaluate(touch, 'pointerdown')
  await expect.poll(() => active(input)).toBe(ids[2])
  await expect(options(popup).nth(2)).toHaveAttribute('data-highlighted', 'true')
  await expect(input).toBeFocused()
})

test('an inline list has no popup: the input reports expanded, Enter adds and hands the highlight to the option now in its place, a click keeps focus in the input, and Escape clears the filter', async ({ page }) => {
  await boot(page)
  const input = page.getByRole('combobox', { name: 'Filter fruit' })
  const list = page.getByRole('listbox', { name: 'Fruit' })
  const picked = page.getByRole('group', { name: 'picked', exact: true })
  await expect(input).toHaveAttribute('aria-expanded', 'true')
  await expect(input).not.toHaveAttribute('data-popup-open')
  await expect(options(list)).toHaveCount(20)
  await expect(options(list).nth(0)).toHaveAttribute('data-part', 'Item')
  await expect(options(list).nth(0)).toHaveAttribute('type', 'button')
  await expect(options(list).nth(0)).toHaveAttribute('tabindex', '-1')
  await input.focus()
  for (let i = 0; i < 3; i++) await page.keyboard.press('ArrowDown')
  await expect(options(list).nth(2)).toHaveAttribute('data-highlighted', 'true')
  await expect(options(list).nth(2)).toHaveText('Banana')
  await page.keyboard.press('Enter')
  await expect(picked).toHaveText('Banana')
  await expect(options(list)).toHaveCount(19)
  await expect(options(list).nth(2)).toHaveText('Blueberry')
  await expect.poll(() => active(input)).toBe(await options(list).nth(2).evaluate((el) => el.id))
  await expect(input).toBeFocused()
  await options(list).getByText('Cherry', { exact: true }).click()
  await expect(picked).toContainText('Cherry')
  await expect(input).toBeFocused()
  await input.fill('kiwi')
  await expect(options(list)).toHaveText(['Kiwi'])
  expect(await active(input)).toBeNull()
  await page.keyboard.press('Enter')
  await expect(picked).toContainText('Kiwi')
  await expect(input).toHaveValue('kiwi')
  await page.keyboard.press('Escape')
  await expect(input).toHaveValue('')
  await expect(options(list)).toHaveCount(17)
  await page.keyboard.press('Tab')
  expect(await page.evaluate(() => document.activeElement?.getAttribute('role'))).not.toBe('option')
})

test('an option leaving an inline list hands the keyboard highlight to the option now in its place, with the pointer resting on another row', async ({ page }) => {
  await boot(page)
  const input = page.getByRole('combobox', { name: 'Filter fruit' })
  const list = page.getByRole('listbox', { name: 'Fruit' })
  const picked = page.getByRole('group', { name: 'picked', exact: true })
  await options(list).nth(0).hover()
  await expect(options(list).nth(0)).toHaveAttribute('data-highlighted', 'true')
  await input.focus()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('ArrowDown')
  await expect(options(list).nth(2)).toHaveAttribute('data-highlighted', 'true')
  await page.keyboard.press('Enter')
  await expect(picked).toHaveText('Banana')
  await expect(options(list).nth(2)).toHaveText('Blueberry')
  await expect(options(list).nth(2)).toHaveAttribute('data-highlighted', 'true')
  await page.waitForTimeout(200)
  await expect(options(list).nth(0)).not.toHaveAttribute('data-highlighted')
  await expect(options(list).nth(2)).toHaveAttribute('data-highlighted', 'true')
})

test('under a modal dialog Escape closes the combobox popup first, then clears, then closes the dialog', async ({ page }) => {
  await boot(page)
  await page.getByRole('button', { name: 'Open Dialog' }).click()
  await expect.poll(() => isModal(page)).toBe(true)
  const input = page.locator('main dialog').getByRole('combobox')
  await input.fill('ap')
  await expect.poll(() => page.evaluate(() => document.querySelector('main dialog [popover="manual"]:popover-open') !== null)).toBe(true)
  await page.keyboard.press('Escape')
  await expect.poll(() => page.evaluate(() => document.querySelector('main dialog [popover="manual"]:popover-open') !== null)).toBe(false)
  expect(await isModal(page)).toBe(true)
  await page.keyboard.press('Escape')
  await expect(input).toHaveValue('')
  expect(await isModal(page)).toBe(true)
  await page.keyboard.press('Escape')
  await expect.poll(() => isModal(page)).toBe(false)
})
