import { expect, test } from '@playwright/test'
import { boot, isModal, parts } from './support.mjs'

test('the theme is light until a click chooses, whatever the system prefers, and the choice survives a reload', async ({ page, browser }) => {
  const dark = await browser.newContext({ colorScheme: 'dark' })
  const darkPage = await dark.newPage()
  await darkPage.goto('/dialog')
  await expect(parts(darkPage).trigger).toBeVisible()
  await expect.poll(() => darkPage.evaluate(() => document.documentElement.dataset.theme)).toBe('light')
  expect(await darkPage.evaluate(() => localStorage.getItem('theme'))).toBeNull()
  await dark.close()

  const { trigger } = await boot(page)
  const theme = () => page.evaluate(() => document.documentElement.dataset.theme)
  const toggle = page.getByRole('button', { name: /theme/ })
  await expect.poll(theme).toBe('light')
  expect(await page.evaluate(() => localStorage.getItem('theme'))).toBeNull()
  await expect(toggle).toHaveAccessibleName('Switch to the dark theme')
  await toggle.click()
  await expect.poll(theme).toBe('dark')
  expect(await page.evaluate(() => localStorage.getItem('theme'))).toBe('dark')
  await page.reload()
  await expect(trigger).toBeVisible()
  await expect.poll(theme).toBe('dark')
  await expect(toggle).toHaveAccessibleName('Switch to the light theme')
  await toggle.click()
  await expect.poll(theme).toBe('light')
})

test('at phone width the navigation is a drawer built on Dialog; a link closes it, and so does widening past the breakpoint', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const menu = page.getByRole('button', { name: 'Open navigation' })
  await expect(menu).toBeVisible()
  await expect(page.locator('aside')).toBeHidden()
  await menu.click()
  await expect.poll(() => isModal(page)).toBe(true)
  const drawer = page.getByRole('dialog', { name: 'Navigation' })
  await drawer.getByRole('link', { name: 'Dialog' }).click()
  await expect.poll(() => isModal(page)).toBe(false)
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Dialog')
  await menu.click()
  await expect.poll(() => isModal(page)).toBe(true)
  await page.setViewportSize({ width: 1280, height: 800 })
  await expect.poll(() => isModal(page)).toBe(false)
  await expect(menu).toBeHidden()
  await expect(page.locator('aside')).toBeVisible()
})

test('the index lists every component and links to its page', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Rip UI')
  const card = page.getByRole('link', { name: /Dialog/ }).filter({ hasText: 'A modal that opens on top of the entire page.' })
  await expect(card).toBeVisible()
  await card.click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Dialog')
  await expect(parts(page).trigger).toBeVisible()
  await page.getByRole('link', { name: 'Rip UI' }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Rip UI')
})
