// CodeBuilder — the emitter writes THROUGH the builder.
// emit() appends text and advances the running generated offset; mark()
// wraps a role's emission and records a MappingStore row with both spans
// known exactly. Generated spans exist by construction — never by
// searching output text.
//
// MappingStore row: { nodeId, role, mappingKind, sourceStart, sourceEnd,
//   generatedStart, generatedEnd, fileId }
//
// Source-span resolution in mark():
//   '$self'          — the node's NodeStore row span ($self is a NodeStore
//                      lookup, never a RoleStore row)
//   ref role         — its RoleStore row span
//   literal-sourced  — mappingKind 'synthetic' with a zero-width source
//                      anchor at the owning node's sourceStart (the value
//                      is statically known)
//
// mappingKind is determined by construction, never declared: the builder
// compares the emitted slice against the source slice and records 'exact'
// only when they are verbatim-equal, 'cover' otherwise.
//
// Output accumulates as an array of chunks, joined once at the end. Every
// mark starts at a chunk boundary, so a marked region's text is the join
// of the chunks appended during its fn() — O(marked region), never a
// flatten of the whole growing buffer.

import { ops } from './ops.js';

export class CodeBuilder {
  constructor(stores, { source = null, primitives = false } = {}) {
    this.stores = stores;
    this.source = source;
    // TS face only: primitive identifier reads claim their own source spans
    // (claimPrimitiveSpan). The bookkeeping below is per-mark and per-row, so
    // the shipping JS emission — which never claims one — does not run it.
    this.trackPrimitives = primitives;
    this.chunks = [];
    this.length = 0;
    this.openMarks = 0;
    this.rows = [];
    // Source spans that already own an exact row. Primitive claims consult
    // this set while emitting broader list/body frames, keeping each lookup
    // O(1) instead of rescanning the growing MappingStore.
    this.exactSourceSpans = new Set();
    // Open-mark identities, innermost last. The reactive read rewrite
    // re-marks the innermost open (nodeId, role) around the bare
    // identifier it emits, so the read site gains its own row — exact
    // when the role's source span IS the identifier, cover otherwise
    // (the builder's comparison decides; never declared).
    this.markStack = [];
    // Exactness memo, keyed by alignment delta (sourceStart −
    // generatedStart): the last generated range verified to match the
    // source at that delta, with its chunk-index bounds. Nested exact
    // marks share one delta (a member spine's frames all start at the
    // same offsets), so each enclosing frame re-verifies only the
    // chunks OUTSIDE the memo's range — every generated byte is
    // compared once, not once per enclosing mark, keeping deep chains
    // linear in compile time.
    this.exactRanges = new Map();
    // TS-only generated regions (the TypeScript editor face): every byte the
    // TS face emits BEYOND the JS emission is recorded here as a
    // [start, end) generated span, ascending and disjoint by
    // construction (regions record at emission, and nested tsOnly
    // frames fold into the outermost). Deleting these regions from the
    // TS face's output must reproduce the JS emission byte-for-byte —
    // the strip gate's transform. JS-mode emission records none.
    this.tsRegions = [];
    this.tsDepth = 0;
  }

  // Emit fn()'s output as a TS-ONLY region. Mapping rows recorded
  // inside are ordinary mark-protocol rows — the region list is a
  // separate, additive record of which generated bytes exist only in
  // the TS face.
  tsOnly(fn) {
    const start = this.length;
    this.tsDepth++;
    fn();
    this.tsDepth--;
    if (this.tsDepth === 0 && this.length > start) {
      this.tsRegions.push([start, this.length]);
    }
  }

  get currentMark() {
    return this.markStack[this.markStack.length - 1] ?? null;
  }

  get offset() {
    return this.length;
  }

  // Full output. Collapses the chunks to one only when no mark is open —
  // open marks hold chunk indices that a collapse would invalidate.
  get code() {
    if (this.openMarks > 0) return this.chunks.join('');
    if (this.chunks.length !== 1) {
      this.chunks = [this.chunks.join('')];
      // Collapsing renumbers the chunk array; the memo's chunk-index
      // bounds die with the old numbering.
      this.exactRanges.clear();
    }
    return this.chunks[0];
  }

  emit(text) {
    this.chunks.push(text);
    this.length += text.length;
    return this;
  }

  // The imperative frame pair mark() wraps. Iterative chain emission
  // (deep binary/member/call spines) opens frames from a LOOP, so a
  // ten-thousand-link chain holds its marks as data, never as native
  // stack; every beginMark pairs with exactly one endMark.
  beginMark(nodeId, role) {
    let sourceStart, sourceEnd;
    let mappingKind = null;
    if (role === '$self') {
      const n = this.stores.node(nodeId);
      sourceStart = n.sourceStart;
      sourceEnd = n.sourceEnd;
    } else {
      const r = this.stores.role(nodeId, role);
      if (r.grammarRef === null) {
        mappingKind = 'synthetic';
        sourceStart = sourceEnd = this.stores.node(nodeId).sourceStart;
      } else {
        sourceStart = r.sourceStart;
        sourceEnd = r.sourceEnd;
      }
    }
    this.openMarks++;
    this.markStack.push({
      nodeId, role, sourceStart, sourceEnd, mappingKind,
      generatedStart: this.length, chunkStart: this.chunks.length,
    });
  }

  endMark() {
    const f = this.markStack.pop();
    this.openMarks--;
    let { mappingKind } = f;
    if (mappingKind === null) {
      mappingKind = this.matchesSource(f) ? 'exact' : 'cover';
    }
    this.rows.push({
      nodeId: f.nodeId, role: f.role, mappingKind,
      sourceStart: f.sourceStart, sourceEnd: f.sourceEnd,
      generatedStart: f.generatedStart, generatedEnd: this.length,
      fileId: 0,
    });
    if (this.trackPrimitives && mappingKind === 'exact') {
      this.exactSourceSpans.add(`${f.sourceStart}:${f.sourceEnd}`);
    }
  }

  mark(nodeId, role, fn) {
    this.beginMark(nodeId, role);
    fn();
    this.endMark();
  }

  // The roles markSpan may record — caller-supplied-span TS-face roles
  // come from this fixed set, never from caller-invented strings (the
  // RoleStore is the authority for every other role name): tsDirective
  // rows source their spans from the lexer's trivia channel;
  // shorthandProp rows from the render walk's anchored bare-word scan
  // (a boolean-shorthand prop key is a primitive with no store row).
  static SPAN_ROLES = new Set(['tsDirective', 'shorthandProp', 'identifier']);

  // A mark whose source span is supplied by the CALLER — the channel
  // for trivia-sourced emission (TS directive comments), whose spans
  // live in the lexer's trivia channel, not in RoleStore. The frame
  // closes through endMark, so mappingKind stays determined by the
  // builder's verbatim comparison, never declared.
  markSpan(nodeId, role, sourceStart, sourceEnd, fn) {
    if (!CodeBuilder.SPAN_ROLES.has(role)) {
      throw new Error(
        `builder: markSpan role '${role}' is not in the TS-face trivia allowlist ` +
        `(${[...CodeBuilder.SPAN_ROLES].join(', ')}) — every other role resolves through RoleStore`,
      );
    }
    this.openMarks++;
    this.markStack.push({
      nodeId, role, sourceStart, sourceEnd, mappingKind: null,
      generatedStart: this.length, chunkStart: this.chunks.length,
    });
    fn();
    this.endMark();
  }

  // Claim the next recorded occurrence of a primitive spelling inside the
  // current mark. A fresh mark frame restarts the occurrence cursor, which is
  // exactly what one source role emitted into multiple generated regions
  // needs. No generated text is searched: candidates are parser-recorded
  // source occurrences, and emission order chooses among repeats.
  // `avoid` — [start, end) regions of the frame that belong to a SIBLING role,
  // whose occurrences are therefore not this emission's. It exists because a
  // construct can emit one of its parts from a frame wider than that part: a
  // comprehension's clause variable has no role of its own, so it claims from
  // the whole comprehension, where the body's reads also live. Excluding the
  // body's recorded span leaves exactly the clause's own occurrences, and the
  // cursor below then orders them correctly — every bound is a span the parser
  // recorded, never a search of the text.
  claimPrimitiveSpan(value, avoid = null) {
    const f = this.currentMark;
    if (f === null) return null;
    let candidates = this.stores.primitiveSpans(value, f.sourceStart, f.sourceEnd);
    if (avoid !== null && avoid.length > 0) {
      candidates = candidates.filter((p) =>
        !avoid.some(([a, b]) => p.sourceStart >= a && p.sourceEnd <= b));
    }
    if (candidates.length === 0) return null;
    // TWO exclusions, and the frame's own is a SET, not a counter. An
    // occurrence that already owns an exact row was placed by a narrower role,
    // so a broad frame must not re-place it; an occurrence this frame already
    // handed out must not go twice. What survives is taken in source order.
    //
    // A counter was the bug worth naming: the eligible list SHRINKS as claims
    // register their rows, so indexing it by a call count walks off the end of
    // its own shortening — with three occurrences it hands out the first, then
    // the third, then the second, and a diagnostic on the middle read lands on
    // its neighbour. Emission order still chooses among repeats; it just does
    // so by consuming the list rather than by counting calls against it.
    const claims = f.primitiveClaims ?? (f.primitiveClaims = new Map());
    let taken = claims.get(value);
    if (taken === undefined) claims.set(value, taken = new Set());
    const free = candidates.filter((c) => !taken.has(c.sourceStart));
    const unplaced = free.filter((c) =>
      !this.exactSourceSpans.has(`${c.sourceStart}:${c.sourceEnd}`)
    );
    const p = (unplaced.length > 0 ? unplaced : free)[0];
    // Every occurrence in this frame is spoken for — decline, rather than hand
    // a second generated position a row on a source read that already has one.
    if (p === undefined) return null;
    taken.add(p.sourceStart);
    // A SIGIL-carrying token records the sigil inside its span — the symbol
    // `alpha` is lexed as `:alpha` — so the recorded span is wider than the
    // name it stands for and a mark over it would not be verbatim. The name's
    // own bytes are the tail: arithmetic on a recorded span, never a search.
    if (this.source !== null) {
      const text = this.source.slice(p.sourceStart, p.sourceEnd);
      // Narrow ONLY the sigil case — the name is the whole tail and what
      // precedes it is a single non-identifier byte. Anything else keeps the
      // recorded span and classifies exactly as it did before.
      if (text !== value && text.endsWith(value) &&
          !/[\w$]/.test(text[text.length - value.length - 1] ?? '')) {
        return [p.sourceEnd - value.length, p.sourceEnd];
      }
    }
    return [p.sourceStart, p.sourceEnd];
  }

  // Does the region emitted during frame `f` equal its source span
  // verbatim? Equivalent to joining the region's chunks and comparing
  // the strings, but never joins: the length gate answers most cover
  // frames in O(1), the chunk walk bails at the first mismatching
  // chunk, and the per-delta memo lets an enclosing exact frame skip
  // every chunk a contained exact frame already verified. Marks begin
  // and end on chunk boundaries by construction (emit pushes whole
  // chunks), so the memo's bounds always land on a walkable boundary.
  matchesSource(f) {
    if (this.source === null) return false;
    // The length gate reads the span's NOMINAL width, so it is
    // equivalent to slicing only for in-range spans — an out-of-range
    // span is a store-protocol violation (every span derives from
    // token offsets into this source), never something to clamp over.
    if (f.sourceStart < 0 || f.sourceEnd > this.source.length) {
      throw new Error(
        `builder: mark (nodeId ${f.nodeId}, role '${f.role}') has source span ` +
        `[${f.sourceStart}, ${f.sourceEnd}) outside the source text ` +
        `[0, ${this.source.length}) — store-protocol violation`,
      );
    }
    const genEnd = this.length;
    if (genEnd - f.generatedStart !== f.sourceEnd - f.sourceStart) return false;
    const delta = f.sourceStart - f.generatedStart;
    const m = this.exactRanges.get(delta);
    // The memo may begin BEFORE this frame (an earlier sibling at the
    // same delta bridged in) — any part of it inside the frame is
    // still verified, so the walk jumps from wherever it enters the
    // memo range straight to the range's end.
    const skippable = m !== undefined && m.genEnd <= genEnd;
    const chunkEnd = this.chunks.length;
    let pos = f.generatedStart;
    let i = f.chunkStart;
    while (i < chunkEnd) {
      if (ops.on) ops.n++;
      if (skippable && pos >= m.genStart && pos < m.genEnd) {
        pos = m.genEnd;
        i = m.chunkEnd;
        continue;
      }
      const chunk = this.chunks[i];
      if (!this.source.startsWith(chunk, pos + delta)) return false;
      pos += chunk.length;
      i++;
    }
    if (genEnd === f.generatedStart) return true; // zero-width: nothing to memoize
    // A closing mark always ends at the emission frontier, so the memo
    // range is never strictly right of this frame: either they overlap
    // (union them — the range grows along a spine) or the memo ends in
    // a gap left of the frame. Gaps are typically the bytes of marks
    // that never verify (synthetic operators emit `.` between two
    // verified ranges); if the gap's chunks also match the source at
    // this delta, the ranges bridge into one — this is what keeps a
    // member spine's per-level re-verification O(1) instead of
    // O(prefix). An unbridgeable gap means every enclosing frame at
    // this delta mismatches there too, so the old range is spent:
    // replace it with the frontier's.
    if (m !== undefined && (f.generatedStart <= m.genEnd || this.bridges(m, f, delta))) {
      if (f.generatedStart < m.genStart) {
        m.genStart = f.generatedStart;
        m.chunkStart = f.chunkStart;
      }
      m.genEnd = genEnd;
      m.chunkEnd = chunkEnd;
    } else {
      this.exactRanges.set(delta, {
        genStart: f.generatedStart, genEnd, chunkStart: f.chunkStart, chunkEnd,
      });
    }
    return true;
  }

  // Do the chunks between the memo range's end and frame `f`'s start
  // match the source at `delta`? Bails at the first mismatch.
  bridges(m, f, delta) {
    let pos = m.genEnd;
    for (let i = m.chunkEnd; i < f.chunkStart; i++) {
      if (ops.on) ops.n++;
      const chunk = this.chunks[i];
      if (!this.source.startsWith(chunk, pos + delta)) return false;
      pos += chunk.length;
    }
    return true;
  }

  finish() {
    return { code: this.code, mappings: this.rows, tsRegions: this.tsRegions };
  }
}
