// CodeBuilder — the emitter writes THROUGH the builder.
// emit() appends text and advances the running generated offset; mark()
// wraps a role's emission and records a MappingStore row with both spans
// known exactly. Generated spans exist by construction — never by
// searching output text.
//
// MappingStore row: { nodeId, role, mappingKind, sourceStart, sourceEnd,
//   generatedStart, generatedEnd, fileId }
//
// Source-span resolution in mark():
//   '$self'          — the node's NodeStore row span ($self is a NodeStore
//                      lookup, never a RoleStore row)
//   ref role         — its RoleStore row span
//   literal-sourced  — mappingKind 'synthetic' with a zero-width source
//                      anchor at the owning node's sourceStart (the value
//                      is statically known)
//
// mappingKind is determined by construction, never declared: the builder
// compares the emitted slice against the source slice and records 'exact'
// only when they are verbatim-equal, 'cover' otherwise.
//
// Output accumulates as an array of chunks, joined once at the end. Every
// mark starts at a chunk boundary, so a marked region's text is the join
// of the chunks appended during its fn() — O(marked region), never a
// flatten of the whole growing buffer.

import { ops } from './ops.js';

export class CodeBuilder {
  constructor(stores, { source = null } = {}) {
    this.stores = stores;
    this.source = source;
    this.chunks = [];
    this.length = 0;
    this.openMarks = 0;
    this.rows = [];
    // Open-mark identities, innermost last. The reactive read rewrite
    // re-marks the innermost open (nodeId, role) around the bare
    // identifier it emits, so the read site gains its own row — exact
    // when the role's source span IS the identifier, cover otherwise
    // (the builder's comparison decides; never declared).
    this.markStack = [];
    // Exactness memo, keyed by alignment delta (sourceStart −
    // generatedStart): the last generated range verified to match the
    // source at that delta, with its chunk-index bounds. Nested exact
    // marks share one delta (a member spine's frames all start at the
    // same offsets), so each enclosing frame re-verifies only the
    // chunks OUTSIDE the memo's range — every generated byte is
    // compared once, not once per enclosing mark, keeping deep chains
    // linear in compile time.
    this.exactRanges = new Map();
    // TS-only generated regions (the TypeScript editor face): every byte the
    // TS face emits BEYOND the JS emission is recorded here as a
    // [start, end) generated span, ascending and disjoint by
    // construction (regions record at emission, and nested tsOnly
    // frames fold into the outermost). Deleting these regions from the
    // TS face's output must reproduce the JS emission byte-for-byte —
    // the strip gate's transform. JS-mode emission records none.
    this.tsRegions = [];
    this.tsDepth = 0;
  }

  // Emit fn()'s output as a TS-ONLY region. Mapping rows recorded
  // inside are ordinary mark-protocol rows — the region list is a
  // separate, additive record of which generated bytes exist only in
  // the TS face.
  tsOnly(fn) {
    const start = this.length;
    this.tsDepth++;
    fn();
    this.tsDepth--;
    if (this.tsDepth === 0 && this.length > start) {
      this.tsRegions.push([start, this.length]);
    }
  }

  get currentMark() {
    return this.markStack[this.markStack.length - 1] ?? null;
  }

  get offset() {
    return this.length;
  }

  // Full output. Collapses the chunks to one only when no mark is open —
  // open marks hold chunk indices that a collapse would invalidate.
  get code() {
    if (this.openMarks > 0) return this.chunks.join('');
    if (this.chunks.length !== 1) {
      this.chunks = [this.chunks.join('')];
      // Collapsing renumbers the chunk array; the memo's chunk-index
      // bounds die with the old numbering.
      this.exactRanges.clear();
    }
    return this.chunks[0];
  }

  emit(text) {
    this.chunks.push(text);
    this.length += text.length;
    return this;
  }

  // The imperative frame pair mark() wraps. Iterative chain emission
  // (deep binary/member/call spines) opens frames from a LOOP, so a
  // ten-thousand-link chain holds its marks as data, never as native
  // stack; every beginMark pairs with exactly one endMark.
  beginMark(nodeId, role) {
    let sourceStart, sourceEnd;
    let mappingKind = null;
    if (role === '$self') {
      const n = this.stores.node(nodeId);
      sourceStart = n.sourceStart;
      sourceEnd = n.sourceEnd;
    } else {
      const r = this.stores.role(nodeId, role);
      if (r.grammarRef === null) {
        mappingKind = 'synthetic';
        sourceStart = sourceEnd = this.stores.node(nodeId).sourceStart;
      } else {
        sourceStart = r.sourceStart;
        sourceEnd = r.sourceEnd;
      }
    }
    this.openMarks++;
    this.markStack.push({
      nodeId, role, sourceStart, sourceEnd, mappingKind,
      generatedStart: this.length, chunkStart: this.chunks.length,
    });
  }

  endMark() {
    const f = this.markStack.pop();
    this.openMarks--;
    let { mappingKind } = f;
    if (mappingKind === null) {
      mappingKind = this.matchesSource(f) ? 'exact' : 'cover';
    }
    this.rows.push({
      nodeId: f.nodeId, role: f.role, mappingKind,
      sourceStart: f.sourceStart, sourceEnd: f.sourceEnd,
      generatedStart: f.generatedStart, generatedEnd: this.length,
      fileId: 0,
    });
  }

  mark(nodeId, role, fn) {
    this.beginMark(nodeId, role);
    fn();
    this.endMark();
  }

  // The roles markSpan may record — caller-supplied-span TS-face roles
  // come from this fixed set, never from caller-invented strings (the
  // RoleStore is the authority for every other role name): tsDirective
  // rows source their spans from the lexer's trivia channel;
  // shorthandProp rows from the render walk's anchored bare-word scan
  // (a boolean-shorthand prop key is a primitive with no store row).
  static SPAN_ROLES = new Set(['tsDirective', 'shorthandProp']);

  // A mark whose source span is supplied by the CALLER — the channel
  // for trivia-sourced emission (TS directive comments), whose spans
  // live in the lexer's trivia channel, not in RoleStore. The frame
  // closes through endMark, so mappingKind stays determined by the
  // builder's verbatim comparison, never declared.
  markSpan(nodeId, role, sourceStart, sourceEnd, fn) {
    if (!CodeBuilder.SPAN_ROLES.has(role)) {
      throw new Error(
        `builder: markSpan role '${role}' is not in the TS-face trivia allowlist ` +
        `(${[...CodeBuilder.SPAN_ROLES].join(', ')}) — every other role resolves through RoleStore`,
      );
    }
    this.openMarks++;
    this.markStack.push({
      nodeId, role, sourceStart, sourceEnd, mappingKind: null,
      generatedStart: this.length, chunkStart: this.chunks.length,
    });
    fn();
    this.endMark();
  }

  // ── probe emission (the place-or-decline check) ───────────────────
  //
  // A directive's placement decision needs the governed statement's
  // ACTUAL face emission (single line or not) — unknowable from the
  // tree without duplicating every lowering decision. The probe
  // protocol: checkpoint, emit once, inspect; when the emission turns
  // out single-line, roll back and re-emit with the directive line in
  // front. Rollback requires mark-BALANCED emission between
  // checkpoint and rollback (statements are; the guard rejects
  // anything else), and kills the exactness memo — its chunk indices
  // die with the truncation.

  checkpoint() {
    return {
      length: this.length, chunks: this.chunks.length, rows: this.rows.length,
      tsRegions: this.tsRegions.length, marks: this.markStack.length,
    };
  }

  // Does the emission since `cp` span multiple lines? One TRAILING
  // newline is layout, not a second line (class member rows own their
  // line break; statement-position emissions end before theirs).
  multiLineSince(cp) {
    const text = this.chunks.slice(cp.chunks).join('');
    return (text.endsWith('\n') ? text.slice(0, -1) : text).includes('\n');
  }

  rollback(cp) {
    if (this.markStack.length !== cp.marks) {
      throw new Error('builder: rollback across an open-mark boundary — probe emission must be mark-balanced');
    }
    this.chunks.length = cp.chunks;
    this.length = cp.length;
    this.rows.length = cp.rows;
    this.tsRegions.length = cp.tsRegions;
    this.exactRanges.clear();
  }

  // Does the region emitted during frame `f` equal its source span
  // verbatim? Equivalent to joining the region's chunks and comparing
  // the strings, but never joins: the length gate answers most cover
  // frames in O(1), the chunk walk bails at the first mismatching
  // chunk, and the per-delta memo lets an enclosing exact frame skip
  // every chunk a contained exact frame already verified. Marks begin
  // and end on chunk boundaries by construction (emit pushes whole
  // chunks), so the memo's bounds always land on a walkable boundary.
  matchesSource(f) {
    if (this.source === null) return false;
    // The length gate reads the span's NOMINAL width, so it is
    // equivalent to slicing only for in-range spans — an out-of-range
    // span is a store-protocol violation (every span derives from
    // token offsets into this source), never something to clamp over.
    if (f.sourceStart < 0 || f.sourceEnd > this.source.length) {
      throw new Error(
        `builder: mark (nodeId ${f.nodeId}, role '${f.role}') has source span ` +
        `[${f.sourceStart}, ${f.sourceEnd}) outside the source text ` +
        `[0, ${this.source.length}) — store-protocol violation`,
      );
    }
    const genEnd = this.length;
    if (genEnd - f.generatedStart !== f.sourceEnd - f.sourceStart) return false;
    const delta = f.sourceStart - f.generatedStart;
    const m = this.exactRanges.get(delta);
    // The memo may begin BEFORE this frame (an earlier sibling at the
    // same delta bridged in) — any part of it inside the frame is
    // still verified, so the walk jumps from wherever it enters the
    // memo range straight to the range's end.
    const skippable = m !== undefined && m.genEnd <= genEnd;
    const chunkEnd = this.chunks.length;
    let pos = f.generatedStart;
    let i = f.chunkStart;
    while (i < chunkEnd) {
      if (ops.on) ops.n++;
      if (skippable && pos >= m.genStart && pos < m.genEnd) {
        pos = m.genEnd;
        i = m.chunkEnd;
        continue;
      }
      const chunk = this.chunks[i];
      if (!this.source.startsWith(chunk, pos + delta)) return false;
      pos += chunk.length;
      i++;
    }
    if (genEnd === f.generatedStart) return true; // zero-width: nothing to memoize
    // A closing mark always ends at the emission frontier, so the memo
    // range is never strictly right of this frame: either they overlap
    // (union them — the range grows along a spine) or the memo ends in
    // a gap left of the frame. Gaps are typically the bytes of marks
    // that never verify (synthetic operators emit `.` between two
    // verified ranges); if the gap's chunks also match the source at
    // this delta, the ranges bridge into one — this is what keeps a
    // member spine's per-level re-verification O(1) instead of
    // O(prefix). An unbridgeable gap means every enclosing frame at
    // this delta mismatches there too, so the old range is spent:
    // replace it with the frontier's.
    if (m !== undefined && (f.generatedStart <= m.genEnd || this.bridges(m, f, delta))) {
      if (f.generatedStart < m.genStart) {
        m.genStart = f.generatedStart;
        m.chunkStart = f.chunkStart;
      }
      m.genEnd = genEnd;
      m.chunkEnd = chunkEnd;
    } else {
      this.exactRanges.set(delta, {
        genStart: f.generatedStart, genEnd, chunkStart: f.chunkStart, chunkEnd,
      });
    }
    return true;
  }

  // Do the chunks between the memo range's end and frame `f`'s start
  // match the source at `delta`? Bails at the first mismatch.
  bridges(m, f, delta) {
    let pos = m.genEnd;
    for (let i = m.chunkEnd; i < f.chunkStart; i++) {
      if (ops.on) ops.n++;
      const chunk = this.chunks[i];
      if (!this.source.startsWith(chunk, pos + delta)) return false;
      pos += chunk.length;
    }
    return true;
  }

  finish() {
    return { code: this.code, mappings: this.rows, tsRegions: this.tsRegions };
  }
}
