//! Parser (Auto-generated)
//!
//! Generated by grammar.zig from a .grammar file.
//! Contains both lexer and parser.

const std = @import("std");
const MAX_ARGS: usize = 32;
const rip = @import("rip.zig");

// SIMD helpers (fallback if simd.zig not available)
const simd = struct {
    fn findByte(haystack: []const u8, needle: u8) usize {
        for (haystack, 0..) |c, i| if (c == needle) return i;
        return haystack.len;
    }
};

// =============================================================================
// TOKEN CATEGORIES
// =============================================================================

pub const TokenCat = enum(u8) {
    ident,
    integer,
    real,
    string_sq,
    string_dq,
    bool_true,
    bool_false,
    plus,
    minus,
    star,
    slash,
    percent,
    power,
    eq,
    ne,
    lt,
    gt,
    le,
    ge,
    and_sym,
    or_sym,
    not_sym,
    assign,
    const_assign,
    plus_assign,
    minus_assign,
    star_assign,
    slash_assign,
    lparen,
    rparen,
    lbrace,
    rbrace,
    lbracket,
    rbracket,
    comma,
    colon,
    arrow,
    fat_arrow,
    dot,
    dotdot,
    pipe,
    indent,
    outdent,
    newline,
    comment,
    eof,
    err,

    // Internal (used by generator)
    skip,
};

// =============================================================================
// TOKEN STRUCT (8 bytes)
// =============================================================================

pub const Token = struct {
    pos: u32,         // Byte position in source (4 bytes)
    len: u16,         // Token length in bytes (2 bytes)
    cat: TokenCat,    // Token category (1 byte)
    pre: u8,          // Preceding whitespace OR dot-level for indent (1 byte)

    comptime {
        std.debug.assert(@sizeOf(Token) == 8);
    }
};

// =============================================================================
// LEXER
// =============================================================================
pub const BaseLexer = struct {
    const Self = @This();

    source: []const u8,
    pos: u32,
    // State variables
    beg: i32,
    paren: i32,
    brace: i32,

    pub fn init(source: []const u8) Self {
        return .{
            .source = source,
            .pos = 0,
            .beg = 1,
            .paren = 0,
            .brace = 0,
        };
    }

    /// Get the text slice for a token (zero-copy into source)
    pub fn text(self: *const Self, tok: Token) []const u8 {
        const start: usize = tok.pos;
        const end: usize = @min(start + tok.len, self.source.len);
        if (start >= self.source.len) return "";
        return self.source[start..end];
    }

    /// Reset lexer to beginning
    pub fn reset(self: *Self) void {
        self.pos = 0;
        self.beg = 1;
        self.paren = 0;
        self.brace = 0;
    }

    /// Peek at current character (0 if at end)
    inline fn peek(self: *const Self) u8 {
        return if (self.pos < self.source.len) self.source[self.pos] else 0;
    }

    /// Peek at character at offset (0 if at end)
    inline fn peekAt(self: *const Self, offset: u32) u8 {
        const p = self.pos + offset;
        return if (p < self.source.len) self.source[p] else 0;
    }

    /// Get next token
    pub fn next(self: *Self) Token {
        return self.matchRules();
    }

    // Character classification flags (generated from grammar patterns)
    const DIGIT: u8 = 1 << 0;
    const LETTER: u8 = 1 << 1;
    const WHITESPACE: u8 = 1 << 2;

    const char_flags: [256]u8 = blk: {
        var table: [256]u8 = [_]u8{0} ** 256;
        for ('0'..'9' + 1) |c| table[c] = DIGIT;
        for ('A'..'Z' + 1) |c| table[c] = LETTER;
        for ('a'..'z' + 1) |c| table[c] = LETTER;
        table['_'] = LETTER;
        table[' '] = WHITESPACE;
        table['\t'] = WHITESPACE;
        break :blk table;
    };

    inline fn isDigit(c: u8) bool {
        return (char_flags[c] & DIGIT) != 0;
    }

    inline fn isLetter(c: u8) bool {
        return (char_flags[c] & LETTER) != 0;
    }

    inline fn isWhitespace(c: u8) bool {
        return (char_flags[c] & WHITESPACE) != 0;
    }

    inline fn isIdentChar(c: u8) bool {
        return isLetter(c) or isDigit(c);
    }
    /// Match lexer rules
    pub fn matchRules(self: *Self) Token {
        // Count whitespace first
        const ws_start = self.pos;
        while (self.pos < self.source.len and isWhitespace(self.source[self.pos])) {
            self.pos += 1;
        }
        const ws_count: u8 = @intCast(@min(self.pos - ws_start, 255));
        // EOF check
        if (self.pos >= self.source.len) {            return Token{ .cat = .eof, .pre = ws_count, .pos = self.pos, .len = 0 };
        }

        const start = self.pos;
        const c = self.source[self.pos];
        // Newline handling (generated from grammar rules)
        if (c == '\n' or c == '\r') {
            if (c == '\r' and self.pos + 1 < self.source.len and self.source[self.pos + 1] == '\n') {
                self.pos += 2;
                self.beg = 1;
                return Token{ .cat = .newline, .pre = ws_count, .pos = start, .len = 2 };
            }
                self.pos += 1;
                self.beg = 1;
                return Token{ .cat = .newline, .pre = ws_count, .pos = start, .len = 1 };
        }
        // From here, clear line-start flag
        self.beg = 0;
        if (c == '"') {            self.pos += 1;
            while (self.pos < self.source.len) {
                const ch = self.source[self.pos];
                if (ch == '"') {
                    self.pos += 1;
                    return Token{ .cat = .string_dq, .pre = ws_count, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (ch == '\\') { self.pos += 2; continue; }
                if (ch == '\n') break;
                self.pos += 1;
            }
            return Token{ .cat = .err, .pre = ws_count, .pos = start, .len = @intCast(self.pos - start) };
        }
        if (c == '\'') {            self.pos += 1;
            while (self.pos < self.source.len) {
                const ch = self.source[self.pos];
                if (ch == '\'') {
                    self.pos += 1;
                    if (self.pos < self.source.len and self.source[self.pos] == '\'') { self.pos += 1; continue; }
                    return Token{ .cat = .string_sq, .pre = ws_count, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (ch == '\n') break;
                self.pos += 1;
            }
            return Token{ .cat = .err, .pre = ws_count, .pos = start, .len = @intCast(self.pos - start) };
        }
        // Number (digit or leading dot followed by digit)
        if (isDigit(c) or (c == '.' and self.pos + 1 < self.source.len and isDigit(self.source[self.pos + 1]))) {
            return self.scanNumber(start, ws_count);
        }
        // Identifier
        if (isLetter(c)) {
            return self.scanIdent(start, ws_count);
        }
        // Comment (scan to end of line)
        if (c == '#') {
            while (self.pos < self.source.len and self.source[self.pos] != '\n') {
                self.pos += 1;
            }
            return Token{ .cat = .comment, .pre = ws_count, .pos = start, .len = @intCast(self.pos - start) };
        }
        // Single/multi-char operators
        self.pos += 1;
        return switch (c) {
            '!' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .ne, .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .not_sym, .pre = ws_count, .pos = start, .len = 1 };
            },
            '%' => Token{ .cat = .percent, .pre = ws_count, .pos = start, .len = 1 },
            '&' => blk: {
                if (self.peek() == '&') {
                    self.pos += 1;
                    break :blk Token{ .cat = .and_sym, .pre = ws_count, .pos = start, .len = 2 };
                }
                self.pos -= 1;
                break :blk Token{ .cat = .err, .pre = ws_count, .pos = start, .len = 1 };
            },
            '(' => blk: {
                self.paren += 1;
                    break :blk Token{ .cat = .lparen, .pre = ws_count, .pos = start, .len = 1 };
            },
            ')' => blk: {
                self.paren -= 1;
                    break :blk Token{ .cat = .rparen, .pre = ws_count, .pos = start, .len = 1 };
            },
            '*' => blk: {
                if (self.peek() == '*') {
                    self.pos += 1;
                    break :blk Token{ .cat = .power, .pre = ws_count, .pos = start, .len = 2 };
                }
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .star_assign, .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .star, .pre = ws_count, .pos = start, .len = 1 };
            },
            '+' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .plus_assign, .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .plus, .pre = ws_count, .pos = start, .len = 1 };
            },
            ',' => Token{ .cat = .comma, .pre = ws_count, .pos = start, .len = 1 },
            '-' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .minus_assign, .pre = ws_count, .pos = start, .len = 2 };
                }
                if (self.peek() == '>') {
                    self.pos += 1;
                    break :blk Token{ .cat = .arrow, .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .minus, .pre = ws_count, .pos = start, .len = 1 };
            },
            '.' => blk: {
                if (self.peek() == '.') {
                    self.pos += 1;
                    break :blk Token{ .cat = .dotdot, .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .dot, .pre = ws_count, .pos = start, .len = 1 };
            },
            '/' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .slash_assign, .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .slash, .pre = ws_count, .pos = start, .len = 1 };
            },
            ':' => Token{ .cat = .colon, .pre = ws_count, .pos = start, .len = 1 },
            '<' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .le, .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .lt, .pre = ws_count, .pos = start, .len = 1 };
            },
            '=' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .eq, .pre = ws_count, .pos = start, .len = 2 };
                }
                if (self.peek() == '!') {
                    self.pos += 1;
                    break :blk Token{ .cat = .const_assign, .pre = ws_count, .pos = start, .len = 2 };
                }
                if (self.peek() == '>') {
                    self.pos += 1;
                    break :blk Token{ .cat = .fat_arrow, .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .assign, .pre = ws_count, .pos = start, .len = 1 };
            },
            '>' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .ge, .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .gt, .pre = ws_count, .pos = start, .len = 1 };
            },
            '[' => Token{ .cat = .lbracket, .pre = ws_count, .pos = start, .len = 1 },
            '\\' => blk: {
                if (self.peek() == '\n') {
                    self.pos += 1;
                    break :blk Token{ .cat = .skip, .pre = ws_count, .pos = start, .len = 2 };
                }
                self.pos -= 1;
                break :blk Token{ .cat = .err, .pre = ws_count, .pos = start, .len = 1 };
            },
            ']' => Token{ .cat = .rbracket, .pre = ws_count, .pos = start, .len = 1 },
            '{' => blk: {
                self.brace += 1;
                    break :blk Token{ .cat = .lbrace, .pre = ws_count, .pos = start, .len = 1 };
            },
            '|' => blk: {
                if (self.peek() == '|') {
                    self.pos += 1;
                    break :blk Token{ .cat = .or_sym, .pre = ws_count, .pos = start, .len = 2 };
                }
                if (self.peek() == '>') {
                    self.pos += 1;
                    break :blk Token{ .cat = .pipe, .pre = ws_count, .pos = start, .len = 2 };
                }
                self.pos -= 1;
                break :blk Token{ .cat = .err, .pre = ws_count, .pos = start, .len = 1 };
            },
            '}' => blk: {
                self.brace -= 1;
                    break :blk Token{ .cat = .rbrace, .pre = ws_count, .pos = start, .len = 1 };
            },
            else => Token{ .cat = .err, .pre = ws_count, .pos = start, .len = 1 },
        };
    }

    /// Scan number (generated from grammar)
    fn scanNumber(self: *Self, start: u32, ws: u8) Token {        var has_decimal = false;        const starts_with_dot = self.source[self.pos] == '.';
        // Integer part
        if (isDigit(self.source[self.pos])) {
            while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                self.pos += 1;
            }
        }
        // Decimal part
        if (self.pos < self.source.len and self.source[self.pos] == '.') {
            const next_c = if (self.pos + 1 < self.source.len) self.source[self.pos + 1] else 0;
            if (isDigit(next_c)) {
                has_decimal = true;
                self.pos += 1;
                while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                    self.pos += 1;
                }
            }
        }
        // Classify
        const token_cat: TokenCat = if (has_decimal or starts_with_dot)
            .real
        else
            .integer;

        return Token{ .cat = token_cat, .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }

    /// Scan identifier (generated from grammar)
    fn scanIdent(self: *Self, start: u32, ws: u8) Token {        // Normal mode: full identifier
        while (self.pos < self.source.len and isIdentChar(self.source[self.pos])) {
            self.pos += 1;
        }
        return Token{ .cat = .ident, .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }
};

pub const Lexer = if (@hasDecl(rip, "Lexer")) rip.Lexer else BaseLexer;

// =============================================================================
// Tag Enum (re-exported from language module)
// =============================================================================
pub const Tag = rip.Tag;

// =============================================================================
// S-Expression (AST Node) - 5 Clean Variants
// =============================================================================

pub const Sexp = union(enum) {
    nil:  void,                                        // Empty (nothing)
    tag:  Tag,                                         // Semantic type (1 byte)
    src:  struct { pos: u32, len: u16, id: u16 },      // Source ref + identity (8 bytes)
    str:  []const u8,                                  // Embedded string (16 bytes)
    list: []const Sexp,                                // Compound: (tag child1 ...)

    /// Get token text from source
    pub fn getText(self: Sexp, source: []const u8) []const u8 {
        return switch (self) {
            .src => |s| source[s.pos..][0..s.len],
            .str => |s| s,
            else => "",
        };
    }

    /// Format for debug output
    pub fn write(self: Sexp, source: []const u8, w: anytype) !void {
        switch (self) {
            .nil => try w.writeAll("_"),
            .tag => |t| try w.print("{s}", .{@tagName(t)}),
            .src => |s| try w.print("{s}", .{source[s.pos..][0..s.len]}),
            .str => |s| try w.print("\"{s}\"", .{s}),
            .list => |items| {
                try w.writeAll("(");
                for (items, 0..) |item, i| {
                    if (i > 0) try w.writeAll(" ");
                    try item.write(source, w);
                }
                try w.writeAll(")");
            },
        }
    }
};

// =============================================================================
// Parser
// =============================================================================

pub const Parser = struct {
    arena: std.heap.ArenaAllocator,
    lexer: Lexer,
    source: []const u8,
    current: Token,
    injected_token: ?u16 = null,
    last_matched_id: u16 = 0,

    state_stack: std.ArrayListUnmanaged(u16) = .{},
    value_stack: std.ArrayListUnmanaged(Sexp) = .{},

    pub fn init(backing_allocator: std.mem.Allocator, source: []const u8) Parser {
        var p = Parser{
            .arena = std.heap.ArenaAllocator.init(backing_allocator),
            .lexer = Lexer.init(source),
            .source = source,
            .current = undefined,
        };
        p.current = p.lexer.next();
        return p;
    }

    pub fn deinit(self: *Parser) void {
        self.arena.deinit();
    }

    fn allocator(self: *Parser) std.mem.Allocator {
        return self.arena.allocator();
    }

    pub fn printError(self: *Parser) void {
        const pos: usize = @min(self.current.pos, self.source.len);
        var line: usize = 1;
        var col: usize = 1;
        var i: usize = 0;
        while (i < pos) : (i += 1) {
            if (self.source[i] == '\n') {
                line += 1;
                col = 1;
            } else {
                col += 1;
            }
        }
        std.debug.print("Parse error at line {d}, column {d}: unexpected {s}\n", .{
            line,
            col,
            @tagName(self.current.cat),
        });
    }

    fn doParse(self: *Parser, start_sym: u16) !Sexp {
        const start_state = getStartState(start_sym);
        self.state_stack.clearRetainingCapacity();
        self.value_stack.clearRetainingCapacity();
        try self.state_stack.append(self.allocator(), start_state);

        while (true) {
            const state = self.state_stack.getLast();
            const sym = if (self.injected_token) |inj| inj else self.tokenToSymbol(self.current);
            var action = getAction(state, sym);

            // X "c" check: if reducing and next char matches with pre==0, shift instead
            if (action < -1 and self.current.pre == 0 and self.current.pos < self.source.len) {
                if (getImmediateShift(state, self.source[self.current.pos])) |shift_target| {
                    action = shift_target;
                }
            }

            if (action == 0) {
                return error.ParseError;
            } else if (action == -1) {
                return self.value_stack.getLast();
            } else if (action > 0) {
                // Shift
                if (self.injected_token != null) {
                    try self.value_stack.append(self.allocator(), .nil);
                    self.injected_token = null;
                } else {
                    try self.value_stack.append(self.allocator(), .{ .src = .{
                        .pos = self.current.pos,
                        .len = self.current.len,
                        .id  = self.last_matched_id,
                    } });
                    self.last_matched_id = 0;
                    self.current = self.lexer.next();
                }
                try self.state_stack.append(self.allocator(), @intCast(action));
            } else {
                // Reduce
                const rule_id: u16 = @intCast(-action - 2);
                var pass: [MAX_ARGS]Sexp = undefined;
                const len = rule_len[rule_id];
                for (0..len) |i| {
                    pass[len - 1 - i] = self.value_stack.pop().?;
                    _ = self.state_stack.pop();
                }

                const result = self.executeAction(rule_id, pass[0..len]);

                if (isAcceptRule(rule_id)) return result;

                try self.value_stack.append(self.allocator(), result);

                const goto_state = self.state_stack.getLast();
                const next = getAction(goto_state, rule_lhs[rule_id]);
                if (next <= 0) return error.ParseError;
                try self.state_stack.append(self.allocator(), @intCast(next));
            }
        }
    }

    /// Spread list helper: [head, ...tail]
    fn spreadList(self: *Parser, head: Sexp, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .{};
        out.append(self.allocator(), head) catch return .nil;
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Spread only: [...tail]
    fn spreadOnly(self: *Parser, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .{};
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Default list handler
    fn list(self: *Parser, pass: []Sexp) Sexp {
        if (pass.len == 0) return .nil;
        if (pass.len == 1) return pass[0];
        var out: std.ArrayListUnmanaged(Sexp) = .{};
        for (pass) |v| out.append(self.allocator(), v) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Build S-expression: (tag items...) with trailing nil trimming
    inline fn sexp(self: *Parser, comptime tag: Tag, items: []const Sexp) Sexp {
        if (items.len == 0) {
            const result = self.allocator().alloc(Sexp, 1) catch return .nil;
            result[0] = .{ .tag = tag };
            return .{ .list = result };
        }
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag ...spread) - tag + spread items
    inline fn sexpSpread(self: *Parser, comptime tag: Tag, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag pos ...spread) - tag + position + spread items
    inline fn sexpPosSpread(self: *Parser, comptime tag: Tag, pos: Sexp, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const skip_pos = (pos == .nil and len == 0);
        const total = if (skip_pos) 1 else len + 2;
        const result = self.allocator().alloc(Sexp, total) catch return .nil;
        result[0] = .{ .tag = tag };
        if (!skip_pos) {
            result[1] = pos;
            if (len > 0) @memcpy(result[2..][0..len], items[0..len]);
        }
        return .{ .list = result };
    }

    fn executeAction(self: *Parser, rule_id: u16, pass: []Sexp) Sexp {
        return switch (rule_id) {
            0 => self.spreadList(pass[0], pass[1]),
            1 => .{ .list = &[_]Sexp{} },
            2 => self.sexpSpread(.@"module", pass[1]),
            3 => pass[1],
            4 => pass[0],
            5 => pass[0],
            6 => .nil,
            7 => .nil,
            8 => pass[0],
            9 => .nil,
            10 => .nil,
            11 => self.list(pass),
            12 => self.list(pass),
            13 => self.list(pass),
            14 => self.list(pass),
            15 => self.sexp(.@"use", &.{pass[1]}),
            16 => self.sexp(.@"fun", &.{pass[1], pass[2], pass[3]}),
            17 => self.sexp(.@"fun", &.{pass[1], pass[2]}),
            18 => self.sexp(.@"sub", &.{pass[1], pass[2], pass[3]}),
            19 => self.sexp(.@"sub", &.{pass[1], pass[2]}),
            20 => self.spreadList(pass[0], pass[1]),
            21 => self.spreadList(pass[1], pass[2]),
            22 => .{ .list = &[_]Sexp{} },
            23 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            24 => self.list(pass),
            25 => self.list(pass),
            26 => self.list(pass),
            27 => self.list(pass),
            28 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"=" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            29 => self.sexp(.@"const", &.{pass[0], pass[2]}),
            30 => self.sexp(.@"or", &.{pass[0], pass[2]}),
            31 => self.list(pass),
            32 => self.sexp(.@"and", &.{pass[0], pass[2]}),
            33 => self.list(pass),
            34 => self.sexp(.@"eq", &.{pass[0], pass[2]}),
            35 => self.sexp(.@"ne", &.{pass[0], pass[2]}),
            36 => self.sexp(.@"lt", &.{pass[0], pass[2]}),
            37 => self.sexp(.@"gt", &.{pass[0], pass[2]}),
            38 => self.sexp(.@"le", &.{pass[0], pass[2]}),
            39 => self.sexp(.@"ge", &.{pass[0], pass[2]}),
            40 => self.list(pass),
            41 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"+" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            42 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"-" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            43 => self.list(pass),
            44 => self.sexp(.@"*", &.{pass[0], pass[2]}),
            45 => self.sexp(.@"/", &.{pass[0], pass[2]}),
            46 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"%" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            47 => self.list(pass),
            48 => self.sexp(.@"**", &.{pass[0], pass[2]}),
            49 => self.list(pass),
            50 => self.sexp(.@"not", &.{pass[1]}),
            51 => self.sexp(.@"neg", &.{pass[1]}),
            52 => self.list(pass),
            53 => self.sexp(.@"await", &.{pass[0], pass[2]}),
            54 => self.sexp(.@"call", &.{pass[0], pass[1]}),
            55 => self.sexpPosSpread(.@"call", pass[0], pass[2]),
            56 => self.list(pass),
            57 => self.list(pass),
            58 => self.spreadList(pass[0], pass[1]),
            59 => .{ .list = &[_]Sexp{} },
            60 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), pass[0]) catch break :blk .nil; if (pass[1] == .list) for (pass[1].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            61 => .{ .list = &[_]Sexp{} },
            62 => self.list(pass),
            63 => self.list(pass),
            64 => self.list(pass),
            65 => self.list(pass),
            66 => self.list(pass),
            67 => self.list(pass),
            68 => self.list(pass),
            69 => pass[1],
            70 => self.list(pass),
            71 => self.spreadList(pass[0], pass[1]),
            72 => .{ .list = &[_]Sexp{} },
            73 => self.sexpSpread(.@"block", pass[1]),
            74 => self.sexpSpread(.@"block", pass[1]),
            75 => self.sexp(.@"if", &.{pass[1], pass[2]}),
            76 => self.sexp(.@"if", &.{pass[1], pass[2], pass[3]}),
            77 => pass[1],
            78 => self.sexp(.@"else", &.{pass[1]}),
            79 => self.sexp(.@"return", &.{pass[1]}),
            80 => self.sexp(.@"return", &.{}),
            81 => self.list(pass),
            82 => self.list(pass),
            else => .nil,
        };
    }

    fn tokenToSymbol(self: *Parser, token: Token) u16 {
        return switch (token.cat) {
            .eof => 1,
            .ident => self.identToSymbol(token),
            .newline => 30,
            .comment => 31,
            .integer => 60,
            .real => 61,
            .string_sq => 62,
            .string_dq => 63,
            .indent => 66,
            .outdent => 68,
            .comma => 36,
            .assign => 39,
            .lt => 45,
            .gt => 46,
            .plus => 49,
            .minus => 50,
            .star => 51,
            .slash => 52,
            .percent => 53,
            .not_sym => 55,
            .lparen => 56,
            .rparen => 57,
            .const_assign => 40,
            .or_sym => 41,
            .and_sym => 42,
            .eq => 43,
            .ne => 44,
            .le => 47,
            .ge => 48,
            .power => 54,
            else => 2, // error
        };
    }

    fn identToSymbol(self: *Parser, token: Token) u16 {
        const text = self.source[token.pos..][0..token.len];
        if (text.len == 0) return SYM_IDENT;
        if (self.try_ident_as_keyword(token, text)) |sym| return sym;
        return SYM_IDENT;
    }

    fn try_ident_as_keyword(self: *Parser, token: Token, text: []const u8) ?u16 {
        _ = token;
        const state = self.state_stack.getLast();
        if (rip.keyword_as(text)) |id| {
            const id_idx = @intFromEnum(id);
            const sym = keyword_to_symbol[id_idx];
            if (sym != 0 and getAction(state, sym) != 0) {
                self.last_matched_id = @intCast(id_idx);
                return sym;
            }
            const fallback = keyword_fallback_symbol;
            if (fallback != 0 and getAction(state, fallback) != 0) {
                self.last_matched_id = @intCast(id_idx);
                return fallback;
            }
        }
        return null;
    }

    pub fn parseProgram(self: *Parser) !Sexp {
        self.injected_token = SYM_program_START;
        return self.doParse(SYM_program);
    }
    pub fn parseExpr(self: *Parser) !Sexp {
        self.injected_token = SYM_expr_START;
        return self.doParse(SYM_expr);
    }
};

// Symbol IDs
const SYM_program: u16 = 3;
const SYM_program_START: u16 = 72;
const SYM_expr: u16 = 4;
const SYM_expr_START: u16 = 74;
const SYM_IDENT: u16 = 33;

// Mapping from rip.keyword_id to grammar symbol IDs (computed at comptime)
const keyword_to_symbol = blk: {
    var arr: [512]u16 = .{0} ** 512;
    if (@hasField(rip.keyword_id, "NEWLINE")) arr[@intFromEnum(rip.keyword_id.NEWLINE)] = 30;
    if (@hasField(rip.keyword_id, "COMMENT")) arr[@intFromEnum(rip.keyword_id.COMMENT)] = 31;
    if (@hasField(rip.keyword_id, "USE")) arr[@intFromEnum(rip.keyword_id.USE)] = 32;
    if (@hasField(rip.keyword_id, "IDENT")) arr[@intFromEnum(rip.keyword_id.IDENT)] = 33;
    if (@hasField(rip.keyword_id, "FUN")) arr[@intFromEnum(rip.keyword_id.FUN)] = 34;
    if (@hasField(rip.keyword_id, "SUB")) arr[@intFromEnum(rip.keyword_id.SUB)] = 35;
    if (@hasField(rip.keyword_id, "INTEGER")) arr[@intFromEnum(rip.keyword_id.INTEGER)] = 60;
    if (@hasField(rip.keyword_id, "REAL")) arr[@intFromEnum(rip.keyword_id.REAL)] = 61;
    if (@hasField(rip.keyword_id, "STRING_SQ")) arr[@intFromEnum(rip.keyword_id.STRING_SQ)] = 62;
    if (@hasField(rip.keyword_id, "STRING_DQ")) arr[@intFromEnum(rip.keyword_id.STRING_DQ)] = 63;
    if (@hasField(rip.keyword_id, "TRUE")) arr[@intFromEnum(rip.keyword_id.TRUE)] = 64;
    if (@hasField(rip.keyword_id, "FALSE")) arr[@intFromEnum(rip.keyword_id.FALSE)] = 65;
    if (@hasField(rip.keyword_id, "INDENT")) arr[@intFromEnum(rip.keyword_id.INDENT)] = 66;
    if (@hasField(rip.keyword_id, "OUTDENT")) arr[@intFromEnum(rip.keyword_id.OUTDENT)] = 68;
    if (@hasField(rip.keyword_id, "IF")) arr[@intFromEnum(rip.keyword_id.IF)] = 69;
    if (@hasField(rip.keyword_id, "ELSE")) arr[@intFromEnum(rip.keyword_id.ELSE)] = 70;
    if (@hasField(rip.keyword_id, "RETURN")) arr[@intFromEnum(rip.keyword_id.RETURN)] = 71;
    break :blk arr;
};
const keyword_fallback_symbol: u16 = 0;

const rule_lhs = [_]u16{ 29, 29, 3, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7, 7, 7, 8, 9, 9, 10, 10, 37, 38, 38, 11, 4, 4, 4, 4, 12, 13, 14, 14, 15, 15, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 18, 18, 18, 18, 19, 19, 20, 20, 20, 21, 21, 21, 21, 58, 59, 59, 22, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 67, 67, 24, 25, 26, 26, 27, 27, 28, 28, 73, 75 };
const rule_len = [_]u8{ 2, 0, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 4, 3, 4, 3, 2, 3, 0, 1, 1, 1, 1, 1, 3, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 3, 1, 3, 3, 3, 1, 3, 1, 2, 2, 1, 3, 2, 4, 1, 2, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 0, 3, 3, 3, 4, 2, 2, 2, 1, 2, 2 };

// Parse Table: 130 states × 76 symbols
const NUM_STATES = 130;
const NUM_SYMBOLS = 76;

const sparse = [NUM_STATES][]const i16{
    &.{3,2,72,3},
    &.{4,29,12,12,13,5,14,18,15,15,16,6,17,9,18,28,19,24,20,14,21,11,23,30,25,20,26,21,33,27,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22,69,13,74,17},
    &.{1,-1},
    &.{1,-3,4,43,5,40,7,36,8,37,9,33,10,35,12,12,13,5,14,18,15,15,16,6,17,9,18,28,19,24,20,14,21,11,23,30,25,20,26,21,29,41,30,34,31,42,32,38,33,27,34,39,35,32,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22,69,13,74,17},
    &.{1,-69,30,-69,31,-69,32,-69,33,-69,34,-69,35,-69,36,-69,41,-69,42,-69,43,-69,44,-69,45,-69,46,-69,47,-69,48,-69,49,-69,50,-69,51,-69,52,-69,53,-69,54,-69,55,-69,56,-69,57,-69,60,-69,61,-69,62,-69,63,-69,64,-69,65,-69,66,-69,69,-69,74,-69},
    &.{1,-28,30,-28,31,-28,32,-28,33,-28,34,-28,35,-28,36,-28,50,-28,55,-28,56,-28,57,-28,60,-28,61,-28,62,-28,63,-28,64,-28,65,-28,66,-28,69,-28,74,-28},
    &.{1,-35,30,-35,31,-35,32,-35,33,-35,34,-35,35,-35,36,-35,41,-35,42,-35,50,-35,55,-35,56,-35,57,-35,60,-35,61,-35,62,-35,63,-35,64,-35,65,-35,66,-35,69,-35,74,-35},
    &.{1,-68,30,-68,31,-68,32,-68,33,-68,34,-68,35,-68,36,-68,41,-68,42,-68,43,-68,44,-68,45,-68,46,-68,47,-68,48,-68,49,-68,50,-68,51,-68,52,-68,53,-68,54,-68,55,-68,56,-68,57,-68,60,-68,61,-68,62,-68,63,-68,64,-68,65,-68,66,-68,69,-68,74,-68},
    &.{1,-70,30,-70,31,-70,32,-70,33,-70,34,-70,35,-70,36,-70,41,-70,42,-70,43,-70,44,-70,45,-70,46,-70,47,-70,48,-70,49,-70,50,-70,51,-70,52,-70,53,-70,54,-70,55,-70,56,-70,57,-70,60,-70,61,-70,62,-70,63,-70,64,-70,65,-70,66,-70,69,-70,74,-70},
    &.{1,-42,30,-42,31,-42,32,-42,33,-42,34,-42,35,-42,36,-42,41,-42,42,-42,43,46,44,48,45,51,46,50,47,47,48,45,49,44,50,49,55,-42,56,-42,57,-42,60,-42,61,-42,62,-42,63,-42,64,-42,65,-42,66,-42,69,-42,74,-42},
    &.{1,-65,30,-65,31,-65,32,-65,33,-65,34,-65,35,-65,36,-65,41,-65,42,-65,43,-65,44,-65,45,-65,46,-65,47,-65,48,-65,49,-65,50,-65,51,-65,52,-65,53,-65,54,-65,55,-65,56,-65,57,-65,60,-65,61,-65,62,-65,63,-65,64,-65,65,-65,66,-65,69,-65,74,-65},
    &.{1,-54,23,55,25,20,30,-54,31,-54,32,-54,33,52,34,-54,35,-54,36,-54,41,-54,42,-54,43,-54,44,-54,45,-54,46,-54,47,-54,48,-54,49,-54,50,-54,51,-54,52,-54,53,-54,54,-54,55,53,56,54,57,-54,60,10,61,19,62,26,63,7,64,4,65,8,66,22,69,-54,74,-54},
    &.{1,-27,30,-27,31,-27,32,-27,33,-27,34,-27,35,-27,36,-27,50,-27,55,-27,56,-27,57,-27,60,-27,61,-27,62,-27,63,-27,64,-27,65,-27,66,-27,69,-27,74,-27},
    &.{4,56,12,12,13,5,14,18,15,15,16,6,17,9,18,28,19,24,20,14,21,11,23,30,25,20,26,21,33,27,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22,69,13,74,17},
    &.{1,-51,30,-51,31,-51,32,-51,33,-51,34,-51,35,-51,36,-51,41,-51,42,-51,43,-51,44,-51,45,-51,46,-51,47,-51,48,-51,49,-51,50,-51,51,-51,52,-51,53,-51,54,57,55,-51,56,-51,57,-51,60,-51,61,-51,62,-51,63,-51,64,-51,65,-51,66,-51,69,-51,74,-51},
    &.{1,-33,30,-33,31,-33,32,-33,33,-33,34,-33,35,-33,36,-33,41,-33,42,58,50,-33,55,-33,56,-33,57,-33,60,-33,61,-33,62,-33,63,-33,64,-33,65,-33,66,-33,69,-33,74,-33},
    &.{4,59,12,12,13,5,14,18,15,15,16,6,17,9,18,28,19,24,20,14,21,11,23,30,25,20,26,21,33,27,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22,69,13,74,17},
    &.{4,60,12,12,13,5,14,18,15,15,16,6,17,9,18,28,19,24,20,14,21,11,23,30,25,20,26,21,33,27,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22,69,13,74,17},
    &.{1,-29,30,-29,31,-29,32,-29,33,-29,34,-29,35,-29,36,-29,41,61,50,-29,55,-29,56,-29,57,-29,60,-29,61,-29,62,-29,63,-29,64,-29,65,-29,66,-29,69,-29,74,-29},
    &.{1,-66,30,-66,31,-66,32,-66,33,-66,34,-66,35,-66,36,-66,41,-66,42,-66,43,-66,44,-66,45,-66,46,-66,47,-66,48,-66,49,-66,50,-66,51,-66,52,-66,53,-66,54,-66,55,-66,56,-66,57,-66,60,-66,61,-66,62,-66,63,-66,64,-66,65,-66,66,-66,69,-66,74,-66},
    &.{1,-72,30,-72,31,-72,32,-72,33,-72,34,-72,35,-72,36,-72,41,-72,42,-72,43,-72,44,-72,45,-72,46,-72,47,-72,48,-72,49,-72,50,-72,51,-72,52,-72,53,-72,54,-72,55,-72,56,-72,57,-72,60,-72,61,-72,62,-72,63,-72,64,-72,65,-72,66,-72,69,-72,74,-72},
    &.{1,-26,30,-26,31,-26,32,-26,33,-26,34,-26,35,-26,36,-26,50,-26,55,-26,56,-26,57,-26,60,-26,61,-26,62,-26,63,-26,64,-26,65,-26,66,-26,69,-26,74,-26},
    &.{4,43,6,65,7,64,8,37,9,33,10,35,12,12,13,5,14,18,15,15,16,6,17,9,18,28,19,24,20,14,21,11,23,30,25,20,26,21,30,63,31,66,32,38,33,27,34,39,35,32,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22,67,62,68,-74,69,13,74,17},
    &.{20,67,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{1,-49,30,-49,31,-49,32,-49,33,-49,34,-49,35,-49,36,-49,41,-49,42,-49,43,-49,44,-49,45,-49,46,-49,47,-49,48,-49,49,-49,50,-49,51,-49,52,-49,53,-49,55,-49,56,-49,57,-49,60,-49,61,-49,62,-49,63,-49,64,-49,65,-49,66,-49,69,-49,74,-49},
    &.{20,68,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{1,-67,30,-67,31,-67,32,-67,33,-67,34,-67,35,-67,36,-67,41,-67,42,-67,43,-67,44,-67,45,-67,46,-67,47,-67,48,-67,49,-67,50,-67,51,-67,52,-67,53,-67,54,-67,55,-67,56,-67,57,-67,60,-67,61,-67,62,-67,63,-67,64,-67,65,-67,66,-67,69,-67,74,-67},
    &.{1,-64,30,-64,31,-64,32,-64,33,-64,34,-64,35,-64,36,-64,39,70,40,69,41,-64,42,-64,43,-64,44,-64,45,-64,46,-64,47,-64,48,-64,49,-64,50,-64,51,-64,52,-64,53,-64,54,-64,55,-64,56,-64,57,-64,60,-64,61,-64,62,-64,63,-64,64,-64,65,-64,66,-64,69,-64,74,-64},
    &.{1,-45,30,-45,31,-45,32,-45,33,-45,34,-45,35,-45,36,-45,41,-45,42,-45,43,-45,44,-45,45,-45,46,-45,47,-45,48,-45,49,-45,50,-45,51,72,52,71,53,73,55,-45,56,-45,57,-45,60,-45,61,-45,62,-45,63,-45,64,-45,65,-45,66,-45,69,-45,74,-45},
    &.{1,-1},
    &.{1,-58,30,-58,31,-58,32,-58,33,-58,34,-58,35,-58,36,-58,41,-58,42,-58,43,-58,44,-58,45,-58,46,-58,47,-58,48,-58,49,-58,50,-58,51,-58,52,-58,53,-58,54,-58,55,-58,56,-58,57,-58,60,-58,61,-58,62,-58,63,-58,64,-58,65,-58,66,-58,69,-58,74,-58},
    &.{1,-1},
    &.{33,75},
    &.{1,-14,30,-14,31,-14,32,-14,33,-14,34,-14,35,-14,50,-14,55,-14,56,-14,60,-14,61,-14,62,-14,63,-14,64,-14,65,-14,66,-14,69,-14,74,-14},
    &.{1,-9,30,-9,31,-9,32,-9,33,-9,34,-9,35,-9,50,-9,55,-9,56,-9,60,-9,61,-9,62,-9,63,-9,64,-9,65,-9,66,-9,69,-9,74,-9},
    &.{1,-15,30,-15,31,-15,32,-15,33,-15,34,-15,35,-15,50,-15,55,-15,56,-15,60,-15,61,-15,62,-15,63,-15,64,-15,65,-15,66,-15,69,-15,74,-15},
    &.{1,-7,30,76,31,-7,32,-7,33,-7,34,-7,35,-7,50,-7,55,-7,56,-7,60,-7,61,-7,62,-7,63,-7,64,-7,65,-7,66,-7,69,-7,74,-7},
    &.{1,-13,30,-13,31,-13,32,-13,33,-13,34,-13,35,-13,50,-13,55,-13,56,-13,60,-13,61,-13,62,-13,63,-13,64,-13,65,-13,66,-13,69,-13,74,-13},
    &.{33,77},
    &.{33,78},
    &.{1,-3,4,43,5,40,7,36,8,37,9,33,10,35,12,12,13,5,14,18,15,15,16,6,17,9,18,28,19,24,20,14,21,11,23,30,25,20,26,21,29,79,30,34,31,42,32,38,33,27,34,39,35,32,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22,69,13,74,17},
    &.{1,-4},
    &.{1,-8,30,-8,31,-8,32,-8,33,-8,34,-8,35,-8,50,-8,55,-8,56,-8,60,-8,61,-8,62,-8,63,-8,64,-8,65,-8,66,-8,69,-8,74,-8},
    &.{1,-16,30,-16,31,-16,32,-16,33,-16,34,-16,35,-16,50,-16,55,-16,56,-16,60,-16,61,-16,62,-16,63,-16,64,-16,65,-16,66,-16,69,-16,74,-16},
    &.{18,80,19,24,20,14,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{17,81,18,28,19,24,20,14,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{17,82,18,28,19,24,20,14,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{17,83,18,28,19,24,20,14,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{17,84,18,28,19,24,20,14,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{18,85,19,24,20,14,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{17,86,18,28,19,24,20,14,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{17,87,18,28,19,24,20,14,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{1,-64,30,-64,31,-64,32,-64,33,-64,34,-64,35,-64,36,-64,41,-64,42,-64,43,-64,44,-64,45,-64,46,-64,47,-64,48,-64,49,-64,50,-64,51,-64,52,-64,53,-64,54,-64,55,-64,56,-64,57,-64,60,-64,61,-64,62,-64,63,-64,64,-64,65,-64,66,-64,69,-64,74,-64},
    &.{23,88,25,20,33,52,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{4,90,12,12,13,5,14,18,15,15,16,6,17,9,18,28,19,24,20,14,21,11,22,89,23,30,25,20,26,21,33,27,50,25,55,23,56,16,57,-63,60,10,61,19,62,26,63,7,64,4,65,8,66,22,69,13,74,17},
    &.{1,-56,30,-56,31,-56,32,-56,33,-56,34,-56,35,-56,36,-56,41,-56,42,-56,43,-56,44,-56,45,-56,46,-56,47,-56,48,-56,49,-56,50,-56,51,-56,52,-56,53,-56,54,-56,55,-56,56,-56,57,-56,60,-56,61,-56,62,-56,63,-56,64,-56,65,-56,66,-56,69,-56,74,-56},
    &.{24,91,66,92},
    &.{19,93,20,14,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{16,94,17,9,18,28,19,24,20,14,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{57,95},
    &.{1,-5,30,-5,31,-5,32,-5,33,-5,34,-5,35,-5,36,-5,50,-5,55,-5,56,-5,57,-5,60,-5,61,-5,62,-5,63,-5,64,-5,65,-5,66,-5,69,-5,74,-5},
    &.{15,96,16,6,17,9,18,28,19,24,20,14,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{68,97},
    &.{30,-12,31,-12,32,-12,33,-12,34,-12,35,-12,50,-12,55,-12,56,-12,60,-12,61,-12,62,-12,63,-12,64,-12,65,-12,66,-12,68,-12,69,-12,74,-12},
    &.{30,98},
    &.{4,43,6,65,7,64,8,37,9,33,10,35,12,12,13,5,14,18,15,15,16,6,17,9,18,28,19,24,20,14,21,11,23,30,25,20,26,21,30,63,31,66,32,38,33,27,34,39,35,32,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22,67,99,68,-74,69,13,74,17},
    &.{30,100},
    &.{1,-52,30,-52,31,-52,32,-52,33,-52,34,-52,35,-52,36,-52,41,-52,42,-52,43,-52,44,-52,45,-52,46,-52,47,-52,48,-52,49,-52,50,-52,51,-52,52,-52,53,-52,54,-52,55,-52,56,-52,57,-52,60,-52,61,-52,62,-52,63,-52,64,-52,65,-52,66,-52,69,-52,74,-52},
    &.{1,-53,30,-53,31,-53,32,-53,33,-53,34,-53,35,-53,36,-53,41,-53,42,-53,43,-53,44,-53,45,-53,46,-53,47,-53,48,-53,49,-53,50,-53,51,-53,52,-53,53,-53,54,-53,55,-53,56,-53,57,-53,60,-53,61,-53,62,-53,63,-53,64,-53,65,-53,66,-53,69,-53,74,-53},
    &.{4,101,12,12,13,5,14,18,15,15,16,6,17,9,18,28,19,24,20,14,21,11,23,30,25,20,26,21,33,27,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22,69,13,74,17},
    &.{4,102,12,12,13,5,14,18,15,15,16,6,17,9,18,28,19,24,20,14,21,11,23,30,25,20,26,21,33,27,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22,69,13,74,17},
    &.{19,103,20,14,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{19,104,20,14,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{19,105,20,14,21,11,23,30,25,20,33,52,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22},
    &.{1,-1},
    &.{11,108,24,106,33,107,37,109,66,92},
    &.{1,-6,30,-6,31,-6,32,-6,33,-6,34,-6,35,-6,50,-6,55,-6,56,-6,60,-6,61,-6,62,-6,63,-6,64,-6,65,-6,66,-6,69,-6,74,-6},
    &.{1,-17,30,-17,31,-17,32,-17,33,-17,34,-17,35,-17,50,-17,55,-17,56,-17,60,-17,61,-17,62,-17,63,-17,64,-17,65,-17,66,-17,69,-17,74,-17},
    &.{11,111,24,110,33,107,37,109,66,92},
    &.{1,-2},
    &.{1,-43,30,-43,31,-43,32,-43,33,-43,34,-43,35,-43,36,-43,41,-43,42,-43,43,-43,44,-43,45,-43,46,-43,47,-43,48,-43,49,-43,50,-43,51,72,52,71,53,73,55,-43,56,-43,57,-43,60,-43,61,-43,62,-43,63,-43,64,-43,65,-43,66,-43,69,-43,74,-43},
    &.{1,-41,30,-41,31,-41,32,-41,33,-41,34,-41,35,-41,36,-41,41,-41,42,-41,49,44,50,49,55,-41,56,-41,57,-41,60,-41,61,-41,62,-41,63,-41,64,-41,65,-41,66,-41,69,-41,74,-41},
    &.{1,-36,30,-36,31,-36,32,-36,33,-36,34,-36,35,-36,36,-36,41,-36,42,-36,49,44,50,49,55,-36,56,-36,57,-36,60,-36,61,-36,62,-36,63,-36,64,-36,65,-36,66,-36,69,-36,74,-36},
    &.{1,-40,30,-40,31,-40,32,-40,33,-40,34,-40,35,-40,36,-40,41,-40,42,-40,49,44,50,49,55,-40,56,-40,57,-40,60,-40,61,-40,62,-40,63,-40,64,-40,65,-40,66,-40,69,-40,74,-40},
    &.{1,-37,30,-37,31,-37,32,-37,33,-37,34,-37,35,-37,36,-37,41,-37,42,-37,49,44,50,49,55,-37,56,-37,57,-37,60,-37,61,-37,62,-37,63,-37,64,-37,65,-37,66,-37,69,-37,74,-37},
    &.{1,-44,30,-44,31,-44,32,-44,33,-44,34,-44,35,-44,36,-44,41,-44,42,-44,43,-44,44,-44,45,-44,46,-44,47,-44,48,-44,49,-44,50,-44,51,72,52,71,53,73,55,-44,56,-44,57,-44,60,-44,61,-44,62,-44,63,-44,64,-44,65,-44,66,-44,69,-44,74,-44},
    &.{1,-39,30,-39,31,-39,32,-39,33,-39,34,-39,35,-39,36,-39,41,-39,42,-39,49,44,50,49,55,-39,56,-39,57,-39,60,-39,61,-39,62,-39,63,-39,64,-39,65,-39,66,-39,69,-39,74,-39},
    &.{1,-38,30,-38,31,-38,32,-38,33,-38,34,-38,35,-38,36,-38,41,-38,42,-38,49,44,50,49,55,-38,56,-38,57,-38,60,-38,61,-38,62,-38,63,-38,64,-38,65,-38,66,-38,69,-38,74,-38},
    &.{1,-55,30,-55,31,-55,32,-55,33,-55,34,-55,35,-55,36,-55,41,-55,42,-55,43,-55,44,-55,45,-55,46,-55,47,-55,48,-55,49,-55,50,-55,51,-55,52,-55,53,-55,54,-55,55,-55,56,-55,57,-55,60,-55,61,-55,62,-55,63,-55,64,-55,65,-55,66,-55,69,-55,74,-55},
    &.{57,112},
    &.{36,114,57,95,58,115,59,113},
    &.{1,-77,27,116,30,-77,31,-77,32,-77,33,-77,34,-77,35,-77,36,-77,50,-77,55,-77,56,-77,57,-77,60,-77,61,-77,62,-77,63,-77,64,-77,65,-77,66,-77,69,-77,70,117,74,-77},
    &.{4,43,6,65,7,64,8,37,9,33,10,35,12,12,13,5,14,18,15,15,16,6,17,9,18,28,19,24,20,14,21,11,23,30,25,20,26,21,30,63,31,66,32,38,33,27,34,39,35,32,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22,67,118,68,-74,69,13,74,17},
    &.{1,-50,30,-50,31,-50,32,-50,33,-50,34,-50,35,-50,36,-50,41,-50,42,-50,43,-50,44,-50,45,-50,46,-50,47,-50,48,-50,49,-50,50,-50,51,-50,52,-50,53,-50,55,-50,56,-50,57,-50,60,-50,61,-50,62,-50,63,-50,64,-50,65,-50,66,-50,69,-50,74,-50},
    &.{1,-34,30,-34,31,-34,32,-34,33,-34,34,-34,35,-34,36,-34,41,-34,42,-34,50,-34,55,-34,56,-34,57,-34,60,-34,61,-34,62,-34,63,-34,64,-34,65,-34,66,-34,69,-34,74,-34},
    &.{1,-71,30,-71,31,-71,32,-71,33,-71,34,-71,35,-71,36,-71,41,-71,42,-71,43,-71,44,-71,45,-71,46,-71,47,-71,48,-71,49,-71,50,-71,51,-71,52,-71,53,-71,54,-71,55,-71,56,-71,57,-71,60,-71,61,-71,62,-71,63,-71,64,-71,65,-71,66,-71,69,-71,74,-71},
    &.{1,-32,30,-32,31,-32,32,-32,33,-32,34,-32,35,-32,36,-32,41,-32,42,58,50,-32,55,-32,56,-32,57,-32,60,-32,61,-32,62,-32,63,-32,64,-32,65,-32,66,-32,69,-32,74,-32},
    &.{1,-76,30,-76,31,-76,32,-76,33,-76,34,-76,35,-76,36,-76,41,-76,42,-76,43,-76,44,-76,45,-76,46,-76,47,-76,48,-76,49,-76,50,-76,51,-76,52,-76,53,-76,54,-76,55,-76,56,-76,57,-76,60,-76,61,-76,62,-76,63,-76,64,-76,65,-76,66,-76,69,-76,74,-76},
    &.{30,-10,31,-10,32,-10,33,-10,34,-10,35,-10,50,-10,55,-10,56,-10,60,-10,61,-10,62,-10,63,-10,64,-10,65,-10,66,-10,68,-10,69,-10,74,-10},
    &.{68,-73},
    &.{30,-11,31,-11,32,-11,33,-11,34,-11,35,-11,50,-11,55,-11,56,-11,60,-11,61,-11,62,-11,63,-11,64,-11,65,-11,66,-11,68,-11,69,-11,74,-11},
    &.{1,-31,30,-31,31,-31,32,-31,33,-31,34,-31,35,-31,36,-31,50,-31,55,-31,56,-31,57,-31,60,-31,61,-31,62,-31,63,-31,64,-31,65,-31,66,-31,69,-31,74,-31},
    &.{1,-30,30,-30,31,-30,32,-30,33,-30,34,-30,35,-30,36,-30,50,-30,55,-30,56,-30,57,-30,60,-30,61,-30,62,-30,63,-30,64,-30,65,-30,66,-30,69,-30,74,-30},
    &.{1,-47,30,-47,31,-47,32,-47,33,-47,34,-47,35,-47,36,-47,41,-47,42,-47,43,-47,44,-47,45,-47,46,-47,47,-47,48,-47,49,-47,50,-47,51,-47,52,-47,53,-47,55,-47,56,-47,57,-47,60,-47,61,-47,62,-47,63,-47,64,-47,65,-47,66,-47,69,-47,74,-47},
    &.{1,-46,30,-46,31,-46,32,-46,33,-46,34,-46,35,-46,36,-46,41,-46,42,-46,43,-46,44,-46,45,-46,46,-46,47,-46,48,-46,49,-46,50,-46,51,-46,52,-46,53,-46,55,-46,56,-46,57,-46,60,-46,61,-46,62,-46,63,-46,64,-46,65,-46,66,-46,69,-46,74,-46},
    &.{1,-48,30,-48,31,-48,32,-48,33,-48,34,-48,35,-48,36,-48,41,-48,42,-48,43,-48,44,-48,45,-48,46,-48,47,-48,48,-48,49,-48,50,-48,51,-48,52,-48,53,-48,55,-48,56,-48,57,-48,60,-48,61,-48,62,-48,63,-48,64,-48,65,-48,66,-48,69,-48,74,-48},
    &.{1,-21,30,-21,31,-21,32,-21,33,-21,34,-21,35,-21,50,-21,55,-21,56,-21,60,-21,61,-21,62,-21,63,-21,64,-21,65,-21,66,-21,69,-21,74,-21},
    &.{36,120,38,119,66,-24},
    &.{24,121,66,92},
    &.{66,-25},
    &.{1,-19,30,-19,31,-19,32,-19,33,-19,34,-19,35,-19,50,-19,55,-19,56,-19,60,-19,61,-19,62,-19,63,-19,64,-19,65,-19,66,-19,69,-19,74,-19},
    &.{24,122,66,92},
    &.{1,-57,30,-57,31,-57,32,-57,33,-57,34,-57,35,-57,36,-57,41,-57,42,-57,43,-57,44,-57,45,-57,46,-57,47,-57,48,-57,49,-57,50,-57,51,-57,52,-57,53,-57,54,-57,55,-57,56,-57,57,-57,60,-57,61,-57,62,-57,63,-57,64,-57,65,-57,66,-57,69,-57,74,-57},
    &.{57,-62},
    &.{4,123,12,12,13,5,14,18,15,15,16,6,17,9,18,28,19,24,20,14,21,11,23,30,25,20,26,21,33,27,50,25,55,23,56,16,60,10,61,19,62,26,63,7,64,4,65,8,66,22,69,13,74,17},
    &.{36,114,57,-61,58,115,59,124},
    &.{1,-78,30,-78,31,-78,32,-78,33,-78,34,-78,35,-78,36,-78,50,-78,55,-78,56,-78,57,-78,60,-78,61,-78,62,-78,63,-78,64,-78,65,-78,66,-78,69,-78,74,-78},
    &.{24,125,26,126,66,92,69,13},
    &.{68,127},
    &.{66,-22},
    &.{33,128},
    &.{1,-20,30,-20,31,-20,32,-20,33,-20,34,-20,35,-20,50,-20,55,-20,56,-20,60,-20,61,-20,62,-20,63,-20,64,-20,65,-20,66,-20,69,-20,74,-20},
    &.{1,-18,30,-18,31,-18,32,-18,33,-18,34,-18,35,-18,50,-18,55,-18,56,-18,60,-18,61,-18,62,-18,63,-18,64,-18,65,-18,66,-18,69,-18,74,-18},
    &.{36,-59,57,-59},
    &.{57,-60},
    &.{1,-80,30,-80,31,-80,32,-80,33,-80,34,-80,35,-80,36,-80,50,-80,55,-80,56,-80,57,-80,60,-80,61,-80,62,-80,63,-80,64,-80,65,-80,66,-80,69,-80,74,-80},
    &.{1,-79,30,-79,31,-79,32,-79,33,-79,34,-79,35,-79,36,-79,50,-79,55,-79,56,-79,57,-79,60,-79,61,-79,62,-79,63,-79,64,-79,65,-79,66,-79,69,-79,74,-79},
    &.{1,-75,30,-75,31,-75,32,-75,33,-75,34,-75,35,-75,36,-75,50,-75,55,-75,56,-75,57,-75,60,-75,61,-75,62,-75,63,-75,64,-75,65,-75,66,-75,69,-75,70,-75,74,-75},
    &.{36,120,38,129,66,-24},
    &.{66,-23},
};

const parse_table = blk: {
    @setEvalBranchQuota(100000);
    var t: [NUM_STATES][NUM_SYMBOLS]i16 = .{.{0} ** NUM_SYMBOLS} ** NUM_STATES;
    for (sparse, 0..) |row, state| {
        var i: usize = 0;
        while (i < row.len) : (i += 2) {
            t[state][@intCast(row[i])] = row[i + 1];
        }
    }
    break :blk t;
};

fn getAction(state: u16, sym: u16) i16 {
    return parse_table[state][sym];
}
// X "c" excludes: shift instead of reduce when pre==0 and char matches
const x_excludes = [_]struct { state: u16, char: u8, shift: u16 }{
};

fn getImmediateShift(state: u16, char: u8) ?i16 {
    for (x_excludes) |x| {
        if (x.state == state and x.char == char) return @intCast(x.shift);
    }
    return null;
}
const start_states = [_]struct { sym: u16, state: u16 }{
    .{ .sym = 3, .state = 0 },
    .{ .sym = 4, .state = 1 },
};

fn getStartState(start_sym: u16) u16 {
    for (start_states) |entry| {
        if (entry.sym == start_sym) return entry.state;
    }
    return 0;
}

const accept_rules = [_]u16{ 81, 82 };

fn isAcceptRule(rule_id: u16) bool {
    for (accept_rules) |ar| if (rule_id == ar) return true;
    return false;
}
