//! Parser (Auto-generated)
//!
//! Generated by grammar.zig from a .grammar file.
//! Contains both lexer and parser.

const std = @import("std");
const MAX_ARGS: usize = 32;
const rip = @import("rip.zig");

// SIMD helpers (fallback if simd.zig not available)
const simd = struct {
    fn findByte(haystack: []const u8, needle: u8) usize {
        for (haystack, 0..) |c, i| if (c == needle) return i;
        return haystack.len;
    }
};

// =============================================================================
// TOKEN CATEGORIES
// =============================================================================

pub const TokenCat = enum(u8) {
    @"ident",
    @"integer",
    @"real",
    @"string_sq",
    @"string_dq",
    @"true",
    @"false",
    @"plus",
    @"minus",
    @"star",
    @"slash",
    @"percent",
    @"power",
    @"eq",
    @"ne",
    @"lt",
    @"gt",
    @"le",
    @"ge",
    @"and_sym",
    @"or_sym",
    @"not_sym",
    @"question",
    @"nullish",
    @"bar",
    @"at",
    @"assign",
    @"const_assign",
    @"plus_assign",
    @"minus_assign",
    @"star_assign",
    @"slash_assign",
    @"lparen",
    @"rparen",
    @"lbrace",
    @"rbrace",
    @"lbracket",
    @"rbracket",
    @"comma",
    @"colon",
    @"arrow",
    @"fat_arrow",
    @"dot",
    @"dotdot",
    @"pipe",
    @"indent",
    @"outdent",
    @"newline",
    @"comment",
    @"eof",
    @"err",

    // Internal (used by generator)
    @"skip",
};

// =============================================================================
// TOKEN STRUCT (8 bytes)
// =============================================================================

pub const Token = struct {
    pos: u32,         // Byte position in source (4 bytes)
    len: u16,         // Token length in bytes (2 bytes)
    cat: TokenCat,    // Token category (1 byte)
    pre: u8,          // Preceding whitespace OR dot-level for indent (1 byte)

    comptime {
        std.debug.assert(@sizeOf(Token) == 8);
    }
};

// =============================================================================
// LEXER
// =============================================================================
pub const BaseLexer = struct {
    const Self = @This();

    source: []const u8,
    pos: u32,
    // State variables
    beg: i32,
    paren: i32,
    brace: i32,

    pub fn init(source: []const u8) Self {
        return .{
            .source = source,
            .pos = 0,
            .beg = 1,
            .paren = 0,
            .brace = 0,
        };
    }

    /// Get the text slice for a token (zero-copy into source)
    pub fn text(self: *const Self, tok: Token) []const u8 {
        const start: usize = tok.pos;
        const end: usize = @min(start + tok.len, self.source.len);
        if (start >= self.source.len) return "";
        return self.source[start..end];
    }

    /// Reset lexer to beginning
    pub fn reset(self: *Self) void {
        self.pos = 0;
        self.beg = 1;
        self.paren = 0;
        self.brace = 0;
    }

    /// Peek at current character (0 if at end)
    inline fn peek(self: *const Self) u8 {
        return if (self.pos < self.source.len) self.source[self.pos] else 0;
    }

    /// Peek at character at offset (0 if at end)
    inline fn peekAt(self: *const Self, offset: u32) u8 {
        const p = self.pos + offset;
        return if (p < self.source.len) self.source[p] else 0;
    }

    /// Get next token
    pub fn next(self: *Self) Token {
        return self.matchRules();
    }

    // Character classification flags (generated from grammar patterns)
    const DIGIT: u8 = 1 << 0;
    const LETTER: u8 = 1 << 1;
    const WHITESPACE: u8 = 1 << 2;

    const char_flags: [256]u8 = blk: {
        var table: [256]u8 = [_]u8{0} ** 256;
        for ('0'..'9' + 1) |c| table[c] = DIGIT;
        for ('A'..'Z' + 1) |c| table[c] = LETTER;
        for ('a'..'z' + 1) |c| table[c] = LETTER;
        table['_'] = LETTER;
        table[' '] = WHITESPACE;
        table['\t'] = WHITESPACE;
        break :blk table;
    };

    inline fn isDigit(c: u8) bool {
        return (char_flags[c] & DIGIT) != 0;
    }

    inline fn isLetter(c: u8) bool {
        return (char_flags[c] & LETTER) != 0;
    }

    inline fn isWhitespace(c: u8) bool {
        return (char_flags[c] & WHITESPACE) != 0;
    }

    inline fn isIdentChar(c: u8) bool {
        return isLetter(c) or isDigit(c);
    }
    /// Match lexer rules
    pub fn matchRules(self: *Self) Token {
        // Count whitespace first
        const ws_start = self.pos;
        while (self.pos < self.source.len and isWhitespace(self.source[self.pos])) {
            self.pos += 1;
        }
        const ws_count: u8 = @intCast(@min(self.pos - ws_start, 255));
        // EOF check
        if (self.pos >= self.source.len) {            return Token{ .cat = .@"eof", .pre = ws_count, .pos = self.pos, .len = 0 };
        }

        const start = self.pos;
        const c = self.source[self.pos];
        // Newline handling (generated from grammar rules)
        if (c == '\n' or c == '\r') {
            if (c == '\r' and self.pos + 1 < self.source.len and self.source[self.pos + 1] == '\n') {
                self.pos += 2;
                self.beg = 1;
                return Token{ .cat = .@"newline", .pre = ws_count, .pos = start, .len = 2 };
            }
                self.pos += 1;
                self.beg = 1;
                return Token{ .cat = .@"newline", .pre = ws_count, .pos = start, .len = 1 };
        }
        // From here, clear line-start flag
        self.beg = 0;
        if (c == '"') {            self.pos += 1;
            while (self.pos < self.source.len) {
                const ch = self.source[self.pos];
                if (ch == '"') {
                    self.pos += 1;
                    return Token{ .cat = .@"string_dq", .pre = ws_count, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (ch == '\\') { self.pos += 2; continue; }
                if (ch == '\n') break;
                self.pos += 1;
            }
            return Token{ .cat = .@"err", .pre = ws_count, .pos = start, .len = @intCast(self.pos - start) };
        }
        if (c == '\'') {            self.pos += 1;
            while (self.pos < self.source.len) {
                const ch = self.source[self.pos];
                if (ch == '\'') {
                    self.pos += 1;
                    if (self.pos < self.source.len and self.source[self.pos] == '\'') { self.pos += 1; continue; }
                    return Token{ .cat = .@"string_sq", .pre = ws_count, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (ch == '\n') break;
                self.pos += 1;
            }
            return Token{ .cat = .@"err", .pre = ws_count, .pos = start, .len = @intCast(self.pos - start) };
        }
        // Number (digit or leading dot followed by digit)
        if (isDigit(c) or (c == '.' and self.pos + 1 < self.source.len and isDigit(self.source[self.pos + 1]))) {
            return self.scanNumber(start, ws_count);
        }
        // Identifier
        if (isLetter(c)) {
            return self.scanIdent(start, ws_count);
        }
        // Comment (scan to end of line)
        if (c == '#') {
            while (self.pos < self.source.len and self.source[self.pos] != '\n') {
                self.pos += 1;
            }
            return Token{ .cat = .@"comment", .pre = ws_count, .pos = start, .len = @intCast(self.pos - start) };
        }
        // Single/multi-char operators
        self.pos += 1;
        return switch (c) {
            '!' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"ne", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"not_sym", .pre = ws_count, .pos = start, .len = 1 };
            },
            '%' => Token{ .cat = .@"percent", .pre = ws_count, .pos = start, .len = 1 },
            '&' => blk: {
                if (self.peek() == '&') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"and_sym", .pre = ws_count, .pos = start, .len = 2 };
                }
                self.pos -= 1;
                break :blk Token{ .cat = .@"err", .pre = ws_count, .pos = start, .len = 1 };
            },
            '(' => blk: {
                self.paren += 1;
                    break :blk Token{ .cat = .@"lparen", .pre = ws_count, .pos = start, .len = 1 };
            },
            ')' => blk: {
                self.paren -= 1;
                    break :blk Token{ .cat = .@"rparen", .pre = ws_count, .pos = start, .len = 1 };
            },
            '*' => blk: {
                if (self.peek() == '*') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"power", .pre = ws_count, .pos = start, .len = 2 };
                }
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"star_assign", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"star", .pre = ws_count, .pos = start, .len = 1 };
            },
            '+' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"plus_assign", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"plus", .pre = ws_count, .pos = start, .len = 1 };
            },
            ',' => Token{ .cat = .@"comma", .pre = ws_count, .pos = start, .len = 1 },
            '-' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"minus_assign", .pre = ws_count, .pos = start, .len = 2 };
                }
                if (self.peek() == '>') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"arrow", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"minus", .pre = ws_count, .pos = start, .len = 1 };
            },
            '.' => blk: {
                if (self.peek() == '.') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"dotdot", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"dot", .pre = ws_count, .pos = start, .len = 1 };
            },
            '/' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"slash_assign", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"slash", .pre = ws_count, .pos = start, .len = 1 };
            },
            ':' => Token{ .cat = .@"colon", .pre = ws_count, .pos = start, .len = 1 },
            '<' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"le", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"lt", .pre = ws_count, .pos = start, .len = 1 };
            },
            '=' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"eq", .pre = ws_count, .pos = start, .len = 2 };
                }
                if (self.peek() == '!') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"const_assign", .pre = ws_count, .pos = start, .len = 2 };
                }
                if (self.peek() == '>') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"fat_arrow", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"assign", .pre = ws_count, .pos = start, .len = 1 };
            },
            '>' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"ge", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"gt", .pre = ws_count, .pos = start, .len = 1 };
            },
            '?' => blk: {
                if (self.peek() == '?') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"nullish", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"question", .pre = ws_count, .pos = start, .len = 1 };
            },
            '@' => Token{ .cat = .@"at", .pre = ws_count, .pos = start, .len = 1 },
            '[' => Token{ .cat = .@"lbracket", .pre = ws_count, .pos = start, .len = 1 },
            '\\' => blk: {
                if (self.peek() == '\n') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"skip", .pre = ws_count, .pos = start, .len = 2 };
                }
                self.pos -= 1;
                break :blk Token{ .cat = .@"err", .pre = ws_count, .pos = start, .len = 1 };
            },
            ']' => Token{ .cat = .@"rbracket", .pre = ws_count, .pos = start, .len = 1 },
            '{' => blk: {
                self.brace += 1;
                    break :blk Token{ .cat = .@"lbrace", .pre = ws_count, .pos = start, .len = 1 };
            },
            '|' => blk: {
                if (self.peek() == '|') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"or_sym", .pre = ws_count, .pos = start, .len = 2 };
                }
                if (self.peek() == '>') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"pipe", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"bar", .pre = ws_count, .pos = start, .len = 1 };
            },
            '}' => blk: {
                self.brace -= 1;
                    break :blk Token{ .cat = .@"rbrace", .pre = ws_count, .pos = start, .len = 1 };
            },
            else => Token{ .cat = .@"err", .pre = ws_count, .pos = start, .len = 1 },
        };
    }

    /// Scan number (generated from grammar)
    fn scanNumber(self: *Self, start: u32, ws: u8) Token {        var has_decimal = false;        const starts_with_dot = self.source[self.pos] == '.';
        // Integer part
        if (isDigit(self.source[self.pos])) {
            while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                self.pos += 1;
            }
        }
        // Decimal part
        if (self.pos < self.source.len and self.source[self.pos] == '.') {
            const next_c = if (self.pos + 1 < self.source.len) self.source[self.pos + 1] else 0;
            if (isDigit(next_c)) {
                has_decimal = true;
                self.pos += 1;
                while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                    self.pos += 1;
                }
            }
        }
        // Classify
        const token_cat: TokenCat = if (has_decimal or starts_with_dot)
            .@"real"
        else
            .@"integer";

        return Token{ .cat = token_cat, .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }

    /// Scan identifier (generated from grammar)
    fn scanIdent(self: *Self, start: u32, ws: u8) Token {
        while (self.pos < self.source.len and isIdentChar(self.source[self.pos])) {
            self.pos += 1;
        }
        return Token{ .cat = .@"ident", .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }
};

pub const Lexer = if (@hasDecl(rip, "Lexer")) rip.Lexer else BaseLexer;

// =============================================================================
// Tag Enum (re-exported from language module)
// =============================================================================
pub const Tag = rip.Tag;

// =============================================================================
// S-Expression (AST Node) - 5 Clean Variants
// =============================================================================

pub const Sexp = union(enum) {
    nil:  void,                                        // Empty (nothing)
    tag:  Tag,                                         // Semantic type (1 byte)
    src:  struct { pos: u32, len: u16, id: u16 },      // Source ref + identity (8 bytes)
    str:  []const u8,                                  // Embedded string (16 bytes)
    list: []const Sexp,                                // Compound: (tag child1 ...)

    /// Get token text from source
    pub fn getText(self: Sexp, source: []const u8) []const u8 {
        return switch (self) {
            .src => |s| source[s.pos..][0..s.len],
            .str => |s| s,
            else => "",
        };
    }

    /// Format for debug output
    pub fn write(self: Sexp, source: []const u8, w: anytype) !void {
        switch (self) {
            .nil => try w.writeAll("_"),
            .tag => |t| try w.print("{s}", .{@tagName(t)}),
            .src => |s| try w.print("{s}", .{source[s.pos..][0..s.len]}),
            .str => |s| try w.print("\"{s}\"", .{s}),
            .list => |items| {
                try w.writeAll("(");
                for (items, 0..) |item, i| {
                    if (i > 0) try w.writeAll(" ");
                    try item.write(source, w);
                }
                try w.writeAll(")");
            },
        }
    }
};

// =============================================================================
// Parser
// =============================================================================

pub const Parser = struct {
    arena: std.heap.ArenaAllocator,
    lexer: Lexer,
    source: []const u8,
    current: Token,
    injected_token: ?u16 = null,
    last_matched_id: u16 = 0,

    state_stack: std.ArrayListUnmanaged(u16) = .{},
    value_stack: std.ArrayListUnmanaged(Sexp) = .{},

    pub fn init(backing_allocator: std.mem.Allocator, source: []const u8) Parser {
        var p = Parser{
            .arena = std.heap.ArenaAllocator.init(backing_allocator),
            .lexer = Lexer.init(source),
            .source = source,
            .current = undefined,
        };
        p.current = p.lexer.next();
        return p;
    }

    pub fn deinit(self: *Parser) void {
        self.arena.deinit();
    }

    fn allocator(self: *Parser) std.mem.Allocator {
        return self.arena.allocator();
    }

    pub fn printError(self: *Parser) void {
        const pos: usize = @min(self.current.pos, self.source.len);
        var line: usize = 1;
        var col: usize = 1;
        var i: usize = 0;
        while (i < pos) : (i += 1) {
            if (self.source[i] == '\n') {
                line += 1;
                col = 1;
            } else {
                col += 1;
            }
        }
        std.debug.print("Parse error at line {d}, column {d}: unexpected {s}\n", .{
            line,
            col,
            @tagName(self.current.cat),
        });
    }

    fn doParse(self: *Parser, start_sym: u16) !Sexp {
        const start_state = getStartState(start_sym);
        self.state_stack.clearRetainingCapacity();
        self.value_stack.clearRetainingCapacity();
        try self.state_stack.append(self.allocator(), start_state);

        while (true) {
            const state = self.state_stack.getLast();
            const sym = if (self.injected_token) |inj| inj else self.tokenToSymbol(self.current);
            var action = getAction(state, sym);

            // X "c" check: if reducing and next char matches with pre==0, shift instead
            if (action < -1 and self.current.pre == 0 and self.current.pos < self.source.len) {
                if (getImmediateShift(state, self.source[self.current.pos])) |shift_target| {
                    action = shift_target;
                }
            }

            if (action == 0) {
                return error.ParseError;
            } else if (action == -1) {
                return self.value_stack.getLast();
            } else if (action > 0) {
                // Shift
                if (self.injected_token != null) {
                    try self.value_stack.append(self.allocator(), .nil);
                    self.injected_token = null;
                } else {
                    try self.value_stack.append(self.allocator(), .{ .src = .{
                        .pos = self.current.pos,
                        .len = self.current.len,
                        .id  = self.last_matched_id,
                    } });
                    self.last_matched_id = 0;
                    self.current = self.lexer.next();
                }
                try self.state_stack.append(self.allocator(), @intCast(action));
            } else {
                // Reduce
                const rule_id: u16 = @intCast(-action - 2);
                var pass: [MAX_ARGS]Sexp = undefined;
                const len = rule_len[rule_id];
                for (0..len) |i| {
                    pass[len - 1 - i] = self.value_stack.pop().?;
                    _ = self.state_stack.pop();
                }

                const result = self.executeAction(rule_id, pass[0..len]);

                if (isAcceptRule(rule_id)) return result;

                try self.value_stack.append(self.allocator(), result);

                const goto_state = self.state_stack.getLast();
                const next = getAction(goto_state, rule_lhs[rule_id]);
                if (next <= 0) return error.ParseError;
                try self.state_stack.append(self.allocator(), @intCast(next));
            }
        }
    }

    /// Spread list helper: [head, ...tail]
    fn spreadList(self: *Parser, head: Sexp, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .{};
        out.append(self.allocator(), head) catch return .nil;
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Spread only: [...tail]
    fn spreadOnly(self: *Parser, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .{};
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Default list handler
    fn list(self: *Parser, pass: []Sexp) Sexp {
        if (pass.len == 0) return .nil;
        if (pass.len == 1) return pass[0];
        var out: std.ArrayListUnmanaged(Sexp) = .{};
        for (pass) |v| out.append(self.allocator(), v) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Build S-expression: (tag items...) with trailing nil trimming
    inline fn sexp(self: *Parser, comptime tag: Tag, items: []const Sexp) Sexp {
        if (items.len == 0) {
            const result = self.allocator().alloc(Sexp, 1) catch return .nil;
            result[0] = .{ .tag = tag };
            return .{ .list = result };
        }
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag ...spread) - tag + spread items
    inline fn sexpSpread(self: *Parser, comptime tag: Tag, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag pos ...spread) - tag + position + spread items
    inline fn sexpPosSpread(self: *Parser, comptime tag: Tag, pos: Sexp, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const skip_pos = (pos == .nil and len == 0);
        const total = if (skip_pos) 1 else len + 2;
        const result = self.allocator().alloc(Sexp, total) catch return .nil;
        result[0] = .{ .tag = tag };
        if (!skip_pos) {
            result[1] = pos;
            if (len > 0) @memcpy(result[2..][0..len], items[0..len]);
        }
        return .{ .list = result };
    }

    fn executeAction(self: *Parser, rule_id: u16, pass: []Sexp) Sexp {
        return switch (rule_id) {
            0 => self.sexpSpread(.@"module", pass[1]),
            1 => pass[1],
            2 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            3 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            4 => pass[0],
            5 => self.list(pass),
            6 => self.list(pass),
            7 => self.list(pass),
            8 => self.list(pass),
            9 => self.list(pass),
            10 => self.list(pass),
            11 => self.list(pass),
            12 => self.list(pass),
            13 => self.list(pass),
            14 => self.list(pass),
            15 => self.sexp(.@"pub", &.{pass[1]}),
            16 => self.sexp(.@"pub", &.{pass[1]}),
            17 => self.sexp(.@"pub", &.{pass[1]}),
            18 => self.sexp(.@"pub", &.{pass[1]}),
            19 => self.sexpSpread(.@"block", pass[1]),
            20 => self.sexp(.@"block", &.{}),
            21 => self.sexp(.@"fun", &.{pass[1], pass[2], pass[3], pass[4]}),
            22 => self.sexp(.@"fun", &.{pass[1], pass[2], .nil, pass[3]}),
            23 => self.sexp(.@"fun", &.{pass[1], .nil, pass[2], pass[3]}),
            24 => self.sexp(.@"fun", &.{pass[1], .nil, .nil, pass[2]}),
            25 => self.sexp(.@"sub", &.{pass[1], pass[2], .nil, pass[3]}),
            26 => self.sexp(.@"sub", &.{pass[1], .nil, .nil, pass[2]}),
            27 => self.sexp(.@"use", &.{pass[1]}),
            28 => self.sexp(.@"alias", &.{pass[1], pass[3]}),
            29 => self.sexp(.@"test", &.{pass[1], pass[2]}),
            30 => self.sexpPosSpread(.@"enum", pass[1], pass[3]),
            31 => self.sexpPosSpread(.@"error_set", pass[1], pass[3]),
            32 => self.sexpPosSpread(.@"struct", pass[1], pass[3]),
            33 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            34 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            35 => pass[0],
            36 => self.list(pass),
            37 => self.list(pass),
            38 => self.list(pass),
            39 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            40 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            41 => pass[0],
            42 => pass[0],
            43 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@":" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            44 => pass[1],
            45 => self.list(pass),
            46 => self.sexp(.@"error_union", &.{pass[1]}),
            47 => self.sexp(.@"?", &.{pass[1]}),
            48 => self.sexp(.@"ptr", &.{pass[1]}),
            49 => self.sexp(.@"slice", &.{pass[2]}),
            50 => self.spreadList(pass[0], pass[1]),
            51 => self.spreadList(pass[1], pass[2]),
            52 => .{ .list = &[_]Sexp{} },
            53 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            54 => self.list(pass),
            55 => self.list(pass),
            56 => self.list(pass),
            57 => self.list(pass),
            58 => self.list(pass),
            59 => self.list(pass),
            60 => self.list(pass),
            61 => self.list(pass),
            62 => self.list(pass),
            63 => self.list(pass),
            64 => self.list(pass),
            65 => self.list(pass),
            66 => self.list(pass),
            67 => self.list(pass),
            68 => self.list(pass),
            69 => self.sexp(.@"??", &.{pass[0], pass[2]}),
            70 => self.sexp(.@"catch", &.{pass[0], pass[3], pass[4]}),
            71 => self.sexp(.@"catch", &.{pass[0], pass[2]}),
            72 => self.list(pass),
            73 => self.sexp(.@"as", &.{pass[0], pass[2]}),
            74 => self.sexp(.@"as", &.{pass[0], pass[2]}),
            75 => self.sexp(.@"if", &.{pass[1], pass[3], pass[5]}),
            76 => self.sexp(.@"if", &.{pass[1], pass[3]}),
            77 => self.sexp(.@"if", &.{pass[1], pass[2], pass[4]}),
            78 => self.sexp(.@"if", &.{pass[1], pass[2], pass[4]}),
            79 => self.sexp(.@"if", &.{pass[1], pass[2]}),
            80 => self.sexp(.@"while", &.{pass[1], .nil, pass[2]}),
            81 => self.sexp(.@"while", &.{pass[1], pass[3], pass[4]}),
            82 => self.sexp(.@"for", &.{pass[1], .nil, pass[3], pass[4]}),
            83 => self.sexp(.@"for", &.{pass[1], pass[3], pass[5], pass[6]}),
            84 => self.sexpPosSpread(.@"match", pass[1], pass[3]),
            85 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            86 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            87 => pass[0],
            88 => self.sexp(.@"arm", &.{pass[0], pass[2]}),
            89 => self.sexp(.@"arm", &.{pass[0], pass[1]}),
            90 => self.sexp(.@"return", &.{pass[1]}),
            91 => self.sexp(.@"return", &.{}),
            92 => self.sexp(.@"break", &.{}),
            93 => self.sexp(.@"continue", &.{}),
            94 => self.sexp(.@"defer", &.{pass[1]}),
            95 => self.sexp(.@"errdefer", &.{pass[1]}),
            96 => self.sexp(.@"comptime", &.{pass[1]}),
            97 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"=" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            98 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"+=" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            99 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"-=" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            100 => self.sexp(.@"*=", &.{pass[0], pass[2]}),
            101 => self.sexp(.@"/=", &.{pass[0], pass[2]}),
            102 => self.sexp(.@"const", &.{pass[0], pass[2]}),
            103 => self.sexp(.@"not", &.{pass[1]}),
            104 => self.sexp(.@"neg", &.{pass[1]}),
            105 => self.sexp(.@"try", &.{pass[1]}),
            106 => self.list(pass),
            107 => self.sexp(.@"await", &.{pass[0], pass[2]}),
            108 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"." }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            109 => self.sexp(.@"index", &.{pass[0], pass[2]}),
            110 => self.spreadList(pass[0], pass[1]),
            111 => self.spreadList(pass[1], pass[2]),
            112 => .{ .list = &[_]Sexp{} },
            113 => self.sexpPosSpread(.@"call", pass[0], pass[1]),
            114 => self.sexpPosSpread(.@"call", pass[0], pass[2]),
            115 => self.list(pass),
            116 => self.spreadList(pass[0], pass[1]),
            117 => self.spreadList(pass[1], pass[2]),
            118 => .{ .list = &[_]Sexp{} },
            119 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            120 => .{ .list = &[_]Sexp{} },
            121 => self.list(pass),
            122 => self.list(pass),
            123 => self.list(pass),
            124 => self.list(pass),
            125 => self.list(pass),
            126 => self.list(pass),
            127 => self.list(pass),
            128 => self.sexp(.@"unreachable", &.{}),
            129 => self.sexp(.@"undefined", &.{}),
            130 => self.sexpPosSpread(.@"builtin", pass[1], pass[3]),
            131 => self.list(pass),
            132 => self.list(pass),
            133 => self.sexpSpread(.@"array", pass[1]),
            134 => pass[1],
            135 => self.spreadList(pass[0], pass[1]),
            136 => self.spreadList(pass[1], pass[2]),
            137 => .{ .list = &[_]Sexp{} },
            138 => self.sexpPosSpread(.@"literal", pass[0], pass[2]),
            139 => self.sexp(.@"pair", &.{pass[0], pass[2]}),
            140 => self.sexp(.@"lambda", &.{pass[1], .nil, pass[2]}),
            141 => self.sexp(.@"lambda", &.{.nil, .nil, pass[1]}),
            142 => self.list(pass),
            143 => self.list(pass),
            144 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"|>" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            145 => pass[0],
            146 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"||" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            147 => pass[0],
            148 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"&&" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            149 => pass[0],
            150 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"==" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            151 => self.sexp(.@"!=", &.{pass[0], pass[2]}),
            152 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"<" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            153 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@">" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            154 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"<=" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            155 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@">=" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            156 => pass[0],
            157 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@".." }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            158 => pass[0],
            159 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"+" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            160 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"-" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            161 => pass[0],
            162 => self.sexp(.@"*", &.{pass[0], pass[2]}),
            163 => self.sexp(.@"/", &.{pass[0], pass[2]}),
            164 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"%" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            165 => pass[0],
            166 => self.sexp(.@"**", &.{pass[0], pass[2]}),
            167 => pass[0],
            168 => pass[0],
            else => .nil,
        };
    }

    fn tokenToSymbol(self: *Parser, token: Token) u16 {
        return switch (token.cat) {
            .@"eof" => 1,
            .@"ident" => self.identToSymbol(token),
            .@"newline" => 48,
            .@"indent" => 50,
            .@"outdent" => 51,
            .@"string_dq" => 59,
            .@"integer" => 106,
            .@"real" => 107,
            .@"string_sq" => 108,
            .@"true" => 109,
            .@"false" => 110,
            .@"assign" => 57,
            .@"colon" => 63,
            .@"not_sym" => 65,
            .@"question" => 66,
            .@"star" => 67,
            .@"lbracket" => 68,
            .@"rbracket" => 69,
            .@"comma" => 70,
            .@"bar" => 77,
            .@"minus" => 97,
            .@"dot" => 99,
            .@"lparen" => 102,
            .@"rparen" => 103,
            .@"at" => 113,
            .@"lbrace" => 114,
            .@"rbrace" => 117,
            .@"lt" => 136,
            .@"gt" => 137,
            .@"plus" => 141,
            .@"slash" => 142,
            .@"percent" => 143,
            .@"arrow" => 64,
            .@"nullish" => 74,
            .@"fat_arrow" => 85,
            .@"plus_assign" => 92,
            .@"minus_assign" => 93,
            .@"star_assign" => 94,
            .@"slash_assign" => 95,
            .@"const_assign" => 96,
            .@"pipe" => 131,
            .@"or_sym" => 132,
            .@"and_sym" => 133,
            .@"eq" => 134,
            .@"ne" => 135,
            .@"le" => 138,
            .@"ge" => 139,
            .@"dotdot" => 140,
            .@"power" => 144,
            else => 2, // error
        };
    }

    fn identToSymbol(self: *Parser, token: Token) u16 {
        const text = self.source[token.pos..][0..token.len];
        if (text.len == 0) return SYM_IDENT;
        if (self.try_ident_as_keyword(token, text)) |sym| return sym;
        return SYM_IDENT;
    }

    fn try_ident_as_keyword(self: *Parser, token: Token, text: []const u8) ?u16 {
        _ = token;
        const state = self.state_stack.getLast();
        if (rip.keyword_as(text)) |id| {
            const id_idx = @intFromEnum(id);
            const sym = keyword_to_symbol[id_idx];
            if (sym != 0 and getAction(state, sym) != 0) {
                self.last_matched_id = @intCast(id_idx);
                return sym;
            }
            const fallback = keyword_fallback_symbol;
            if (fallback != 0 and getAction(state, fallback) != 0) {
                self.last_matched_id = @intCast(id_idx);
                return fallback;
            }
        }
        return null;
    }

    pub fn parseProgram(self: *Parser) !Sexp {
        self.injected_token = SYM_program_START;
        return self.doParse(SYM_program);
    }
    pub fn parseExpr(self: *Parser) !Sexp {
        self.injected_token = SYM_expr_START;
        return self.doParse(SYM_expr);
    }
};

// Symbol IDs
const SYM_program: u16 = 3;
const SYM_program_START: u16 = 119;
const SYM_expr: u16 = 4;
const SYM_expr_START: u16 = 121;
const SYM_IDENT: u16 = 53;

// Mapping from rip.keyword_id to grammar symbol IDs (computed at comptime)
const keyword_to_symbol = blk: {
    var arr: [512]u16 = .{0} ** 512;
    if (@hasField(rip.keyword_id, "NEWLINE")) arr[@intFromEnum(rip.keyword_id.NEWLINE)] = 48;
    if (@hasField(rip.keyword_id, "PUB")) arr[@intFromEnum(rip.keyword_id.PUB)] = 49;
    if (@hasField(rip.keyword_id, "INDENT")) arr[@intFromEnum(rip.keyword_id.INDENT)] = 50;
    if (@hasField(rip.keyword_id, "OUTDENT")) arr[@intFromEnum(rip.keyword_id.OUTDENT)] = 51;
    if (@hasField(rip.keyword_id, "FUN")) arr[@intFromEnum(rip.keyword_id.FUN)] = 52;
    if (@hasField(rip.keyword_id, "IDENT")) arr[@intFromEnum(rip.keyword_id.IDENT)] = 53;
    if (@hasField(rip.keyword_id, "SUB")) arr[@intFromEnum(rip.keyword_id.SUB)] = 54;
    if (@hasField(rip.keyword_id, "USE")) arr[@intFromEnum(rip.keyword_id.USE)] = 55;
    if (@hasField(rip.keyword_id, "ALIAS")) arr[@intFromEnum(rip.keyword_id.ALIAS)] = 56;
    if (@hasField(rip.keyword_id, "TEST")) arr[@intFromEnum(rip.keyword_id.TEST)] = 58;
    if (@hasField(rip.keyword_id, "STRING_DQ")) arr[@intFromEnum(rip.keyword_id.STRING_DQ)] = 59;
    if (@hasField(rip.keyword_id, "ENUM")) arr[@intFromEnum(rip.keyword_id.ENUM)] = 60;
    if (@hasField(rip.keyword_id, "ERROR")) arr[@intFromEnum(rip.keyword_id.ERROR)] = 61;
    if (@hasField(rip.keyword_id, "STRUCT")) arr[@intFromEnum(rip.keyword_id.STRUCT)] = 62;
    if (@hasField(rip.keyword_id, "CATCH")) arr[@intFromEnum(rip.keyword_id.CATCH)] = 75;
    if (@hasField(rip.keyword_id, "AS")) arr[@intFromEnum(rip.keyword_id.AS)] = 76;
    if (@hasField(rip.keyword_id, "IF")) arr[@intFromEnum(rip.keyword_id.IF)] = 78;
    if (@hasField(rip.keyword_id, "THEN")) arr[@intFromEnum(rip.keyword_id.THEN)] = 79;
    if (@hasField(rip.keyword_id, "ELSE")) arr[@intFromEnum(rip.keyword_id.ELSE)] = 80;
    if (@hasField(rip.keyword_id, "WHILE")) arr[@intFromEnum(rip.keyword_id.WHILE)] = 81;
    if (@hasField(rip.keyword_id, "FOR")) arr[@intFromEnum(rip.keyword_id.FOR)] = 82;
    if (@hasField(rip.keyword_id, "IN")) arr[@intFromEnum(rip.keyword_id.IN)] = 83;
    if (@hasField(rip.keyword_id, "MATCH")) arr[@intFromEnum(rip.keyword_id.MATCH)] = 84;
    if (@hasField(rip.keyword_id, "RETURN")) arr[@intFromEnum(rip.keyword_id.RETURN)] = 86;
    if (@hasField(rip.keyword_id, "BREAK")) arr[@intFromEnum(rip.keyword_id.BREAK)] = 87;
    if (@hasField(rip.keyword_id, "CONTINUE")) arr[@intFromEnum(rip.keyword_id.CONTINUE)] = 88;
    if (@hasField(rip.keyword_id, "DEFER")) arr[@intFromEnum(rip.keyword_id.DEFER)] = 89;
    if (@hasField(rip.keyword_id, "ERRDEFER")) arr[@intFromEnum(rip.keyword_id.ERRDEFER)] = 90;
    if (@hasField(rip.keyword_id, "COMPTIME")) arr[@intFromEnum(rip.keyword_id.COMPTIME)] = 91;
    if (@hasField(rip.keyword_id, "TRY")) arr[@intFromEnum(rip.keyword_id.TRY)] = 98;
    if (@hasField(rip.keyword_id, "INTEGER")) arr[@intFromEnum(rip.keyword_id.INTEGER)] = 106;
    if (@hasField(rip.keyword_id, "REAL")) arr[@intFromEnum(rip.keyword_id.REAL)] = 107;
    if (@hasField(rip.keyword_id, "STRING_SQ")) arr[@intFromEnum(rip.keyword_id.STRING_SQ)] = 108;
    if (@hasField(rip.keyword_id, "TRUE")) arr[@intFromEnum(rip.keyword_id.TRUE)] = 109;
    if (@hasField(rip.keyword_id, "FALSE")) arr[@intFromEnum(rip.keyword_id.FALSE)] = 110;
    if (@hasField(rip.keyword_id, "UNREACHABLE")) arr[@intFromEnum(rip.keyword_id.UNREACHABLE)] = 111;
    if (@hasField(rip.keyword_id, "UNDEFINED")) arr[@intFromEnum(rip.keyword_id.UNDEFINED)] = 112;
    if (@hasField(rip.keyword_id, "FN")) arr[@intFromEnum(rip.keyword_id.FN)] = 118;
    break :blk arr;
};
const keyword_fallback_symbol: u16 = 0;

const rule_lhs = [_]u16{ 3, 4, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 9, 9, 9, 9, 10, 10, 11, 12, 13, 14, 15, 16, 17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 21, 22, 22, 22, 22, 22, 71, 72, 72, 23, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 24, 25, 25, 26, 26, 26, 27, 27, 27, 27, 27, 28, 28, 29, 29, 30, 31, 31, 31, 32, 32, 33, 33, 34, 35, 36, 37, 38, 39, 39, 39, 39, 39, 40, 41, 41, 41, 41, 42, 42, 42, 100, 101, 101, 42, 42, 42, 104, 105, 105, 43, 43, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 115, 116, 116, 45, 46, 47, 47, 120, 122, 123, 123, 124, 124, 125, 125, 126, 126, 126, 126, 126, 126, 126, 127, 127, 128, 128, 128, 129, 129, 129, 129, 130, 130, 73 };
const rule_len = [_]u8{ 2, 2, 1, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 2, 5, 4, 4, 3, 4, 3, 2, 4, 3, 5, 5, 5, 1, 3, 2, 1, 1, 1, 1, 3, 2, 1, 3, 2, 1, 2, 2, 2, 3, 2, 3, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 5, 3, 1, 3, 4, 6, 4, 5, 5, 3, 3, 5, 5, 7, 5, 1, 3, 2, 3, 2, 2, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 2, 2, 1, 3, 3, 4, 2, 3, 0, 2, 4, 1, 2, 3, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 3, 3, 2, 3, 0, 4, 3, 3, 2, 2, 2, 3, 1, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 1, 3, 3, 1, 3, 3, 3, 1, 3, 1, 1 };

// Parse Table: 298 states × 145 symbols
const NUM_STATES = 298;
const NUM_SYMBOLS = 145;

const sparse = [NUM_STATES][]const i16{
    &.{3,2,119,3},
    &.{4,57,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-1},
    &.{4,81,5,77,6,75,7,71,9,61,10,67,11,64,12,72,13,62,14,74,15,73,16,68,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,49,65,52,80,53,18,54,66,55,78,56,63,58,69,59,49,60,70,61,76,62,79,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-59,48,-59,50,-59,51,-59,63,-59,69,-59,70,-59,76,-59,77,-59,79,-59,80,-59,103,-59,117,-59},
    &.{1,-125,48,-125,50,-125,51,-125,53,-125,57,-125,59,-125,63,-125,65,-125,67,-125,68,-125,69,-125,70,-125,74,-125,75,-125,76,-125,77,-125,79,-125,80,-125,85,-125,92,-125,93,-125,94,-125,95,-125,96,-125,97,-125,99,-125,102,-125,103,-125,106,-125,107,-125,108,-125,109,-125,110,-125,111,-125,112,-125,113,-125,117,-125,118,-125,131,-125,132,-125,133,-125,134,-125,135,-125,136,-125,137,-125,138,-125,139,-125,140,-125,141,-125,142,-125,143,-125,144,-125},
    &.{1,-131,48,-131,50,-131,51,-131,53,-131,57,-131,59,-131,63,-131,65,-131,67,-131,68,-131,69,-131,70,-131,74,-131,75,-131,76,-131,77,-131,79,-131,80,-131,85,-131,92,-131,93,-131,94,-131,95,-131,96,-131,97,-131,99,-131,102,-131,103,-131,106,-131,107,-131,108,-131,109,-131,110,-131,111,-131,112,-131,113,-131,117,-131,118,-131,131,-131,132,-131,133,-131,134,-131,135,-131,136,-131,137,-131,138,-131,139,-131,140,-131,141,-131,142,-131,143,-131,144,-131},
    &.{1,-169,48,-169,50,-169,51,-169,63,-169,67,-169,69,-169,70,-169,74,-169,75,-169,76,-169,77,-169,79,-169,80,-169,97,-169,103,-169,117,-169,131,-169,132,-169,133,-169,134,-169,135,-169,136,-169,137,-169,138,-169,139,-169,140,-169,141,-169,142,-169,143,-169,144,82},
    &.{1,-149,48,-149,50,-149,51,-149,63,-149,69,-149,70,-149,74,-149,75,-149,76,-149,77,-149,79,-149,80,-149,103,-149,117,-149,131,-149,132,-149,133,83},
    &.{1,-129,48,-129,50,-129,51,-129,53,-129,57,-129,59,-129,63,-129,65,-129,67,-129,68,-129,69,-129,70,-129,74,-129,75,-129,76,-129,77,-129,79,-129,80,-129,85,-129,92,-129,93,-129,94,-129,95,-129,96,-129,97,-129,99,-129,102,-129,103,-129,106,-129,107,-129,108,-129,109,-129,110,-129,111,-129,112,-129,113,-129,117,-129,118,-129,131,-129,132,-129,133,-129,134,-129,135,-129,136,-129,137,-129,138,-129,139,-129,140,-129,141,-129,142,-129,143,-129,144,-129},
    &.{4,84,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-124,48,-124,50,-124,51,-124,53,-124,57,-124,59,-124,63,-124,65,-124,67,-124,68,-124,69,-124,70,-124,74,-124,75,-124,76,-124,77,-124,79,-124,80,-124,85,-124,92,-124,93,-124,94,-124,95,-124,96,-124,97,-124,99,-124,102,-124,103,-124,106,-124,107,-124,108,-124,109,-124,110,-124,111,-124,112,-124,113,-124,117,-124,118,-124,131,-124,132,-124,133,-124,134,-124,135,-124,136,-124,137,-124,138,-124,139,-124,140,-124,141,-124,142,-124,143,-124,144,-124},
    &.{4,87,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,43,85,44,58,45,24,47,29,53,18,59,49,65,35,68,12,69,-122,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,103,-122,104,86,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-93,4,88,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,48,-93,50,-93,51,-93,53,18,59,49,63,-93,65,35,68,12,69,-93,70,-93,73,43,76,-93,77,-93,78,39,79,-93,80,-93,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,103,-93,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,117,-93,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-94,48,-94,50,-94,51,-94,63,-94,69,-94,70,-94,76,-94,77,-94,79,-94,80,-94,103,-94,117,-94},
    &.{1,-65,48,-65,50,-65,51,-65,63,-65,69,-65,70,-65,76,-65,77,-65,79,-65,80,-65,103,-65,117,-65},
    &.{1,-56,48,-56,50,-56,51,-56,63,-56,69,-56,70,-56,76,-56,77,-56,79,-56,80,-56,103,-56,117,-56},
    &.{1,-69,48,-69,50,-69,51,-69,63,-69,69,-69,70,-69,76,-69,77,-69,79,-69,80,-69,103,-69,117,-69},
    &.{1,-123,48,-123,50,-123,51,-123,53,-123,57,-123,59,-123,63,-123,65,-123,67,-123,68,-123,69,-123,70,-123,74,-123,75,-123,76,-123,77,-123,79,-123,80,-123,85,-123,92,-123,93,-123,94,-123,95,-123,96,-123,97,-123,99,-123,102,-123,103,-123,106,-123,107,-123,108,-123,109,-123,110,-123,111,-123,112,-123,113,-123,114,89,117,-123,118,-123,131,-123,132,-123,133,-123,134,-123,135,-123,136,-123,137,-123,138,-123,139,-123,140,-123,141,-123,142,-123,143,-123,144,-123},
    &.{1,-163,48,-163,50,-163,51,-163,63,-163,67,90,69,-163,70,-163,74,-163,75,-163,76,-163,77,-163,79,-163,80,-163,97,-163,103,-163,117,-163,131,-163,132,-163,133,-163,134,-163,135,-163,136,-163,137,-163,138,-163,139,-163,140,-163,141,-163,142,92,143,91},
    &.{4,94,24,54,25,17,26,93,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-130,48,-130,50,-130,51,-130,53,-130,57,-130,59,-130,63,-130,65,-130,67,-130,68,-130,69,-130,70,-130,74,-130,75,-130,76,-130,77,-130,79,-130,80,-130,85,-130,92,-130,93,-130,94,-130,95,-130,96,-130,97,-130,99,-130,102,-130,103,-130,106,-130,107,-130,108,-130,109,-130,110,-130,111,-130,112,-130,113,-130,117,-130,118,-130,131,-130,132,-130,133,-130,134,-130,135,-130,136,-130,137,-130,138,-130,139,-130,140,-130,141,-130,142,-130,143,-130,144,-130},
    &.{1,-170,48,-170,50,-170,51,-170,63,-170,69,-170,70,-170,74,-170,75,-170,76,-170,77,-170,79,-170,80,-170,103,-170,117,-170,131,95},
    &.{1,-147,48,-147,50,-147,51,-147,63,-147,69,-147,70,-147,74,-147,75,-147,76,-147,77,-147,79,-147,80,-147,103,-147,117,-147,131,-147,132,96},
    &.{1,-133,48,-133,50,-133,51,-133,53,-133,57,-133,59,-133,63,-133,65,-133,67,-133,68,-133,69,-133,70,-133,74,-133,75,-133,76,-133,77,-133,79,-133,80,-133,85,-133,92,-133,93,-133,94,-133,95,-133,96,-133,97,-133,99,-133,102,-133,103,-133,106,-133,107,-133,108,-133,109,-133,110,-133,111,-133,112,-133,113,-133,117,-133,118,-133,131,-133,132,-133,133,-133,134,-133,135,-133,136,-133,137,-133,138,-133,139,-133,140,-133,141,-133,142,-133,143,-133,144,-133},
    &.{1,-67,48,-67,50,-67,51,-67,63,-67,69,-67,70,-67,76,-67,77,-67,79,-67,80,-67,103,-67,117,-67},
    &.{53,97},
    &.{1,-160,48,-160,50,-160,51,-160,63,-160,69,-160,70,-160,74,-160,75,-160,76,-160,77,-160,79,-160,80,-160,97,100,103,-160,117,-160,131,-160,132,-160,133,-160,134,-160,135,-160,136,-160,137,-160,138,-160,139,-160,140,99,141,98},
    &.{8,104,20,103,23,106,50,105,53,102,71,101},
    &.{1,-134,48,-134,50,-134,51,-134,53,-134,57,-134,59,-134,63,-134,65,-134,67,-134,68,-134,69,-134,70,-134,74,-134,75,-134,76,-134,77,-134,79,-134,80,-134,85,-134,92,-134,93,-134,94,-134,95,-134,96,-134,97,-134,99,-134,102,-134,103,-134,106,-134,107,-134,108,-134,109,-134,110,-134,111,-134,112,-134,113,-134,117,-134,118,-134,131,-134,132,-134,133,-134,134,-134,135,-134,136,-134,137,-134,138,-134,139,-134,140,-134,141,-134,142,-134,143,-134,144,-134},
    &.{1,-151,48,-151,50,-151,51,-151,63,-151,69,-151,70,-151,74,-151,75,-151,76,-151,77,-151,79,-151,80,-151,103,-151,117,-151,131,-151,132,-151,133,-151},
    &.{41,107,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28},
    &.{1,-128,48,-128,50,-128,51,-128,53,-128,57,-128,59,-128,63,-128,65,-128,67,-128,68,-128,69,-128,70,-128,74,-128,75,-128,76,-128,77,-128,79,-128,80,-128,85,-128,92,-128,93,-128,94,-128,95,-128,96,-128,97,-128,99,-128,102,-128,103,-128,106,-128,107,-128,108,-128,109,-128,110,-128,111,-128,112,-128,113,-128,117,-128,118,-128,131,-128,132,-128,133,-128,134,-128,135,-128,136,-128,137,-128,138,-128,139,-128,140,-128,141,-128,142,-128,143,-128,144,-128},
    &.{1,-62,48,-62,50,-62,51,-62,63,-62,69,-62,70,-62,76,-62,77,-62,79,-62,80,-62,103,-62,117,-62},
    &.{1,-63,48,-63,50,-63,51,-63,63,-63,69,-63,70,-63,76,-63,77,-63,79,-63,80,-63,103,-63,117,-63},
    &.{41,109,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28},
    &.{4,110,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-158,48,-158,50,-158,51,-158,63,-158,69,-158,70,-158,74,-158,75,-158,76,-158,77,-158,79,-158,80,-158,103,-158,117,-158,131,-158,132,-158,133,-158,134,116,135,112,136,115,137,114,138,113,139,111},
    &.{1,-66,48,-66,50,-66,51,-66,63,-66,69,-66,70,-66,76,-66,77,-66,79,-66,80,-66,103,-66,117,-66},
    &.{4,94,24,54,25,17,26,117,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-95,48,-95,50,-95,51,-95,63,-95,69,-95,70,-95,76,-95,77,-95,79,-95,80,-95,103,-95,117,-95},
    &.{4,118,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-126,48,-126,50,-126,51,-126,53,-126,57,-126,59,-126,63,-126,65,-126,67,-126,68,-126,69,-126,70,-126,74,-126,75,-126,76,-126,77,-126,79,-126,80,-126,85,-126,92,-126,93,-126,94,-126,95,-126,96,-126,97,-126,99,-126,102,-126,103,-126,106,-126,107,-126,108,-126,109,-126,110,-126,111,-126,112,-126,113,-126,117,-126,118,-126,131,-126,132,-126,133,-126,134,-126,135,-126,136,-126,137,-126,138,-126,139,-126,140,-126,141,-126,142,-126,143,-126,144,-126},
    &.{1,-70,48,-70,50,-70,51,-70,63,-70,69,-70,70,-70,74,119,75,120,76,-70,77,-70,79,-70,80,-70,103,-70,117,-70},
    &.{4,121,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-108,44,132,45,24,47,29,48,-108,50,-108,51,-108,53,18,57,123,59,49,63,-108,65,124,67,-108,68,126,69,-108,70,-108,74,-108,75,-108,76,-108,77,-108,79,-108,80,-108,92,133,93,130,94,125,95,129,96,122,97,-108,99,131,100,127,102,128,103,-108,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,117,-108,118,28,131,-108,132,-108,133,-108,134,-108,135,-108,136,-108,137,-108,138,-108,139,-108,140,-108,141,-108,142,-108,143,-108,144,-108},
    &.{1,-57,48,-57,50,-57,51,-57,63,-57,69,-57,70,-57,76,-57,77,-57,79,-57,80,-57,103,-57,117,-57},
    &.{1,-61,48,-61,50,-61,51,-61,63,-61,69,-61,70,-61,76,-61,77,-61,79,-61,80,-61,103,-61,117,-61},
    &.{4,134,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-127,48,-127,50,-127,51,-127,53,-127,57,-127,59,-127,63,-127,65,-127,67,-127,68,-127,69,-127,70,-127,74,-127,75,-127,76,-127,77,-127,79,-127,80,-127,85,-127,92,-127,93,-127,94,-127,95,-127,96,-127,97,-127,99,-127,102,-127,103,-127,106,-127,107,-127,108,-127,109,-127,110,-127,111,-127,112,-127,113,-127,117,-127,118,-127,131,-127,132,-127,133,-127,134,-127,135,-127,136,-127,137,-127,138,-127,139,-127,140,-127,141,-127,142,-127,143,-127,144,-127},
    &.{4,135,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{53,136},
    &.{1,-64,48,-64,50,-64,51,-64,63,-64,69,-64,70,-64,76,-64,77,-64,79,-64,80,-64,103,-64,117,-64},
    &.{1,-58,48,-58,50,-58,51,-58,63,-58,69,-58,70,-58,76,-58,77,-58,79,-58,80,-58,103,-58,117,-58},
    &.{1,-68,48,-68,50,-68,51,-68,63,-68,69,-68,70,-68,76,-68,77,-68,79,-68,80,-68,103,-68,117,-68},
    &.{1,-60,48,-60,50,-60,51,-60,63,-60,69,-60,70,-60,76,-60,77,-60,79,-60,80,-60,103,-60,117,-60},
    &.{41,137,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28},
    &.{1,-1},
    &.{1,-117,48,-117,50,-117,51,-117,53,-117,57,-117,59,-117,63,-117,65,-117,67,-117,68,-117,69,-117,70,-117,74,-117,75,-117,76,-117,77,-117,79,-117,80,-117,92,-117,93,-117,94,-117,95,-117,96,-117,97,-117,99,-117,102,-117,103,-117,106,-117,107,-117,108,-117,109,-117,110,-117,111,-117,112,-117,113,-117,117,-117,118,-117,131,-117,132,-117,133,-117,134,-117,135,-117,136,-117,137,-117,138,-117,139,-117,140,-117,141,-117,142,-117,143,-117,144,-117},
    &.{1,-167,48,-167,50,-167,51,-167,63,-167,67,-167,69,-167,70,-167,74,-167,75,-167,76,-167,77,-167,79,-167,80,-167,97,-167,103,-167,117,-167,131,-167,132,-167,133,-167,134,-167,135,-167,136,-167,137,-167,138,-167,139,-167,140,-167,141,-167,142,-167,143,-167},
    &.{1,-1},
    &.{1,-9,48,-9,51,-9},
    &.{1,-15,48,-15,51,-15},
    &.{53,139},
    &.{1,-7,48,-7,51,-7},
    &.{9,140,10,141,14,143,16,142,52,80,54,66,60,70,62,79},
    &.{53,144},
    &.{1,-10,48,-10,51,-10},
    &.{1,-12,48,-12,51,-12},
    &.{59,145},
    &.{53,146},
    &.{1,-8,48,-8,51,-8},
    &.{1,-14,48,-14,51,-14},
    &.{1,-13,48,-13,51,-13},
    &.{1,-11,48,-11,51,-11},
    &.{1,-4,48,-4,51,-4},
    &.{53,147},
    &.{1,-2,48,148},
    &.{53,149},
    &.{53,150},
    &.{53,151},
    &.{1,-16,48,-16,51,-16},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,130,152},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,126,153,127,37,128,27,129,19,130,59},
    &.{1,-97,48,-97,50,-97,51,-97,63,-97,69,-97,70,-97,76,-97,77,-97,79,-97,80,-97,103,-97,117,-97},
    &.{69,154},
    &.{69,-121,103,-121},
    &.{69,-120,70,156,103,-120,105,155},
    &.{1,-92,48,-92,50,-92,51,-92,63,-92,69,-92,70,-92,76,-92,77,-92,79,-92,80,-92,103,-92,117,-92},
    &.{46,157,53,159,115,158},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,130,160},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,130,161},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,130,162},
    &.{8,163,50,105,63,164},
    &.{50,-74,63,-74,76,165,77,166,79,-74},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,124,167,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,125,168,126,30,127,37,128,27,129,19,130,59},
    &.{70,170,83,169},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,129,171,130,59},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,128,172,129,19,130,59},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,129,173,130,59},
    &.{50,-55,64,-55},
    &.{48,-44,50,-44,51,-44,63,174,64,-44,70,-44},
    &.{50,-54,64,-54,70,176,72,175},
    &.{1,-143,48,-143,50,-143,51,-143,53,-143,57,-143,59,-143,63,-143,65,-143,67,-143,68,-143,69,-143,70,-143,74,-143,75,-143,76,-143,77,-143,79,-143,80,-143,85,-143,92,-143,93,-143,94,-143,95,-143,96,-143,97,-143,99,-143,102,-143,103,-143,106,-143,107,-143,108,-143,109,-143,110,-143,111,-143,112,-143,113,-143,117,-143,118,-143,131,-143,132,-143,133,-143,134,-143,135,-143,136,-143,137,-143,138,-143,139,-143,140,-143,141,-143,142,-143,143,-143,144,-143},
    &.{4,81,5,178,6,75,7,71,9,61,10,67,11,64,12,72,13,62,14,74,15,73,16,68,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,49,65,51,177,52,80,53,18,54,66,55,78,56,63,58,69,59,49,60,70,61,76,62,79,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{8,179,50,105},
    &.{1,-106,48,-106,50,-106,51,-106,63,-106,67,-106,69,-106,70,-106,74,-106,75,-106,76,-106,77,-106,79,-106,80,-106,97,-106,103,-106,117,-106,131,-106,132,-106,133,-106,134,-106,135,-106,136,-106,137,-106,138,-106,139,-106,140,-106,141,-106,142,-106,143,-106,144,-106},
    &.{1,-108,44,132,45,24,47,29,48,-108,50,-108,51,-108,53,18,59,49,63,-108,65,124,67,-108,68,126,69,-108,70,-108,74,-108,75,-108,76,-108,77,-108,79,-108,80,-108,97,-108,99,131,100,127,102,128,103,-108,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,117,-108,118,28,131,-108,132,-108,133,-108,134,-108,135,-108,136,-108,137,-108,138,-108,139,-108,140,-108,141,-108,142,-108,143,-108,144,-108},
    &.{1,-105,48,-105,50,-105,51,-105,63,-105,67,-105,69,-105,70,-105,74,-105,75,-105,76,-105,77,-105,79,-105,80,-105,97,-105,103,-105,117,-105,131,-105,132,-105,133,-105,134,-105,135,-105,136,-105,137,-105,138,-105,139,-105,140,-105,141,-105,142,-105,143,-105,144,-105},
    &.{1,-96,48,-96,50,-96,51,-96,63,-96,69,-96,70,-96,76,-96,77,-96,79,-96,80,-96,103,-96,117,-96},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,127,180,128,27,129,19,130,59},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,127,181,128,27,129,19,130,59},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,127,182,128,27,129,19,130,59},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,127,183,128,27,129,19,130,59},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,127,184,128,27,129,19,130,59},
    &.{41,7,42,108,44,58,45,24,47,29,53,18,59,49,65,35,68,12,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,127,185,128,27,129,19,130,59},
    &.{8,186,50,105,79,187},
    &.{1,-98,48,-98,50,-98,51,-98,63,-98,69,-98,70,-98,76,-98,77,-98,79,-98,80,-98,103,-98,117,-98},
    &.{4,188,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{4,190,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,76,189,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{50,191},
    &.{4,192,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{4,193,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{44,194,45,24,47,29,53,18,59,49,68,12,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28},
    &.{4,195,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{4,196,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,43,85,44,58,45,24,47,29,53,18,59,49,65,35,68,12,69,-122,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,103,-122,104,86,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-115,48,-115,50,-115,51,-115,53,-115,57,-115,59,-115,63,-115,65,-115,67,-115,68,-115,69,-115,70,-115,74,-115,75,-115,76,-115,77,-115,79,-115,80,-115,92,-115,93,-115,94,-115,95,-115,96,-115,97,-115,99,-115,102,-115,103,-115,106,-115,107,-115,108,-115,109,-115,110,-115,111,-115,112,-115,113,-115,117,-115,118,-115,131,-115,132,-115,133,-115,134,-115,135,-115,136,-115,137,-115,138,-115,139,-115,140,-115,141,-115,142,-115,143,-115,144,-115},
    &.{4,198,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,43,197,44,58,45,24,47,29,53,18,59,49,65,35,68,12,69,-122,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,103,-122,104,86,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{4,199,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{4,200,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{53,201},
    &.{1,-114,48,-114,50,-114,51,-114,53,-114,57,-114,59,-114,63,-114,65,-114,67,-114,68,-114,69,-114,70,203,74,-114,75,-114,76,-114,77,-114,79,-114,80,-114,92,-114,93,-114,94,-114,95,-114,96,-114,97,-114,99,-114,101,202,102,-114,103,-114,106,-114,107,-114,108,-114,109,-114,110,-114,111,-114,112,-114,113,-114,117,-114,118,-114,131,-114,132,-114,133,-114,134,-114,135,-114,136,-114,137,-114,138,-114,139,-114,140,-114,141,-114,142,-114,143,-114,144,-114},
    &.{4,204,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-3,48,-3,50,-3,51,-3,63,-3,69,-3,70,-3,76,-3,77,-3,79,-3,80,-3,103,-3,117,-3},
    &.{103,205},
    &.{102,206},
    &.{1,-107,48,-107,50,-107,51,-107,63,-107,67,-107,69,-107,70,-107,74,-107,75,-107,76,-107,77,-107,79,-107,80,-107,97,-107,103,-107,117,-107,131,-107,132,-107,133,-107,134,-107,135,-107,136,-107,137,-107,138,-107,139,-107,140,-107,141,-107,142,-107,143,-107,144,-107},
    &.{1,-1},
    &.{57,207},
    &.{1,-17,48,-17,51,-17},
    &.{1,-18,48,-18,51,-18},
    &.{1,-20,48,-20,51,-20},
    &.{1,-19,48,-19,51,-19},
    &.{8,208,20,103,23,209,50,105,53,102,71,101},
    &.{8,210,50,105},
    &.{50,211},
    &.{50,212},
    &.{1,-6,4,81,6,213,7,71,9,61,10,67,11,64,12,72,13,62,14,74,15,73,16,68,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,48,-6,49,65,51,-6,52,80,53,18,54,66,55,78,56,63,58,69,59,49,60,70,61,76,62,79,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-29,48,-29,51,-29},
    &.{50,214},
    &.{8,216,20,103,21,218,23,217,50,105,53,102,64,215,71,101},
    &.{1,-168,48,-168,50,-168,51,-168,63,-168,67,-168,69,-168,70,-168,74,-168,75,-168,76,-168,77,-168,79,-168,80,-168,97,-168,103,-168,117,-168,131,-168,132,-168,133,-168,134,-168,135,-168,136,-168,137,-168,138,-168,139,-168,140,-168,141,-168,142,-168,143,-168},
    &.{1,-150,48,-150,50,-150,51,-150,63,-150,69,-150,70,-150,74,-150,75,-150,76,-150,77,-150,79,-150,80,-150,103,-150,117,-150,131,-150,132,-150,133,-150},
    &.{1,-135,48,-135,50,-135,51,-135,53,-135,57,-135,59,-135,63,-135,65,-135,67,-135,68,-135,69,-135,70,-135,74,-135,75,-135,76,-135,77,-135,79,-135,80,-135,85,-135,92,-135,93,-135,94,-135,95,-135,96,-135,97,-135,99,-135,102,-135,103,-135,106,-135,107,-135,108,-135,109,-135,110,-135,111,-135,112,-135,113,-135,117,-135,118,-135,131,-135,132,-135,133,-135,134,-135,135,-135,136,-135,137,-135,138,-135,139,-135,140,-135,141,-135,142,-135,143,-135,144,-135},
    &.{69,-118,103,-118},
    &.{4,219,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{70,221,116,220,117,-139},
    &.{117,222},
    &.{63,223},
    &.{1,-164,48,-164,50,-164,51,-164,63,-164,67,-164,69,-164,70,-164,74,-164,75,-164,76,-164,77,-164,79,-164,80,-164,97,-164,103,-164,117,-164,131,-164,132,-164,133,-164,134,-164,135,-164,136,-164,137,-164,138,-164,139,-164,140,-164,141,-164,142,-164,143,-164},
    &.{1,-166,48,-166,50,-166,51,-166,63,-166,67,-166,69,-166,70,-166,74,-166,75,-166,76,-166,77,-166,79,-166,80,-166,97,-166,103,-166,117,-166,131,-166,132,-166,133,-166,134,-166,135,-166,136,-166,137,-166,138,-166,139,-166,140,-166,141,-166,142,-166,143,-166},
    &.{1,-165,48,-165,50,-165,51,-165,63,-165,67,-165,69,-165,70,-165,74,-165,75,-165,76,-165,77,-165,79,-165,80,-165,97,-165,103,-165,117,-165,131,-165,132,-165,133,-165,134,-165,135,-165,136,-165,137,-165,138,-165,139,-165,140,-165,141,-165,142,-165,143,-165},
    &.{1,-82,48,-82,50,-82,51,-82,63,-82,69,-82,70,-82,76,-82,77,-82,79,-82,80,-82,103,-82,117,-82},
    &.{4,224,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{53,225},
    &.{53,226},
    &.{1,-146,48,-146,50,-146,51,-146,63,-146,69,-146,70,-146,74,-146,75,-146,76,-146,77,-146,79,-146,80,-146,103,-146,117,-146,131,-146,132,96},
    &.{1,-148,48,-148,50,-148,51,-148,63,-148,69,-148,70,-148,74,-148,75,-148,76,-148,77,-148,79,-148,80,-148,103,-148,117,-148,131,-148,132,-148,133,83},
    &.{4,227,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{53,228},
    &.{1,-161,48,-161,50,-161,51,-161,63,-161,67,90,69,-161,70,-161,74,-161,75,-161,76,-161,77,-161,79,-161,80,-161,97,-161,103,-161,117,-161,131,-161,132,-161,133,-161,134,-161,135,-161,136,-161,137,-161,138,-161,139,-161,140,-161,141,-161,142,92,143,91},
    &.{1,-159,48,-159,50,-159,51,-159,63,-159,69,-159,70,-159,74,-159,75,-159,76,-159,77,-159,79,-159,80,-159,97,100,103,-159,117,-159,131,-159,132,-159,133,-159,134,-159,135,-159,136,-159,137,-159,138,-159,139,-159,141,98},
    &.{1,-162,48,-162,50,-162,51,-162,63,-162,67,90,69,-162,70,-162,74,-162,75,-162,76,-162,77,-162,79,-162,80,-162,97,-162,103,-162,117,-162,131,-162,132,-162,133,-162,134,-162,135,-162,136,-162,137,-162,138,-162,139,-162,140,-162,141,-162,142,92,143,91},
    &.{22,232,53,233,65,230,66,234,67,229,68,231},
    &.{50,-52,64,-52},
    &.{20,235,53,102},
    &.{1,-22,48,-22,50,-22,51,-22,53,-22,57,-22,59,-22,63,-22,65,-22,67,-22,68,-22,69,-22,70,-22,74,-22,75,-22,76,-22,77,-22,79,-22,80,-22,85,-22,92,-22,93,-22,94,-22,95,-22,96,-22,97,-22,99,-22,102,-22,103,-22,106,-22,107,-22,108,-22,109,-22,110,-22,111,-22,112,-22,113,-22,117,-22,118,-22,131,-22,132,-22,133,-22,134,-22,135,-22,136,-22,137,-22,138,-22,139,-22,140,-22,141,-22,142,-22,143,-22,144,-22},
    &.{48,148,51,236},
    &.{1,-142,48,-142,50,-142,51,-142,53,-142,57,-142,59,-142,63,-142,65,-142,67,-142,68,-142,69,-142,70,-142,74,-142,75,-142,76,-142,77,-142,79,-142,80,-142,85,-142,92,-142,93,-142,94,-142,95,-142,96,-142,97,-142,99,-142,102,-142,103,-142,106,-142,107,-142,108,-142,109,-142,110,-142,111,-142,112,-142,113,-142,117,-142,118,-142,131,-142,132,-142,133,-142,134,-142,135,-142,136,-142,137,-142,138,-142,139,-142,140,-142,141,-142,142,-142,143,-142,144,-142},
    &.{1,-157,48,-157,50,-157,51,-157,63,-157,69,-157,70,-157,74,-157,75,-157,76,-157,77,-157,79,-157,80,-157,103,-157,117,-157,131,-157,132,-157,133,-157},
    &.{1,-153,48,-153,50,-153,51,-153,63,-153,69,-153,70,-153,74,-153,75,-153,76,-153,77,-153,79,-153,80,-153,103,-153,117,-153,131,-153,132,-153,133,-153},
    &.{1,-156,48,-156,50,-156,51,-156,63,-156,69,-156,70,-156,74,-156,75,-156,76,-156,77,-156,79,-156,80,-156,103,-156,117,-156,131,-156,132,-156,133,-156},
    &.{1,-155,48,-155,50,-155,51,-155,63,-155,69,-155,70,-155,74,-155,75,-155,76,-155,77,-155,79,-155,80,-155,103,-155,117,-155,131,-155,132,-155,133,-155},
    &.{1,-154,48,-154,50,-154,51,-154,63,-154,69,-154,70,-154,74,-154,75,-154,76,-154,77,-154,79,-154,80,-154,103,-154,117,-154,131,-154,132,-154,133,-154},
    &.{1,-152,48,-152,50,-152,51,-152,63,-152,69,-152,70,-152,74,-152,75,-152,76,-152,77,-152,79,-152,80,-152,103,-152,117,-152,131,-152,132,-152,133,-152},
    &.{1,-81,48,-81,50,-81,51,-81,63,-81,69,-81,70,-81,76,-81,77,-81,79,-81,80,237,103,-81,117,-81},
    &.{4,238,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-71,48,-71,50,-71,51,-71,63,-71,69,-71,70,-71,76,-71,77,-71,79,-71,80,-71,103,-71,117,-71},
    &.{53,239},
    &.{1,-73,48,-73,50,-73,51,-73,63,-73,69,-73,70,-73,76,-73,77,-73,79,-73,80,-73,103,-73,117,-73},
    &.{31,241,32,240,44,242,45,24,47,29,53,18,59,49,68,12,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28},
    &.{1,-104,48,-104,50,-104,51,-104,63,-104,69,-104,70,-104,76,-104,77,-104,79,-104,80,-104,103,-104,117,-104},
    &.{1,-99,48,-99,50,-99,51,-99,63,-99,69,-99,70,-99,76,-99,77,-99,79,-99,80,-99,103,-99,117,-99},
    &.{1,-109,48,-109,50,-109,51,-109,53,-109,57,-109,59,-109,63,-109,65,-109,67,-109,68,-109,69,-109,70,-109,74,-109,75,-109,76,-109,77,-109,79,-109,80,-109,92,-109,93,-109,94,-109,95,-109,96,-109,97,-109,99,-109,102,-109,103,-109,106,-109,107,-109,108,-109,109,-109,110,-109,111,-109,112,-109,113,-109,117,-109,118,-109,131,-109,132,-109,133,-109,134,-109,135,-109,136,-109,137,-109,138,-109,139,-109,140,-109,141,-109,142,-109,143,-109,144,-109},
    &.{1,-102,48,-102,50,-102,51,-102,63,-102,69,-102,70,-102,76,-102,77,-102,79,-102,80,-102,103,-102,117,-102},
    &.{69,243,70,156,103,-120,105,155},
    &.{103,244},
    &.{69,-120,70,156,103,205,105,155},
    &.{1,-103,48,-103,50,-103,51,-103,63,-103,69,-103,70,-103,76,-103,77,-103,79,-103,80,-103,103,-103,117,-103},
    &.{1,-101,48,-101,50,-101,51,-101,63,-101,69,-101,70,-101,76,-101,77,-101,79,-101,80,-101,103,-101,117,-101},
    &.{1,-110,48,-110,50,-110,51,-110,53,-110,57,-110,59,-110,63,-110,65,-110,67,-110,68,-110,69,-110,70,-110,74,-110,75,-110,76,-110,77,-110,79,-110,80,-110,92,-110,93,-110,94,-110,95,-110,96,-110,97,-110,99,-110,102,-110,103,-110,106,-110,107,-110,108,-110,109,-110,110,-110,111,-110,112,-110,113,-110,117,-110,118,-110,131,-110,132,-110,133,-110,134,-110,135,-110,136,-110,137,-110,138,-110,139,-110,140,-110,141,-110,142,-110,143,-110,144,-110},
    &.{1,-112,48,-112,50,-112,51,-112,53,-112,57,-112,59,-112,63,-112,65,-112,67,-112,68,-112,69,-112,70,-112,74,-112,75,-112,76,-112,77,-112,79,-112,80,-112,92,-112,93,-112,94,-112,95,-112,96,-112,97,-112,99,-112,102,-112,103,-112,106,-112,107,-112,108,-112,109,-112,110,-112,111,-112,112,-112,113,-112,117,-112,118,-112,131,-112,132,-112,133,-112,134,-112,135,-112,136,-112,137,-112,138,-112,139,-112,140,-112,141,-112,142,-112,143,-112,144,-112},
    &.{44,245,45,24,47,29,53,18,59,49,68,12,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28},
    &.{1,-100,48,-100,50,-100,51,-100,63,-100,69,-100,70,-100,76,-100,77,-100,79,-100,80,-100,103,-100,117,-100},
    &.{1,-136,48,-136,50,-136,51,-136,53,-136,57,-136,59,-136,63,-136,65,-136,67,-136,68,-136,69,-136,70,-136,74,-136,75,-136,76,-136,77,-136,79,-136,80,-136,85,-136,92,-136,93,-136,94,-136,95,-136,96,-136,97,-136,99,-136,102,-136,103,-136,106,-136,107,-136,108,-136,109,-136,110,-136,111,-136,112,-136,113,-136,117,-136,118,-136,131,-136,132,-136,133,-136,134,-136,135,-136,136,-136,137,-136,138,-136,139,-136,140,-136,141,-136,142,-136,143,-136,144,-136},
    &.{4,87,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,43,246,44,58,45,24,47,29,53,18,59,49,65,35,68,12,69,-122,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,103,-122,104,86,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{22,247,53,233,65,230,66,234,67,229,68,231},
    &.{1,-28,48,-28,51,-28},
    &.{8,248,50,105},
    &.{1,-31,48,-31,51,-31},
    &.{19,249,53,250},
    &.{19,251,53,250},
    &.{1,-5,48,-5,51,-5},
    &.{9,254,10,253,17,256,18,252,20,255,52,80,53,102,54,66},
    &.{22,257,53,233,65,230,66,234,67,229,68,231},
    &.{1,-26,48,-26,51,-26},
    &.{8,258,21,259,50,105,64,215},
    &.{8,260,50,105},
    &.{69,-120,70,156,103,-120,105,261},
    &.{117,-137},
    &.{46,262,53,159},
    &.{1,-140,48,-140,50,-140,51,-140,53,-140,57,-140,59,-140,63,-140,65,-140,67,-140,68,-140,69,-140,70,-140,74,-140,75,-140,76,-140,77,-140,79,-140,80,-140,85,-140,92,-140,93,-140,94,-140,95,-140,96,-140,97,-140,99,-140,102,-140,103,-140,106,-140,107,-140,108,-140,109,-140,110,-140,111,-140,112,-140,113,-140,117,-140,118,-140,131,-140,132,-140,133,-140,134,-140,135,-140,136,-140,137,-140,138,-140,139,-140,140,-140,141,-140,142,-140,143,-140,144,-140},
    &.{4,263,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{8,264,50,105},
    &.{50,-75,63,-75,79,-75},
    &.{77,265},
    &.{8,266,50,105},
    &.{83,267},
    &.{22,268,53,233,65,230,66,234,67,229,68,231},
    &.{22,269,53,233,65,230,66,234,67,229,68,231},
    &.{69,270},
    &.{48,-45,50,-45,51,-45,64,-45,70,-45},
    &.{1,-47,48,-47,50,-47,51,-47,64,-47,70,-47},
    &.{22,271,53,233,65,230,66,234,67,229,68,231},
    &.{50,-54,64,-54,70,176,72,272},
    &.{1,-21,48,-21,50,-21,51,-21,53,-21,57,-21,59,-21,63,-21,65,-21,67,-21,68,-21,69,-21,70,-21,74,-21,75,-21,76,-21,77,-21,79,-21,80,-21,85,-21,92,-21,93,-21,94,-21,95,-21,96,-21,97,-21,99,-21,102,-21,103,-21,106,-21,107,-21,108,-21,109,-21,110,-21,111,-21,112,-21,113,-21,117,-21,118,-21,131,-21,132,-21,133,-21,134,-21,135,-21,136,-21,137,-21,138,-21,139,-21,140,-21,141,-21,142,-21,143,-21,144,-21},
    &.{8,273,27,274,50,105,78,39},
    &.{1,-78,48,-78,50,-78,51,-78,63,-78,69,-78,70,-78,76,-78,77,-78,79,-78,80,275,103,-78,117,-78},
    &.{4,276,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{48,-87,51,-87},
    &.{48,278,51,277},
    &.{8,279,50,105,85,280},
    &.{1,-111,48,-111,50,-111,51,-111,53,-111,57,-111,59,-111,63,-111,65,-111,67,-111,68,-111,69,-111,70,-111,74,-111,75,-111,76,-111,77,-111,79,-111,80,-111,92,-111,93,-111,94,-111,95,-111,96,-111,97,-111,99,-111,102,-111,103,-111,106,-111,107,-111,108,-111,109,-111,110,-111,111,-111,112,-111,113,-111,117,-111,118,-111,131,-111,132,-111,133,-111,134,-111,135,-111,136,-111,137,-111,138,-111,139,-111,140,-111,141,-111,142,-111,143,-111,144,-111},
    &.{1,-116,48,-116,50,-116,51,-116,53,-116,57,-116,59,-116,63,-116,65,-116,67,-116,68,-116,69,-116,70,-116,74,-116,75,-116,76,-116,77,-116,79,-116,80,-116,92,-116,93,-116,94,-116,95,-116,96,-116,97,-116,99,-116,102,-116,103,-116,106,-116,107,-116,108,-116,109,-116,110,-116,111,-116,112,-116,113,-116,117,-116,118,-116,131,-116,132,-116,133,-116,134,-116,135,-116,136,-116,137,-116,138,-116,139,-116,140,-116,141,-116,142,-116,143,-116,144,-116},
    &.{1,-114,48,-114,50,-114,51,-114,53,-114,57,-114,59,-114,63,-114,65,-114,67,-114,68,-114,69,-114,70,203,74,-114,75,-114,76,-114,77,-114,79,-114,80,-114,92,-114,93,-114,94,-114,95,-114,96,-114,97,-114,99,-114,101,281,102,-114,103,-114,106,-114,107,-114,108,-114,109,-114,110,-114,111,-114,112,-114,113,-114,117,-114,118,-114,131,-114,132,-114,133,-114,134,-114,135,-114,136,-114,137,-114,138,-114,139,-114,140,-114,141,-114,142,-114,143,-114,144,-114},
    &.{103,282},
    &.{1,-30,48,-30,51,-30},
    &.{1,-27,48,-27,51,-27},
    &.{48,284,51,283},
    &.{48,-41,51,-41},
    &.{48,284,51,285},
    &.{48,-35,51,-35},
    &.{48,-40,51,-40},
    &.{48,-39,51,-39},
    &.{48,-38,51,-38},
    &.{48,287,51,286},
    &.{50,-46},
    &.{1,-24,48,-24,51,-24},
    &.{8,288,50,105},
    &.{1,-25,48,-25,51,-25},
    &.{69,-119,103,-119},
    &.{70,221,116,289,117,-139},
    &.{70,-141,117,-141},
    &.{1,-83,48,-83,50,-83,51,-83,63,-83,69,-83,70,-83,76,-83,77,-83,79,-83,80,-83,103,-83,117,-83},
    &.{50,-76,63,-76,79,-76},
    &.{1,-84,48,-84,50,-84,51,-84,63,-84,69,-84,70,-84,76,-84,77,-84,79,-84,80,-84,103,-84,117,-84},
    &.{4,290,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-50,48,-50,50,-50,51,-50,64,-50,70,-50},
    &.{1,-48,48,-48,50,-48,51,-48,64,-48,70,-48},
    &.{22,291,53,233,65,230,66,234,67,229,68,231},
    &.{1,-49,48,-49,50,-49,51,-49,64,-49,70,-49},
    &.{50,-53,64,-53},
    &.{1,-80,48,-80,50,-80,51,-80,63,-80,69,-80,70,-80,76,-80,77,-80,79,-80,80,-80,103,-80,117,-80},
    &.{1,-79,48,-79,50,-79,51,-79,63,-79,69,-79,70,-79,76,-79,77,-79,79,-79,80,-79,103,-79,117,-79},
    &.{4,292,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-72,48,-72,50,-72,51,-72,63,-72,69,-72,70,-72,76,-72,77,-72,79,-72,80,-72,103,-72,117,-72},
    &.{1,-86,48,-86,50,-86,51,-86,63,-86,69,-86,70,-86,76,-86,77,-86,79,-86,80,-86,103,-86,117,-86},
    &.{32,293,44,242,45,24,47,29,48,-89,51,-89,53,18,59,49,68,12,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28},
    &.{48,-91,51,-91},
    &.{4,294,24,54,25,17,27,16,28,46,29,53,30,4,33,55,34,47,35,33,36,34,37,52,38,15,39,38,40,25,41,7,42,45,44,58,45,24,47,29,53,18,59,49,65,35,68,12,73,43,78,39,81,20,82,26,84,44,86,13,87,14,88,40,89,36,90,10,91,41,97,31,98,56,102,50,106,11,107,5,108,42,109,32,110,9,111,21,112,6,113,51,118,28,121,48,123,22,124,23,125,8,126,30,127,37,128,27,129,19,130,59},
    &.{1,-113,48,-113,50,-113,51,-113,53,-113,57,-113,59,-113,63,-113,65,-113,67,-113,68,-113,69,-113,70,-113,74,-113,75,-113,76,-113,77,-113,79,-113,80,-113,92,-113,93,-113,94,-113,95,-113,96,-113,97,-113,99,-113,102,-113,103,-113,106,-113,107,-113,108,-113,109,-113,110,-113,111,-113,112,-113,113,-113,117,-113,118,-113,131,-113,132,-113,133,-113,134,-113,135,-113,136,-113,137,-113,138,-113,139,-113,140,-113,141,-113,142,-113,143,-113,144,-113},
    &.{1,-132,48,-132,50,-132,51,-132,53,-132,57,-132,59,-132,63,-132,65,-132,67,-132,68,-132,69,-132,70,-132,74,-132,75,-132,76,-132,77,-132,79,-132,80,-132,85,-132,92,-132,93,-132,94,-132,95,-132,96,-132,97,-132,99,-132,102,-132,103,-132,106,-132,107,-132,108,-132,109,-132,110,-132,111,-132,112,-132,113,-132,117,-132,118,-132,131,-132,132,-132,133,-132,134,-132,135,-132,136,-132,137,-132,138,-132,139,-132,140,-132,141,-132,142,-132,143,-132,144,-132},
    &.{1,-32,48,-32,51,-32},
    &.{48,-43,51,-43,53,295},
    &.{1,-33,48,-33,51,-33},
    &.{1,-34,48,-34,51,-34},
    &.{9,254,10,253,18,296,20,255,48,-37,51,-37,52,80,53,102,54,66},
    &.{1,-23,48,-23,51,-23},
    &.{117,-138},
    &.{8,297,50,105},
    &.{1,-51,48,-51,50,-51,51,-51,64,-51,70,-51},
    &.{1,-77,48,-77,50,-77,51,-77,63,-77,69,-77,70,-77,76,-77,77,-77,79,-77,80,-77,103,-77,117,-77},
    &.{48,-88,51,-88},
    &.{48,-90,51,-90},
    &.{48,-42,51,-42},
    &.{48,-36,51,-36},
    &.{1,-85,48,-85,50,-85,51,-85,63,-85,69,-85,70,-85,76,-85,77,-85,79,-85,80,-85,103,-85,117,-85},
};

const parse_table = blk: {
    @setEvalBranchQuota(100000);
    var t: [NUM_STATES][NUM_SYMBOLS]i16 = .{.{0} ** NUM_SYMBOLS} ** NUM_STATES;
    for (sparse, 0..) |row, state| {
        var i: usize = 0;
        while (i < row.len) : (i += 2) {
            t[state][@intCast(row[i])] = row[i + 1];
        }
    }
    break :blk t;
};

fn getAction(state: u16, sym: u16) i16 {
    return parse_table[state][sym];
}
// X "c" excludes: shift instead of reduce when pre==0 and char matches
const x_excludes = [_]struct { state: u16, char: u8, shift: u16 }{
};

fn getImmediateShift(state: u16, char: u8) ?i16 {
    for (x_excludes) |x| {
        if (x.state == state and x.char == char) return @intCast(x.shift);
    }
    return null;
}
const start_states = [_]struct { sym: u16, state: u16 }{
    .{ .sym = 3, .state = 0 },
    .{ .sym = 4, .state = 1 },
};

fn getStartState(start_sym: u16) u16 {
    for (start_states) |entry| {
        if (entry.sym == start_sym) return entry.state;
    }
    return 0;
}

const accept_rules = [_]u16{ 142, 143 };

fn isAcceptRule(rule_id: u16) bool {
    for (accept_rules) |ar| if (rule_id == ar) return true;
    return false;
}
