//! Parser (Auto-generated)
//!
//! Generated by grammar.zig from a .grammar file.
//! Contains both lexer and parser.

const std = @import("std");
const MAX_ARGS: usize = 32;
const rip = @import("rip.zig");

// SIMD helpers (fallback if simd.zig not available)
const simd = struct {
    fn findByte(haystack: []const u8, needle: u8) usize {
        for (haystack, 0..) |c, i| if (c == needle) return i;
        return haystack.len;
    }
};

// =============================================================================
// TOKEN CATEGORIES
// =============================================================================

pub const TokenCat = enum(u8) {
    @"ident",
    @"integer",
    @"real",
    @"string_sq",
    @"string_dq",
    @"true",
    @"false",
    @"plus",
    @"minus",
    @"star",
    @"slash",
    @"percent",
    @"power",
    @"eq",
    @"ne",
    @"lt",
    @"gt",
    @"le",
    @"ge",
    @"and_sym",
    @"or_sym",
    @"not_sym",
    @"question",
    @"nullish",
    @"bar",
    @"at",
    @"assign",
    @"const_assign",
    @"plus_assign",
    @"minus_assign",
    @"star_assign",
    @"slash_assign",
    @"lparen",
    @"rparen",
    @"lbrace",
    @"rbrace",
    @"lbracket",
    @"rbracket",
    @"comma",
    @"colon",
    @"arrow",
    @"fat_arrow",
    @"dot",
    @"dotdot",
    @"pipe",
    @"indent",
    @"outdent",
    @"newline",
    @"comment",
    @"eof",
    @"err",

    // Internal (used by generator)
    @"skip",
};

// =============================================================================
// TOKEN STRUCT (8 bytes)
// =============================================================================

pub const Token = struct {
    pos: u32,         // Byte position in source (4 bytes)
    len: u16,         // Token length in bytes (2 bytes)
    cat: TokenCat,    // Token category (1 byte)
    pre: u8,          // Preceding whitespace OR dot-level for indent (1 byte)

    comptime {
        std.debug.assert(@sizeOf(Token) == 8);
    }
};

// =============================================================================
// LEXER
// =============================================================================
pub const BaseLexer = struct {
    const Self = @This();

    source: []const u8,
    pos: u32,
    // State variables
    beg: i32,
    paren: i32,
    brace: i32,

    pub fn init(source: []const u8) Self {
        return .{
            .source = source,
            .pos = 0,
            .beg = 1,
            .paren = 0,
            .brace = 0,
        };
    }

    /// Get the text slice for a token (zero-copy into source)
    pub fn text(self: *const Self, tok: Token) []const u8 {
        const start: usize = tok.pos;
        const end: usize = @min(start + tok.len, self.source.len);
        if (start >= self.source.len) return "";
        return self.source[start..end];
    }

    /// Reset lexer to beginning
    pub fn reset(self: *Self) void {
        self.pos = 0;
        self.beg = 1;
        self.paren = 0;
        self.brace = 0;
    }

    /// Peek at current character (0 if at end)
    inline fn peek(self: *const Self) u8 {
        return if (self.pos < self.source.len) self.source[self.pos] else 0;
    }

    /// Peek at character at offset (0 if at end)
    inline fn peekAt(self: *const Self, offset: u32) u8 {
        const p = self.pos + offset;
        return if (p < self.source.len) self.source[p] else 0;
    }

    /// Get next token
    pub fn next(self: *Self) Token {
        return self.matchRules();
    }

    // Character classification flags (generated from grammar patterns)
    const DIGIT: u8 = 1 << 0;
    const LETTER: u8 = 1 << 1;
    const WHITESPACE: u8 = 1 << 2;

    const char_flags: [256]u8 = blk: {
        var table: [256]u8 = [_]u8{0} ** 256;
        for ('0'..'9' + 1) |c| table[c] = DIGIT;
        for ('A'..'Z' + 1) |c| table[c] = LETTER;
        for ('a'..'z' + 1) |c| table[c] = LETTER;
        table['_'] = LETTER;
        table[' '] = WHITESPACE;
        table['\t'] = WHITESPACE;
        break :blk table;
    };

    inline fn isDigit(c: u8) bool {
        return (char_flags[c] & DIGIT) != 0;
    }

    inline fn isLetter(c: u8) bool {
        return (char_flags[c] & LETTER) != 0;
    }

    inline fn isWhitespace(c: u8) bool {
        return (char_flags[c] & WHITESPACE) != 0;
    }

    inline fn isIdentChar(c: u8) bool {
        return isLetter(c) or isDigit(c);
    }
    /// Match lexer rules
    pub fn matchRules(self: *Self) Token {
        // Count whitespace first
        const ws_start = self.pos;
        while (self.pos < self.source.len and isWhitespace(self.source[self.pos])) {
            self.pos += 1;
        }
        const ws_count: u8 = @intCast(@min(self.pos - ws_start, 255));
        // EOF check
        if (self.pos >= self.source.len) {            return Token{ .cat = .@"eof", .pre = ws_count, .pos = self.pos, .len = 0 };
        }

        const start = self.pos;
        const c = self.source[self.pos];
        // Newline handling (generated from grammar rules)
        if (c == '\n' or c == '\r') {
            if (c == '\r' and self.pos + 1 < self.source.len and self.source[self.pos + 1] == '\n') {
                self.pos += 2;
                self.beg = 1;
                return Token{ .cat = .@"newline", .pre = ws_count, .pos = start, .len = 2 };
            }
                self.pos += 1;
                self.beg = 1;
                return Token{ .cat = .@"newline", .pre = ws_count, .pos = start, .len = 1 };
        }
        // From here, clear line-start flag
        self.beg = 0;
        if (c == '"') {            self.pos += 1;
            while (self.pos < self.source.len) {
                const ch = self.source[self.pos];
                if (ch == '"') {
                    self.pos += 1;
                    return Token{ .cat = .@"string_dq", .pre = ws_count, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (ch == '\\') { self.pos += 2; continue; }
                if (ch == '\n') break;
                self.pos += 1;
            }
            return Token{ .cat = .@"err", .pre = ws_count, .pos = start, .len = @intCast(self.pos - start) };
        }
        if (c == '\'') {            self.pos += 1;
            while (self.pos < self.source.len) {
                const ch = self.source[self.pos];
                if (ch == '\'') {
                    self.pos += 1;
                    if (self.pos < self.source.len and self.source[self.pos] == '\'') { self.pos += 1; continue; }
                    return Token{ .cat = .@"string_sq", .pre = ws_count, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (ch == '\n') break;
                self.pos += 1;
            }
            return Token{ .cat = .@"err", .pre = ws_count, .pos = start, .len = @intCast(self.pos - start) };
        }
        // Number (digit or leading dot followed by digit)
        if (isDigit(c) or (c == '.' and self.pos + 1 < self.source.len and isDigit(self.source[self.pos + 1]))) {
            return self.scanNumber(start, ws_count);
        }
        // Identifier
        if (isLetter(c)) {
            return self.scanIdent(start, ws_count);
        }
        // Comment (scan to end of line)
        if (c == '#') {
            while (self.pos < self.source.len and self.source[self.pos] != '\n') {
                self.pos += 1;
            }
            return Token{ .cat = .@"comment", .pre = ws_count, .pos = start, .len = @intCast(self.pos - start) };
        }
        // Single/multi-char operators
        self.pos += 1;
        return switch (c) {
            '!' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"ne", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"not_sym", .pre = ws_count, .pos = start, .len = 1 };
            },
            '%' => Token{ .cat = .@"percent", .pre = ws_count, .pos = start, .len = 1 },
            '&' => blk: {
                if (self.peek() == '&') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"and_sym", .pre = ws_count, .pos = start, .len = 2 };
                }
                self.pos -= 1;
                break :blk Token{ .cat = .@"err", .pre = ws_count, .pos = start, .len = 1 };
            },
            '(' => blk: {
                self.paren += 1;
                    break :blk Token{ .cat = .@"lparen", .pre = ws_count, .pos = start, .len = 1 };
            },
            ')' => blk: {
                self.paren -= 1;
                    break :blk Token{ .cat = .@"rparen", .pre = ws_count, .pos = start, .len = 1 };
            },
            '*' => blk: {
                if (self.peek() == '*') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"power", .pre = ws_count, .pos = start, .len = 2 };
                }
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"star_assign", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"star", .pre = ws_count, .pos = start, .len = 1 };
            },
            '+' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"plus_assign", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"plus", .pre = ws_count, .pos = start, .len = 1 };
            },
            ',' => Token{ .cat = .@"comma", .pre = ws_count, .pos = start, .len = 1 },
            '-' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"minus_assign", .pre = ws_count, .pos = start, .len = 2 };
                }
                if (self.peek() == '>') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"arrow", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"minus", .pre = ws_count, .pos = start, .len = 1 };
            },
            '.' => blk: {
                if (self.peek() == '.') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"dotdot", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"dot", .pre = ws_count, .pos = start, .len = 1 };
            },
            '/' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"slash_assign", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"slash", .pre = ws_count, .pos = start, .len = 1 };
            },
            ':' => Token{ .cat = .@"colon", .pre = ws_count, .pos = start, .len = 1 },
            '<' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"le", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"lt", .pre = ws_count, .pos = start, .len = 1 };
            },
            '=' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"eq", .pre = ws_count, .pos = start, .len = 2 };
                }
                if (self.peek() == '!') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"const_assign", .pre = ws_count, .pos = start, .len = 2 };
                }
                if (self.peek() == '>') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"fat_arrow", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"assign", .pre = ws_count, .pos = start, .len = 1 };
            },
            '>' => blk: {
                if (self.peek() == '=') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"ge", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"gt", .pre = ws_count, .pos = start, .len = 1 };
            },
            '?' => blk: {
                if (self.peek() == '?') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"nullish", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"question", .pre = ws_count, .pos = start, .len = 1 };
            },
            '@' => Token{ .cat = .@"at", .pre = ws_count, .pos = start, .len = 1 },
            '[' => Token{ .cat = .@"lbracket", .pre = ws_count, .pos = start, .len = 1 },
            '\\' => blk: {
                if (self.peek() == '\n') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"skip", .pre = ws_count, .pos = start, .len = 2 };
                }
                self.pos -= 1;
                break :blk Token{ .cat = .@"err", .pre = ws_count, .pos = start, .len = 1 };
            },
            ']' => Token{ .cat = .@"rbracket", .pre = ws_count, .pos = start, .len = 1 },
            '{' => blk: {
                self.brace += 1;
                    break :blk Token{ .cat = .@"lbrace", .pre = ws_count, .pos = start, .len = 1 };
            },
            '|' => blk: {
                if (self.peek() == '|') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"or_sym", .pre = ws_count, .pos = start, .len = 2 };
                }
                if (self.peek() == '>') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"pipe", .pre = ws_count, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"bar", .pre = ws_count, .pos = start, .len = 1 };
            },
            '}' => blk: {
                self.brace -= 1;
                    break :blk Token{ .cat = .@"rbrace", .pre = ws_count, .pos = start, .len = 1 };
            },
            else => Token{ .cat = .@"err", .pre = ws_count, .pos = start, .len = 1 },
        };
    }

    /// Scan number (generated from grammar)
    fn scanNumber(self: *Self, start: u32, ws: u8) Token {        var has_decimal = false;        const starts_with_dot = self.source[self.pos] == '.';
        // Integer part
        if (isDigit(self.source[self.pos])) {
            while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                self.pos += 1;
            }
        }
        // Decimal part
        if (self.pos < self.source.len and self.source[self.pos] == '.') {
            const next_c = if (self.pos + 1 < self.source.len) self.source[self.pos + 1] else 0;
            if (isDigit(next_c)) {
                has_decimal = true;
                self.pos += 1;
                while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                    self.pos += 1;
                }
            }
        }
        // Classify
        const token_cat: TokenCat = if (has_decimal or starts_with_dot)
            .@"real"
        else
            .@"integer";

        return Token{ .cat = token_cat, .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }

    /// Scan identifier (generated from grammar)
    fn scanIdent(self: *Self, start: u32, ws: u8) Token {
        while (self.pos < self.source.len and isIdentChar(self.source[self.pos])) {
            self.pos += 1;
        }
        return Token{ .cat = .@"ident", .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }
};

pub const Lexer = if (@hasDecl(rip, "Lexer")) rip.Lexer else BaseLexer;

// =============================================================================
// Tag Enum (re-exported from language module)
// =============================================================================
pub const Tag = rip.Tag;

// =============================================================================
// S-Expression (AST Node) - 5 Clean Variants
// =============================================================================

pub const Sexp = union(enum) {
    nil:  void,                                        // Empty (nothing)
    tag:  Tag,                                         // Semantic type (1 byte)
    src:  struct { pos: u32, len: u16, id: u16 },      // Source ref + identity (8 bytes)
    str:  []const u8,                                  // Embedded string (16 bytes)
    list: []const Sexp,                                // Compound: (tag child1 ...)

    /// Get token text from source
    pub fn getText(self: Sexp, source: []const u8) []const u8 {
        return switch (self) {
            .src => |s| source[s.pos..][0..s.len],
            .str => |s| s,
            else => "",
        };
    }

    /// Format for debug output
    pub fn write(self: Sexp, source: []const u8, w: anytype) !void {
        switch (self) {
            .nil => try w.writeAll("_"),
            .tag => |t| try w.print("{s}", .{@tagName(t)}),
            .src => |s| try w.print("{s}", .{source[s.pos..][0..s.len]}),
            .str => |s| try w.print("\"{s}\"", .{s}),
            .list => |items| {
                try w.writeAll("(");
                for (items, 0..) |item, i| {
                    if (i > 0) try w.writeAll(" ");
                    try item.write(source, w);
                }
                try w.writeAll(")");
            },
        }
    }
};

// =============================================================================
// Parser
// =============================================================================

pub const Parser = struct {
    arena: std.heap.ArenaAllocator,
    lexer: Lexer,
    source: []const u8,
    current: Token,
    injected_token: ?u16 = null,
    last_matched_id: u16 = 0,

    state_stack: std.ArrayListUnmanaged(u16) = .{},
    value_stack: std.ArrayListUnmanaged(Sexp) = .{},

    pub fn init(backing_allocator: std.mem.Allocator, source: []const u8) Parser {
        var p = Parser{
            .arena = std.heap.ArenaAllocator.init(backing_allocator),
            .lexer = Lexer.init(source),
            .source = source,
            .current = undefined,
        };
        p.current = p.lexer.next();
        return p;
    }

    pub fn deinit(self: *Parser) void {
        self.arena.deinit();
    }

    fn allocator(self: *Parser) std.mem.Allocator {
        return self.arena.allocator();
    }

    pub fn printError(self: *Parser) void {
        const pos: usize = @min(self.current.pos, self.source.len);
        var line: usize = 1;
        var col: usize = 1;
        var i: usize = 0;
        while (i < pos) : (i += 1) {
            if (self.source[i] == '\n') {
                line += 1;
                col = 1;
            } else {
                col += 1;
            }
        }
        std.debug.print("Parse error at line {d}, column {d}: unexpected {s}\n", .{
            line,
            col,
            @tagName(self.current.cat),
        });
    }

    fn doParse(self: *Parser, start_sym: u16) !Sexp {
        const start_state = getStartState(start_sym);
        self.state_stack.clearRetainingCapacity();
        self.value_stack.clearRetainingCapacity();
        try self.state_stack.append(self.allocator(), start_state);

        while (true) {
            const state = self.state_stack.getLast();
            const sym = if (self.injected_token) |inj| inj else self.tokenToSymbol(self.current);
            var action = getAction(state, sym);

            // X "c" check: if reducing and next char matches with pre==0, shift instead
            if (action < -1 and self.current.pre == 0 and self.current.pos < self.source.len) {
                if (getImmediateShift(state, self.source[self.current.pos])) |shift_target| {
                    action = shift_target;
                }
            }

            if (action == 0) {
                return error.ParseError;
            } else if (action == -1) {
                return self.value_stack.getLast();
            } else if (action > 0) {
                // Shift
                if (self.injected_token != null) {
                    try self.value_stack.append(self.allocator(), .nil);
                    self.injected_token = null;
                } else {
                    try self.value_stack.append(self.allocator(), .{ .src = .{
                        .pos = self.current.pos,
                        .len = self.current.len,
                        .id  = self.last_matched_id,
                    } });
                    self.last_matched_id = 0;
                    self.current = self.lexer.next();
                }
                try self.state_stack.append(self.allocator(), @intCast(action));
            } else {
                // Reduce
                const rule_id: u16 = @intCast(-action - 2);
                var pass: [MAX_ARGS]Sexp = undefined;
                const len = rule_len[rule_id];
                for (0..len) |i| {
                    pass[len - 1 - i] = self.value_stack.pop().?;
                    _ = self.state_stack.pop();
                }

                const result = self.executeAction(rule_id, pass[0..len]);

                if (isAcceptRule(rule_id)) return result;

                try self.value_stack.append(self.allocator(), result);

                const goto_state = self.state_stack.getLast();
                const next = getAction(goto_state, rule_lhs[rule_id]);
                if (next <= 0) return error.ParseError;
                try self.state_stack.append(self.allocator(), @intCast(next));
            }
        }
    }

    /// Spread list helper: [head, ...tail]
    fn spreadList(self: *Parser, head: Sexp, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .{};
        out.append(self.allocator(), head) catch return .nil;
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Spread only: [...tail]
    fn spreadOnly(self: *Parser, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .{};
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Default list handler
    fn list(self: *Parser, pass: []Sexp) Sexp {
        if (pass.len == 0) return .nil;
        if (pass.len == 1) return pass[0];
        var out: std.ArrayListUnmanaged(Sexp) = .{};
        for (pass) |v| out.append(self.allocator(), v) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Build S-expression: (tag items...) with trailing nil trimming
    inline fn sexp(self: *Parser, comptime tag: Tag, items: []const Sexp) Sexp {
        if (items.len == 0) {
            const result = self.allocator().alloc(Sexp, 1) catch return .nil;
            result[0] = .{ .tag = tag };
            return .{ .list = result };
        }
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag ...spread) - tag + spread items
    inline fn sexpSpread(self: *Parser, comptime tag: Tag, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag pos ...spread) - tag + position + spread items
    inline fn sexpPosSpread(self: *Parser, comptime tag: Tag, pos: Sexp, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const skip_pos = (pos == .nil and len == 0);
        const total = if (skip_pos) 1 else len + 2;
        const result = self.allocator().alloc(Sexp, total) catch return .nil;
        result[0] = .{ .tag = tag };
        if (!skip_pos) {
            result[1] = pos;
            if (len > 0) @memcpy(result[2..][0..len], items[0..len]);
        }
        return .{ .list = result };
    }

    fn executeAction(self: *Parser, rule_id: u16, pass: []Sexp) Sexp {
        return switch (rule_id) {
            0 => self.sexpSpread(.@"module", pass[1]),
            1 => pass[1],
            2 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            3 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            4 => pass[0],
            5 => self.list(pass),
            6 => self.list(pass),
            7 => self.list(pass),
            8 => self.list(pass),
            9 => self.list(pass),
            10 => self.list(pass),
            11 => self.list(pass),
            12 => self.list(pass),
            13 => self.list(pass),
            14 => self.list(pass),
            15 => self.sexp(.@"pub", &.{pass[1]}),
            16 => self.sexp(.@"pub", &.{pass[1]}),
            17 => self.sexp(.@"pub", &.{pass[1]}),
            18 => self.sexp(.@"pub", &.{pass[1]}),
            19 => self.sexpSpread(.@"block", pass[1]),
            20 => self.sexp(.@"block", &.{}),
            21 => self.sexp(.@"fun", &.{pass[1], pass[2], pass[3], pass[4]}),
            22 => self.sexp(.@"fun", &.{pass[1], pass[2], .nil, pass[3]}),
            23 => self.sexp(.@"fun", &.{pass[1], .nil, pass[2], pass[3]}),
            24 => self.sexp(.@"fun", &.{pass[1], .nil, .nil, pass[2]}),
            25 => self.sexp(.@"sub", &.{pass[1], pass[2], .nil, pass[3]}),
            26 => self.sexp(.@"sub", &.{pass[1], .nil, .nil, pass[2]}),
            27 => self.sexp(.@"use", &.{pass[1]}),
            28 => self.sexp(.@"alias", &.{pass[1], pass[3]}),
            29 => self.sexp(.@"test", &.{pass[1], pass[2]}),
            30 => self.sexpPosSpread(.@"enum", pass[1], pass[3]),
            31 => self.sexpPosSpread(.@"error_set", pass[1], pass[3]),
            32 => self.sexpPosSpread(.@"struct", pass[1], pass[3]),
            33 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            34 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            35 => pass[0],
            36 => self.list(pass),
            37 => self.list(pass),
            38 => self.list(pass),
            39 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            40 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            41 => pass[0],
            42 => pass[0],
            43 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@":" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            44 => pass[1],
            45 => self.list(pass),
            46 => self.sexp(.@"error_union", &.{pass[1]}),
            47 => self.sexp(.@"?", &.{pass[1]}),
            48 => self.sexp(.@"ptr", &.{pass[1]}),
            49 => self.sexp(.@"slice", &.{pass[2]}),
            50 => self.spreadList(pass[0], pass[1]),
            51 => self.spreadList(pass[1], pass[2]),
            52 => .{ .list = &[_]Sexp{} },
            53 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            54 => self.list(pass),
            55 => self.list(pass),
            56 => self.list(pass),
            57 => self.list(pass),
            58 => self.list(pass),
            59 => self.list(pass),
            60 => self.list(pass),
            61 => self.list(pass),
            62 => self.list(pass),
            63 => self.list(pass),
            64 => self.list(pass),
            65 => self.list(pass),
            66 => self.list(pass),
            67 => self.list(pass),
            68 => self.list(pass),
            69 => self.list(pass),
            70 => self.sexp(.@"if", &.{pass[2], pass[0], pass[4]}),
            71 => self.sexp(.@"if", &.{pass[2], pass[0]}),
            72 => self.sexp(.@"??", &.{pass[0], pass[2]}),
            73 => self.sexp(.@"catch", &.{pass[0], pass[3], pass[4]}),
            74 => self.sexp(.@"catch", &.{pass[0], pass[2]}),
            75 => self.list(pass),
            76 => self.sexp(.@"as", &.{pass[0], pass[2]}),
            77 => self.sexp(.@"as", &.{pass[0], pass[2]}),
            78 => self.sexp(.@"if", &.{pass[1], pass[2], pass[4]}),
            79 => self.sexp(.@"if", &.{pass[1], pass[2], pass[4]}),
            80 => self.sexp(.@"if", &.{pass[1], pass[2]}),
            81 => self.sexp(.@"while", &.{pass[1], .nil, pass[2]}),
            82 => self.sexp(.@"while", &.{pass[1], pass[3], pass[4]}),
            83 => self.sexp(.@"for", &.{pass[1], .nil, pass[3], pass[4]}),
            84 => self.sexp(.@"for", &.{pass[1], pass[3], pass[5], pass[6]}),
            85 => self.sexpPosSpread(.@"match", pass[1], pass[3]),
            86 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), pass[0]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            87 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            88 => pass[0],
            89 => self.sexp(.@"arm", &.{pass[0], pass[2]}),
            90 => self.sexp(.@"arm", &.{pass[0], pass[1]}),
            91 => self.sexp(.@"return", &.{pass[1]}),
            92 => self.sexp(.@"return", &.{}),
            93 => self.sexp(.@"break", &.{}),
            94 => self.sexp(.@"continue", &.{}),
            95 => self.sexp(.@"defer", &.{pass[1]}),
            96 => self.sexp(.@"errdefer", &.{pass[1]}),
            97 => self.sexp(.@"comptime", &.{pass[1]}),
            98 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"=" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            99 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"+=" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            100 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"-=" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            101 => self.sexp(.@"*=", &.{pass[0], pass[2]}),
            102 => self.sexp(.@"/=", &.{pass[0], pass[2]}),
            103 => self.sexp(.@"const", &.{pass[0], pass[2]}),
            104 => self.sexp(.@"not", &.{pass[1]}),
            105 => self.sexp(.@"neg", &.{pass[1]}),
            106 => self.sexp(.@"try", &.{pass[1]}),
            107 => self.list(pass),
            108 => self.sexp(.@"await", &.{pass[0], pass[2]}),
            109 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"." }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            110 => self.sexp(.@"index", &.{pass[0], pass[2]}),
            111 => self.spreadList(pass[0], pass[1]),
            112 => self.spreadList(pass[1], pass[2]),
            113 => .{ .list = &[_]Sexp{} },
            114 => self.sexpPosSpread(.@"call", pass[0], pass[1]),
            115 => self.sexpPosSpread(.@"call", pass[0], pass[2]),
            116 => self.list(pass),
            117 => self.spreadList(pass[0], pass[1]),
            118 => self.spreadList(pass[1], pass[2]),
            119 => .{ .list = &[_]Sexp{} },
            120 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            121 => .{ .list = &[_]Sexp{} },
            122 => self.list(pass),
            123 => self.list(pass),
            124 => self.list(pass),
            125 => self.list(pass),
            126 => self.list(pass),
            127 => self.list(pass),
            128 => self.list(pass),
            129 => self.sexp(.@"unreachable", &.{}),
            130 => self.sexp(.@"undefined", &.{}),
            131 => self.sexpPosSpread(.@"builtin", pass[1], pass[3]),
            132 => self.list(pass),
            133 => self.list(pass),
            134 => self.sexpSpread(.@"array", pass[1]),
            135 => pass[1],
            136 => self.spreadList(pass[0], pass[1]),
            137 => self.spreadList(pass[1], pass[2]),
            138 => .{ .list = &[_]Sexp{} },
            139 => self.sexpPosSpread(.@"literal", pass[0], pass[2]),
            140 => self.sexp(.@"pair", &.{pass[0], pass[2]}),
            141 => self.sexp(.@"lambda", &.{pass[1], .nil, pass[2]}),
            142 => self.sexp(.@"lambda", &.{.nil, .nil, pass[1]}),
            143 => self.list(pass),
            144 => self.list(pass),
            145 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"|>" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            146 => pass[0],
            147 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"||" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            148 => pass[0],
            149 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"&&" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            150 => pass[0],
            151 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"==" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            152 => self.sexp(.@"!=", &.{pass[0], pass[2]}),
            153 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"<" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            154 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@">" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            155 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"<=" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            156 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@">=" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            157 => pass[0],
            158 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@".." }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            159 => pass[0],
            160 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"+" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            161 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"-" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            162 => pass[0],
            163 => self.sexp(.@"*", &.{pass[0], pass[2]}),
            164 => self.sexp(.@"/", &.{pass[0], pass[2]}),
            165 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .{}; out.append(self.allocator(), .{ .tag = .@"%" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[2]) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            166 => pass[0],
            167 => self.sexp(.@"**", &.{pass[0], pass[2]}),
            168 => pass[0],
            169 => pass[0],
            else => .nil,
        };
    }

    fn tokenToSymbol(self: *Parser, token: Token) u16 {
        return switch (token.cat) {
            .@"eof" => 1,
            .@"ident" => self.identToSymbol(token),
            .@"newline" => 49,
            .@"indent" => 51,
            .@"outdent" => 52,
            .@"string_dq" => 60,
            .@"integer" => 107,
            .@"real" => 108,
            .@"string_sq" => 109,
            .@"true" => 110,
            .@"false" => 111,
            .@"assign" => 58,
            .@"colon" => 64,
            .@"not_sym" => 66,
            .@"question" => 67,
            .@"star" => 68,
            .@"lbracket" => 69,
            .@"rbracket" => 70,
            .@"comma" => 71,
            .@"bar" => 80,
            .@"minus" => 98,
            .@"dot" => 100,
            .@"lparen" => 103,
            .@"rparen" => 104,
            .@"at" => 114,
            .@"lbrace" => 115,
            .@"rbrace" => 118,
            .@"lt" => 137,
            .@"gt" => 138,
            .@"plus" => 142,
            .@"slash" => 143,
            .@"percent" => 144,
            .@"arrow" => 65,
            .@"nullish" => 77,
            .@"fat_arrow" => 86,
            .@"plus_assign" => 93,
            .@"minus_assign" => 94,
            .@"star_assign" => 95,
            .@"slash_assign" => 96,
            .@"const_assign" => 97,
            .@"pipe" => 132,
            .@"or_sym" => 133,
            .@"and_sym" => 134,
            .@"eq" => 135,
            .@"ne" => 136,
            .@"le" => 139,
            .@"ge" => 140,
            .@"dotdot" => 141,
            .@"power" => 145,
            else => 2, // error
        };
    }

    fn identToSymbol(self: *Parser, token: Token) u16 {
        const text = self.source[token.pos..][0..token.len];
        if (text.len == 0) return SYM_IDENT;
        if (self.try_ident_as_keyword(token, text)) |sym| return sym;
        return SYM_IDENT;
    }

    fn try_ident_as_keyword(self: *Parser, token: Token, text: []const u8) ?u16 {
        _ = token;
        const state = self.state_stack.getLast();
        if (rip.keyword_as(text)) |id| {
            const id_idx = @intFromEnum(id);
            const sym = keyword_to_symbol[id_idx];
            if (sym != 0 and getAction(state, sym) != 0) {
                self.last_matched_id = @intCast(id_idx);
                return sym;
            }
            const fallback = keyword_fallback_symbol;
            if (fallback != 0 and getAction(state, fallback) != 0) {
                self.last_matched_id = @intCast(id_idx);
                return fallback;
            }
        }
        return null;
    }

    pub fn parseProgram(self: *Parser) !Sexp {
        self.injected_token = SYM_program_START;
        return self.doParse(SYM_program);
    }
    pub fn parseExpr(self: *Parser) !Sexp {
        self.injected_token = SYM_expr_START;
        return self.doParse(SYM_expr);
    }
};

// Symbol IDs
const SYM_program: u16 = 3;
const SYM_program_START: u16 = 120;
const SYM_expr: u16 = 4;
const SYM_expr_START: u16 = 122;
const SYM_IDENT: u16 = 54;

// Mapping from rip.keyword_id to grammar symbol IDs (computed at comptime)
const keyword_to_symbol = blk: {
    var arr: [512]u16 = .{0} ** 512;
    if (@hasField(rip.keyword_id, "NEWLINE")) arr[@intFromEnum(rip.keyword_id.NEWLINE)] = 49;
    if (@hasField(rip.keyword_id, "PUB")) arr[@intFromEnum(rip.keyword_id.PUB)] = 50;
    if (@hasField(rip.keyword_id, "INDENT")) arr[@intFromEnum(rip.keyword_id.INDENT)] = 51;
    if (@hasField(rip.keyword_id, "OUTDENT")) arr[@intFromEnum(rip.keyword_id.OUTDENT)] = 52;
    if (@hasField(rip.keyword_id, "FUN")) arr[@intFromEnum(rip.keyword_id.FUN)] = 53;
    if (@hasField(rip.keyword_id, "IDENT")) arr[@intFromEnum(rip.keyword_id.IDENT)] = 54;
    if (@hasField(rip.keyword_id, "SUB")) arr[@intFromEnum(rip.keyword_id.SUB)] = 55;
    if (@hasField(rip.keyword_id, "USE")) arr[@intFromEnum(rip.keyword_id.USE)] = 56;
    if (@hasField(rip.keyword_id, "ALIAS")) arr[@intFromEnum(rip.keyword_id.ALIAS)] = 57;
    if (@hasField(rip.keyword_id, "TEST")) arr[@intFromEnum(rip.keyword_id.TEST)] = 59;
    if (@hasField(rip.keyword_id, "STRING_DQ")) arr[@intFromEnum(rip.keyword_id.STRING_DQ)] = 60;
    if (@hasField(rip.keyword_id, "ENUM")) arr[@intFromEnum(rip.keyword_id.ENUM)] = 61;
    if (@hasField(rip.keyword_id, "ERROR")) arr[@intFromEnum(rip.keyword_id.ERROR)] = 62;
    if (@hasField(rip.keyword_id, "STRUCT")) arr[@intFromEnum(rip.keyword_id.STRUCT)] = 63;
    if (@hasField(rip.keyword_id, "WHEN")) arr[@intFromEnum(rip.keyword_id.WHEN)] = 75;
    if (@hasField(rip.keyword_id, "ELSE")) arr[@intFromEnum(rip.keyword_id.ELSE)] = 76;
    if (@hasField(rip.keyword_id, "CATCH")) arr[@intFromEnum(rip.keyword_id.CATCH)] = 78;
    if (@hasField(rip.keyword_id, "AS")) arr[@intFromEnum(rip.keyword_id.AS)] = 79;
    if (@hasField(rip.keyword_id, "IF")) arr[@intFromEnum(rip.keyword_id.IF)] = 81;
    if (@hasField(rip.keyword_id, "WHILE")) arr[@intFromEnum(rip.keyword_id.WHILE)] = 82;
    if (@hasField(rip.keyword_id, "FOR")) arr[@intFromEnum(rip.keyword_id.FOR)] = 83;
    if (@hasField(rip.keyword_id, "IN")) arr[@intFromEnum(rip.keyword_id.IN)] = 84;
    if (@hasField(rip.keyword_id, "MATCH")) arr[@intFromEnum(rip.keyword_id.MATCH)] = 85;
    if (@hasField(rip.keyword_id, "RETURN")) arr[@intFromEnum(rip.keyword_id.RETURN)] = 87;
    if (@hasField(rip.keyword_id, "BREAK")) arr[@intFromEnum(rip.keyword_id.BREAK)] = 88;
    if (@hasField(rip.keyword_id, "CONTINUE")) arr[@intFromEnum(rip.keyword_id.CONTINUE)] = 89;
    if (@hasField(rip.keyword_id, "DEFER")) arr[@intFromEnum(rip.keyword_id.DEFER)] = 90;
    if (@hasField(rip.keyword_id, "ERRDEFER")) arr[@intFromEnum(rip.keyword_id.ERRDEFER)] = 91;
    if (@hasField(rip.keyword_id, "COMPTIME")) arr[@intFromEnum(rip.keyword_id.COMPTIME)] = 92;
    if (@hasField(rip.keyword_id, "TRY")) arr[@intFromEnum(rip.keyword_id.TRY)] = 99;
    if (@hasField(rip.keyword_id, "INTEGER")) arr[@intFromEnum(rip.keyword_id.INTEGER)] = 107;
    if (@hasField(rip.keyword_id, "REAL")) arr[@intFromEnum(rip.keyword_id.REAL)] = 108;
    if (@hasField(rip.keyword_id, "STRING_SQ")) arr[@intFromEnum(rip.keyword_id.STRING_SQ)] = 109;
    if (@hasField(rip.keyword_id, "TRUE")) arr[@intFromEnum(rip.keyword_id.TRUE)] = 110;
    if (@hasField(rip.keyword_id, "FALSE")) arr[@intFromEnum(rip.keyword_id.FALSE)] = 111;
    if (@hasField(rip.keyword_id, "UNREACHABLE")) arr[@intFromEnum(rip.keyword_id.UNREACHABLE)] = 112;
    if (@hasField(rip.keyword_id, "UNDEFINED")) arr[@intFromEnum(rip.keyword_id.UNDEFINED)] = 113;
    if (@hasField(rip.keyword_id, "FN")) arr[@intFromEnum(rip.keyword_id.FN)] = 119;
    break :blk arr;
};
const keyword_fallback_symbol: u16 = 0;

const rule_lhs = [_]u16{ 3, 4, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 9, 9, 9, 9, 10, 10, 11, 12, 13, 14, 15, 16, 17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 21, 22, 22, 22, 22, 22, 72, 73, 73, 23, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 24, 24, 25, 26, 26, 27, 27, 27, 28, 28, 28, 29, 29, 30, 30, 31, 32, 32, 32, 33, 33, 34, 34, 35, 36, 37, 38, 39, 40, 40, 40, 40, 40, 41, 42, 42, 42, 42, 43, 43, 43, 101, 102, 102, 43, 43, 43, 105, 106, 106, 44, 44, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 116, 117, 117, 46, 47, 48, 48, 121, 123, 124, 124, 125, 125, 126, 126, 127, 127, 127, 127, 127, 127, 127, 128, 128, 129, 129, 129, 130, 130, 130, 130, 131, 131, 74 };
const rule_len = [_]u8{ 2, 2, 1, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 2, 5, 4, 4, 3, 4, 3, 2, 4, 3, 5, 5, 5, 1, 3, 2, 1, 1, 1, 1, 3, 2, 1, 3, 2, 1, 2, 2, 2, 3, 2, 3, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 3, 3, 5, 3, 1, 3, 4, 5, 5, 3, 3, 5, 5, 7, 5, 1, 3, 2, 3, 2, 2, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 2, 2, 1, 3, 3, 4, 2, 3, 0, 2, 4, 1, 2, 3, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 3, 3, 2, 3, 0, 4, 3, 3, 2, 2, 2, 3, 1, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 1, 3, 3, 1, 3, 3, 3, 1, 3, 1, 1 };

// Parse Table: 299 states × 146 symbols
const NUM_STATES = 299;
const NUM_SYMBOLS = 146;

const sparse = [NUM_STATES][]const i16{
    &.{3,2,120,3},
    &.{4,58,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{1,-1},
    &.{4,82,5,78,6,75,7,71,9,62,10,68,11,66,12,72,13,63,14,74,15,73,16,69,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,50,80,53,67,54,33,55,79,56,65,57,70,59,77,60,39,61,76,62,81,63,64,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{54,83},
    &.{1,-58,49,-58,51,-58,52,-58,64,-58,70,-58,71,-58,76,-58,79,-58,80,-58,104,-58,118,-58},
    &.{1,-125,49,-125,51,-125,52,-125,54,-125,58,-125,60,-125,64,-125,66,-125,68,-125,69,-125,70,-125,71,-125,75,-125,76,-125,77,-125,78,-125,79,-125,80,-125,86,-125,93,-125,94,-125,95,-125,96,-125,97,-125,98,-125,100,-125,103,-125,104,-125,107,-125,108,-125,109,-125,110,-125,111,-125,112,-125,113,-125,114,-125,118,-125,119,-125,132,-125,133,-125,134,-125,135,-125,136,-125,137,-125,138,-125,139,-125,140,-125,141,-125,142,-125,143,-125,144,-125,145,-125},
    &.{1,-67,49,-67,51,-67,52,-67,64,-67,70,-67,71,-67,76,-67,79,-67,80,-67,104,-67,118,-67},
    &.{1,-131,49,-131,51,-131,52,-131,54,-131,58,-131,60,-131,64,-131,66,-131,68,-131,69,-131,70,-131,71,-131,75,-131,76,-131,77,-131,78,-131,79,-131,80,-131,86,-131,93,-131,94,-131,95,-131,96,-131,97,-131,98,-131,100,-131,103,-131,104,-131,107,-131,108,-131,109,-131,110,-131,111,-131,112,-131,113,-131,114,-131,118,-131,119,-131,132,-131,133,-131,134,-131,135,-131,136,-131,137,-131,138,-131,139,-131,140,-131,141,-131,142,-131,143,-131,144,-131,145,-131},
    &.{1,-148,49,-148,51,-148,52,-148,64,-148,70,-148,71,-148,75,-148,76,-148,77,-148,78,-148,79,-148,80,-148,104,-148,118,-148,132,-148,133,84},
    &.{1,-129,49,-129,51,-129,52,-129,54,-129,58,-129,60,-129,64,-129,66,-129,68,-129,69,-129,70,-129,71,-129,75,-129,76,-129,77,-129,78,-129,79,-129,80,-129,86,-129,93,-129,94,-129,95,-129,96,-129,97,-129,98,-129,100,-129,103,-129,104,-129,107,-129,108,-129,109,-129,110,-129,111,-129,112,-129,113,-129,114,-129,118,-129,119,-129,132,-129,133,-129,134,-129,135,-129,136,-129,137,-129,138,-129,139,-129,140,-129,141,-129,142,-129,143,-129,144,-129,145,-129},
    &.{4,85,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{1,-109,45,94,46,27,48,13,49,-109,51,-109,52,-109,54,33,58,87,60,39,64,-109,66,91,68,-109,69,89,70,-109,71,-109,75,-109,76,-109,77,-109,78,-109,79,-109,80,-109,93,95,94,88,95,93,96,86,97,97,98,-109,100,90,101,96,103,92,104,-109,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,118,-109,119,29,132,-109,133,-109,134,-109,135,-109,136,-109,137,-109,138,-109,139,-109,140,-109,141,-109,142,-109,143,-109,144,-109,145,-109},
    &.{1,-135,49,-135,51,-135,52,-135,54,-135,58,-135,60,-135,64,-135,66,-135,68,-135,69,-135,70,-135,71,-135,75,-135,76,-135,77,-135,78,-135,79,-135,80,-135,86,-135,93,-135,94,-135,95,-135,96,-135,97,-135,98,-135,100,-135,103,-135,104,-135,107,-135,108,-135,109,-135,110,-135,111,-135,112,-135,113,-135,114,-135,118,-135,119,-135,132,-135,133,-135,134,-135,135,-135,136,-135,137,-135,138,-135,139,-135,140,-135,141,-135,142,-135,143,-135,144,-135,145,-135},
    &.{1,-71,49,-71,51,-71,52,-71,64,-71,70,-71,71,-71,75,100,76,-71,77,99,78,98,79,-71,80,-71,104,-71,118,-71},
    &.{1,-168,49,-168,51,-168,52,-168,64,-168,68,-168,70,-168,71,-168,75,-168,76,-168,77,-168,78,-168,79,-168,80,-168,98,-168,104,-168,118,-168,132,-168,133,-168,134,-168,135,-168,136,-168,137,-168,138,-168,139,-168,140,-168,141,-168,142,-168,143,-168,144,-168},
    &.{1,-94,4,101,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,49,-94,51,-94,52,-94,54,33,60,39,64,-94,66,50,69,45,70,-94,71,-94,74,14,76,-94,79,-94,80,-94,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,104,-94,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,118,-94,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{1,-64,49,-64,51,-64,52,-64,64,-64,70,-64,71,-64,76,-64,79,-64,80,-64,104,-64,118,-64},
    &.{1,-68,49,-68,51,-68,52,-68,64,-68,70,-68,71,-68,76,-68,79,-68,80,-68,104,-68,118,-68},
    &.{1,-69,49,-69,51,-69,52,-69,64,-69,70,-69,71,-69,76,-69,79,-69,80,-69,104,-69,118,-69},
    &.{1,-161,49,-161,51,-161,52,-161,64,-161,70,-161,71,-161,75,-161,76,-161,77,-161,78,-161,79,-161,80,-161,98,103,104,-161,118,-161,132,-161,133,-161,134,-161,135,-161,136,-161,137,-161,138,-161,139,-161,140,-161,141,102,142,104},
    &.{4,106,24,56,25,18,26,19,27,105,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{1,-130,49,-130,51,-130,52,-130,54,-130,58,-130,60,-130,64,-130,66,-130,68,-130,69,-130,70,-130,71,-130,75,-130,76,-130,77,-130,78,-130,79,-130,80,-130,86,-130,93,-130,94,-130,95,-130,96,-130,97,-130,98,-130,100,-130,103,-130,104,-130,107,-130,108,-130,109,-130,110,-130,111,-130,112,-130,113,-130,114,-130,118,-130,119,-130,132,-130,133,-130,134,-130,135,-130,136,-130,137,-130,138,-130,139,-130,140,-130,141,-130,142,-130,143,-130,144,-130,145,-130},
    &.{4,107,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{1,-171,49,-171,51,-171,52,-171,64,-171,70,-171,71,-171,75,-171,76,-171,77,-171,78,-171,79,-171,80,-171,104,-171,118,-171,132,108},
    &.{1,-118,49,-118,51,-118,52,-118,54,-118,58,-118,60,-118,64,-118,66,-118,68,-118,69,-118,70,-118,71,-118,75,-118,76,-118,77,-118,78,-118,79,-118,80,-118,93,-118,94,-118,95,-118,96,-118,97,-118,98,-118,100,-118,103,-118,104,-118,107,-118,108,-118,109,-118,110,-118,111,-118,112,-118,113,-118,114,-118,118,-118,119,-118,132,-118,133,-118,134,-118,135,-118,136,-118,137,-118,138,-118,139,-118,140,-118,141,-118,142,-118,143,-118,144,-118,145,-118},
    &.{1,-66,49,-66,51,-66,52,-66,64,-66,70,-66,71,-66,76,-66,79,-66,80,-66,104,-66,118,-66},
    &.{1,-134,49,-134,51,-134,52,-134,54,-134,58,-134,60,-134,64,-134,66,-134,68,-134,69,-134,70,-134,71,-134,75,-134,76,-134,77,-134,78,-134,79,-134,80,-134,86,-134,93,-134,94,-134,95,-134,96,-134,97,-134,98,-134,100,-134,103,-134,104,-134,107,-134,108,-134,109,-134,110,-134,111,-134,112,-134,113,-134,114,-134,118,-134,119,-134,132,-134,133,-134,134,-134,135,-134,136,-134,137,-134,138,-134,139,-134,140,-134,141,-134,142,-134,143,-134,144,-134,145,-134},
    &.{4,106,24,56,25,18,26,19,27,109,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{8,113,20,112,23,115,51,111,54,114,72,110},
    &.{42,117,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29},
    &.{1,-159,49,-159,51,-159,52,-159,64,-159,70,-159,71,-159,75,-159,76,-159,77,-159,78,-159,79,-159,80,-159,104,-159,118,-159,132,-159,133,-159,134,-159,135,119,136,122,137,121,138,120,139,118,140,123},
    &.{1,-59,49,-59,51,-59,52,-59,64,-59,70,-59,71,-59,76,-59,79,-59,80,-59,104,-59,118,-59},
    &.{1,-124,49,-124,51,-124,52,-124,54,-124,58,-124,60,-124,64,-124,66,-124,68,-124,69,-124,70,-124,71,-124,75,-124,76,-124,77,-124,78,-124,79,-124,80,-124,86,-124,93,-124,94,-124,95,-124,96,-124,97,-124,98,-124,100,-124,103,-124,104,-124,107,-124,108,-124,109,-124,110,-124,111,-124,112,-124,113,-124,114,-124,115,124,118,-124,119,-124,132,-124,133,-124,134,-124,135,-124,136,-124,137,-124,138,-124,139,-124,140,-124,141,-124,142,-124,143,-124,144,-124,145,-124},
    &.{1,-150,49,-150,51,-150,52,-150,64,-150,70,-150,71,-150,75,-150,76,-150,77,-150,78,-150,79,-150,80,-150,104,-150,118,-150,132,-150,133,-150,134,125},
    &.{1,-127,49,-127,51,-127,52,-127,54,-127,58,-127,60,-127,64,-127,66,-127,68,-127,69,-127,70,-127,71,-127,75,-127,76,-127,77,-127,78,-127,79,-127,80,-127,86,-127,93,-127,94,-127,95,-127,96,-127,97,-127,98,-127,100,-127,103,-127,104,-127,107,-127,108,-127,109,-127,110,-127,111,-127,112,-127,113,-127,114,-127,118,-127,119,-127,132,-127,133,-127,134,-127,135,-127,136,-127,137,-127,138,-127,139,-127,140,-127,141,-127,142,-127,143,-127,144,-127,145,-127},
    &.{1,-61,49,-61,51,-61,52,-61,64,-61,70,-61,71,-61,76,-61,79,-61,80,-61,104,-61,118,-61},
    &.{1,-62,49,-62,51,-62,52,-62,64,-62,70,-62,71,-62,76,-62,79,-62,80,-62,104,-62,118,-62},
    &.{1,-96,49,-96,51,-96,52,-96,64,-96,70,-96,71,-96,76,-96,79,-96,80,-96,104,-96,118,-96},
    &.{1,-128,49,-128,51,-128,52,-128,54,-128,58,-128,60,-128,64,-128,66,-128,68,-128,69,-128,70,-128,71,-128,75,-128,76,-128,77,-128,78,-128,79,-128,80,-128,86,-128,93,-128,94,-128,95,-128,96,-128,97,-128,98,-128,100,-128,103,-128,104,-128,107,-128,108,-128,109,-128,110,-128,111,-128,112,-128,113,-128,114,-128,118,-128,119,-128,132,-128,133,-128,134,-128,135,-128,136,-128,137,-128,138,-128,139,-128,140,-128,141,-128,142,-128,143,-128,144,-128,145,-128},
    &.{1,-152,49,-152,51,-152,52,-152,64,-152,70,-152,71,-152,75,-152,76,-152,77,-152,78,-152,79,-152,80,-152,104,-152,118,-152,132,-152,133,-152,134,-152},
    &.{1,-65,49,-65,51,-65,52,-65,64,-65,70,-65,71,-65,76,-65,79,-65,80,-65,104,-65,118,-65},
    &.{1,-95,49,-95,51,-95,52,-95,64,-95,70,-95,71,-95,76,-95,79,-95,80,-95,104,-95,118,-95},
    &.{4,126,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{1,-126,49,-126,51,-126,52,-126,54,-126,58,-126,60,-126,64,-126,66,-126,68,-126,69,-126,70,-126,71,-126,75,-126,76,-126,77,-126,78,-126,79,-126,80,-126,86,-126,93,-126,94,-126,95,-126,96,-126,97,-126,98,-126,100,-126,103,-126,104,-126,107,-126,108,-126,109,-126,110,-126,111,-126,112,-126,113,-126,114,-126,118,-126,119,-126,132,-126,133,-126,134,-126,135,-126,136,-126,137,-126,138,-126,139,-126,140,-126,141,-126,142,-126,143,-126,144,-126,145,-126},
    &.{4,128,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,44,129,45,25,46,27,48,13,54,33,60,39,66,50,69,45,70,-123,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,104,-123,105,127,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{1,-170,49,-170,51,-170,52,-170,64,-170,68,-170,70,-170,71,-170,75,-170,76,-170,77,-170,78,-170,79,-170,80,-170,98,-170,104,-170,118,-170,132,-170,133,-170,134,-170,135,-170,136,-170,137,-170,138,-170,139,-170,140,-170,141,-170,142,-170,143,-170,144,-170,145,130},
    &.{1,-56,49,-56,51,-56,52,-56,64,-56,70,-56,71,-56,76,-56,79,-56,80,-56,104,-56,118,-56},
    &.{1,-60,49,-60,51,-60,52,-60,64,-60,70,-60,71,-60,76,-60,79,-60,80,-60,104,-60,118,-60},
    &.{54,131},
    &.{42,132,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29},
    &.{1,-132,49,-132,51,-132,52,-132,54,-132,58,-132,60,-132,64,-132,66,-132,68,-132,69,-132,70,-132,71,-132,75,-132,76,-132,77,-132,78,-132,79,-132,80,-132,86,-132,93,-132,94,-132,95,-132,96,-132,97,-132,98,-132,100,-132,103,-132,104,-132,107,-132,108,-132,109,-132,110,-132,111,-132,112,-132,113,-132,114,-132,118,-132,119,-132,132,-132,133,-132,134,-132,135,-132,136,-132,137,-132,138,-132,139,-132,140,-132,141,-132,142,-132,143,-132,144,-132,145,-132},
    &.{4,133,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{4,134,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{1,-63,49,-63,51,-63,52,-63,64,-63,70,-63,71,-63,76,-63,79,-63,80,-63,104,-63,118,-63},
    &.{1,-57,49,-57,51,-57,52,-57,64,-57,70,-57,71,-57,76,-57,79,-57,80,-57,104,-57,118,-57},
    &.{1,-70,49,-70,51,-70,52,-70,64,-70,70,-70,71,-70,76,-70,79,-70,80,-70,104,-70,118,-70},
    &.{42,135,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29},
    &.{1,-1},
    &.{4,137,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{1,-164,49,-164,51,-164,52,-164,64,-164,68,138,70,-164,71,-164,75,-164,76,-164,77,-164,78,-164,79,-164,80,-164,98,-164,104,-164,118,-164,132,-164,133,-164,134,-164,135,-164,136,-164,137,-164,138,-164,139,-164,140,-164,141,-164,142,-164,143,140,144,139},
    &.{1,-1},
    &.{1,-9,49,-9,52,-9},
    &.{1,-15,49,-15,52,-15},
    &.{54,141},
    &.{54,142},
    &.{1,-7,49,-7,52,-7},
    &.{54,143},
    &.{1,-10,49,-10,52,-10},
    &.{1,-12,49,-12,52,-12},
    &.{54,144},
    &.{1,-8,49,-8,52,-8},
    &.{1,-14,49,-14,52,-14},
    &.{1,-13,49,-13,52,-13},
    &.{1,-11,49,-11,52,-11},
    &.{1,-4,49,-4,52,-4},
    &.{54,145},
    &.{60,146},
    &.{1,-2,49,147},
    &.{54,148},
    &.{9,149,10,150,14,152,16,151,53,67,55,79,61,76,63,64},
    &.{54,153},
    &.{1,-16,49,-16,52,-16},
    &.{71,154,84,155},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,126,156,127,40,128,31,129,20,130,60,131,15},
    &.{1,-97,49,-97,51,-97,52,-97,64,-97,70,-97,71,-97,76,-97,79,-97,80,-97,104,-97,118,-97},
    &.{4,157,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{4,158,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{4,159,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{4,160,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,44,129,45,25,46,27,48,13,54,33,60,39,66,50,69,45,70,-123,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,104,-123,105,127,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{54,161},
    &.{45,162,46,27,48,13,54,33,60,39,69,45,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29},
    &.{4,163,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,44,164,45,25,46,27,48,13,54,33,60,39,66,50,69,45,70,-123,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,104,-123,105,127,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{4,165,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{1,-115,49,-115,51,-115,52,-115,54,-115,58,-115,60,-115,64,-115,66,-115,68,-115,69,-115,70,-115,71,167,75,-115,76,-115,77,-115,78,-115,79,-115,80,-115,93,-115,94,-115,95,-115,96,-115,97,-115,98,-115,100,-115,102,166,103,-115,104,-115,107,-115,108,-115,109,-115,110,-115,111,-115,112,-115,113,-115,114,-115,118,-115,119,-115,132,-115,133,-115,134,-115,135,-115,136,-115,137,-115,138,-115,139,-115,140,-115,141,-115,142,-115,143,-115,144,-115,145,-115},
    &.{4,168,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{1,-116,49,-116,51,-116,52,-116,54,-116,58,-116,60,-116,64,-116,66,-116,68,-116,69,-116,70,-116,71,-116,75,-116,76,-116,77,-116,78,-116,79,-116,80,-116,93,-116,94,-116,95,-116,96,-116,97,-116,98,-116,100,-116,103,-116,104,-116,107,-116,108,-116,109,-116,110,-116,111,-116,112,-116,113,-116,114,-116,118,-116,119,-116,132,-116,133,-116,134,-116,135,-116,136,-116,137,-116,138,-116,139,-116,140,-116,141,-116,142,-116,143,-116,144,-116,145,-116},
    &.{4,169,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{4,171,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,79,170,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{4,172,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{4,173,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{1,-93,49,-93,51,-93,52,-93,64,-93,70,-93,71,-93,76,-93,79,-93,80,-93,104,-93,118,-93},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,129,174,130,60,131,15},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,130,175,131,15},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,130,176,131,15},
    &.{8,177,51,111},
    &.{51,-77,64,-77,79,178,80,179},
    &.{1,-3,49,-3,51,-3,52,-3,64,-3,70,-3,71,-3,76,-3,79,-3,80,-3,104,-3,118,-3},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,125,180,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{8,181,51,111,64,182},
    &.{51,-55,65,-55},
    &.{4,82,5,183,6,75,7,71,9,62,10,68,11,66,12,72,13,63,14,74,15,73,16,69,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,50,80,52,184,53,67,54,33,55,79,56,65,57,70,59,77,60,39,61,76,62,81,63,64,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{51,-54,65,-54,71,186,73,185},
    &.{1,-144,49,-144,51,-144,52,-144,54,-144,58,-144,60,-144,64,-144,66,-144,68,-144,69,-144,70,-144,71,-144,75,-144,76,-144,77,-144,78,-144,79,-144,80,-144,86,-144,93,-144,94,-144,95,-144,96,-144,97,-144,98,-144,100,-144,103,-144,104,-144,107,-144,108,-144,109,-144,110,-144,111,-144,112,-144,113,-144,114,-144,118,-144,119,-144,132,-144,133,-144,134,-144,135,-144,136,-144,137,-144,138,-144,139,-144,140,-144,141,-144,142,-144,143,-144,144,-144,145,-144},
    &.{49,-44,51,-44,52,-44,64,187,65,-44,71,-44},
    &.{8,188,51,111},
    &.{1,-109,45,94,46,27,48,13,49,-109,51,-109,52,-109,54,33,60,39,64,-109,66,91,68,-109,69,89,70,-109,71,-109,75,-109,76,-109,77,-109,78,-109,79,-109,80,-109,98,-109,100,90,101,96,103,92,104,-109,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,118,-109,119,29,132,-109,133,-109,134,-109,135,-109,136,-109,137,-109,138,-109,139,-109,140,-109,141,-109,142,-109,143,-109,144,-109,145,-109},
    &.{1,-108,49,-108,51,-108,52,-108,64,-108,68,-108,70,-108,71,-108,75,-108,76,-108,77,-108,78,-108,79,-108,80,-108,98,-108,104,-108,118,-108,132,-108,133,-108,134,-108,135,-108,136,-108,137,-108,138,-108,139,-108,140,-108,141,-108,142,-108,143,-108,144,-108,145,-108},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,128,189,129,20,130,60,131,15},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,128,190,129,20,130,60,131,15},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,128,191,129,20,130,60,131,15},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,128,192,129,20,130,60,131,15},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,128,193,129,20,130,60,131,15},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,128,194,129,20,130,60,131,15},
    &.{47,195,54,196,116,197},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,127,198,128,31,129,20,130,60,131,15},
    &.{1,-98,49,-98,51,-98,52,-98,64,-98,70,-98,71,-98,76,-98,79,-98,80,-98,104,-98,118,-98},
    &.{70,-122,104,-122},
    &.{70,-121,71,199,104,-121,106,200},
    &.{70,201},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,131,202},
    &.{103,203},
    &.{1,-106,49,-106,51,-106,52,-106,64,-106,68,-106,70,-106,71,-106,75,-106,76,-106,77,-106,78,-106,79,-106,80,-106,98,-106,104,-106,118,-106,132,-106,133,-106,134,-106,135,-106,136,-106,137,-106,138,-106,139,-106,140,-106,141,-106,142,-106,143,-106,144,-106,145,-106},
    &.{51,204},
    &.{104,205},
    &.{1,-107,49,-107,51,-107,52,-107,64,-107,68,-107,70,-107,71,-107,75,-107,76,-107,77,-107,78,-107,79,-107,80,-107,98,-107,104,-107,118,-107,132,-107,133,-107,134,-107,135,-107,136,-107,137,-107,138,-107,139,-107,140,-107,141,-107,142,-107,143,-107,144,-107,145,-107},
    &.{1,-1},
    &.{1,-99,49,-99,51,-99,52,-99,64,-99,70,-99,71,-99,76,-99,79,-99,80,-99,104,-99,118,-99},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,131,206},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,131,207},
    &.{42,46,43,116,45,25,46,27,48,13,54,33,60,39,66,50,69,45,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,131,208},
    &.{51,209},
    &.{1,-29,49,-29,52,-29},
    &.{8,210,20,112,21,213,23,212,51,111,54,114,65,211,72,110},
    &.{58,214},
    &.{51,215},
    &.{8,216,51,111},
    &.{1,-6,4,82,6,217,7,71,9,62,10,68,11,66,12,72,13,63,14,74,15,73,16,69,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,49,-6,50,80,52,-6,53,67,54,33,55,79,56,65,57,70,59,77,60,39,61,76,62,81,63,64,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{8,218,20,112,23,219,51,111,54,114,72,110},
    &.{1,-17,49,-17,52,-17},
    &.{1,-18,49,-18,52,-18},
    &.{1,-20,49,-20,52,-20},
    &.{1,-19,49,-19,52,-19},
    &.{51,220},
    &.{54,221},
    &.{4,222,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{1,-149,49,-149,51,-149,52,-149,64,-149,70,-149,71,-149,75,-149,76,-149,77,-149,78,-149,79,-149,80,-149,104,-149,118,-149,132,-149,133,-149,134,125},
    &.{1,-104,49,-104,51,-104,52,-104,64,-104,70,-104,71,-104,76,-104,79,-104,80,-104,104,-104,118,-104},
    &.{1,-100,49,-100,51,-100,52,-100,64,-100,70,-100,71,-100,76,-100,79,-100,80,-100,104,-100,118,-100},
    &.{1,-102,49,-102,51,-102,52,-102,64,-102,70,-102,71,-102,76,-102,79,-102,80,-102,104,-102,118,-102},
    &.{70,223,71,199,104,-121,106,200},
    &.{1,-111,49,-111,51,-111,52,-111,54,-111,58,-111,60,-111,64,-111,66,-111,68,-111,69,-111,70,-111,71,-111,75,-111,76,-111,77,-111,78,-111,79,-111,80,-111,93,-111,94,-111,95,-111,96,-111,97,-111,98,-111,100,-111,103,-111,104,-111,107,-111,108,-111,109,-111,110,-111,111,-111,112,-111,113,-111,114,-111,118,-111,119,-111,132,-111,133,-111,134,-111,135,-111,136,-111,137,-111,138,-111,139,-111,140,-111,141,-111,142,-111,143,-111,144,-111,145,-111},
    &.{1,-110,49,-110,51,-110,52,-110,54,-110,58,-110,60,-110,64,-110,66,-110,68,-110,69,-110,70,-110,71,-110,75,-110,76,-110,77,-110,78,-110,79,-110,80,-110,93,-110,94,-110,95,-110,96,-110,97,-110,98,-110,100,-110,103,-110,104,-110,107,-110,108,-110,109,-110,110,-110,111,-110,112,-110,113,-110,114,-110,118,-110,119,-110,132,-110,133,-110,134,-110,135,-110,136,-110,137,-110,138,-110,139,-110,140,-110,141,-110,142,-110,143,-110,144,-110,145,-110},
    &.{70,-121,71,199,104,205,106,200},
    &.{104,224},
    &.{1,-103,49,-103,51,-103,52,-103,64,-103,70,-103,71,-103,76,-103,79,-103,80,-103,104,-103,118,-103},
    &.{1,-113,49,-113,51,-113,52,-113,54,-113,58,-113,60,-113,64,-113,66,-113,68,-113,69,-113,70,-113,71,-113,75,-113,76,-113,77,-113,78,-113,79,-113,80,-113,93,-113,94,-113,95,-113,96,-113,97,-113,98,-113,100,-113,103,-113,104,-113,107,-113,108,-113,109,-113,110,-113,111,-113,112,-113,113,-113,114,-113,118,-113,119,-113,132,-113,133,-113,134,-113,135,-113,136,-113,137,-113,138,-113,139,-113,140,-113,141,-113,142,-113,143,-113,144,-113,145,-113},
    &.{45,225,46,27,48,13,54,33,60,39,69,45,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29},
    &.{1,-101,49,-101,51,-101,52,-101,64,-101,70,-101,71,-101,76,-101,79,-101,80,-101,104,-101,118,-101},
    &.{1,-105,49,-105,51,-105,52,-105,64,-105,70,-105,71,-105,76,-105,79,-105,80,-105,104,-105,118,-105},
    &.{54,226},
    &.{1,-76,49,-76,51,-76,52,-76,64,-76,70,-76,71,-76,76,-76,79,-76,80,-76,104,-76,118,-76},
    &.{1,-74,49,-74,51,-74,52,-74,64,-74,70,-74,71,-74,76,-74,79,-74,80,-74,104,-74,118,-74},
    &.{1,-73,49,-73,51,-73,52,-73,64,-73,70,-73,71,-73,76,227,79,-73,80,-73,104,-73,118,-73},
    &.{1,-160,49,-160,51,-160,52,-160,64,-160,70,-160,71,-160,75,-160,76,-160,77,-160,78,-160,79,-160,80,-160,98,103,104,-160,118,-160,132,-160,133,-160,134,-160,135,-160,136,-160,137,-160,138,-160,139,-160,140,-160,142,104},
    &.{1,-163,49,-163,51,-163,52,-163,64,-163,68,138,70,-163,71,-163,75,-163,76,-163,77,-163,78,-163,79,-163,80,-163,98,-163,104,-163,118,-163,132,-163,133,-163,134,-163,135,-163,136,-163,137,-163,138,-163,139,-163,140,-163,141,-163,142,-163,143,140,144,139},
    &.{1,-162,49,-162,51,-162,52,-162,64,-162,68,138,70,-162,71,-162,75,-162,76,-162,77,-162,78,-162,79,-162,80,-162,98,-162,104,-162,118,-162,132,-162,133,-162,134,-162,135,-162,136,-162,137,-162,138,-162,139,-162,140,-162,141,-162,142,-162,143,140,144,139},
    &.{1,-82,49,-82,51,-82,52,-82,64,-82,70,-82,71,-82,76,228,79,-82,80,-82,104,-82,118,-82},
    &.{54,229},
    &.{54,230},
    &.{1,-147,49,-147,51,-147,52,-147,64,-147,70,-147,71,-147,75,-147,76,-147,77,-147,78,-147,79,-147,80,-147,104,-147,118,-147,132,-147,133,84},
    &.{1,-83,49,-83,51,-83,52,-83,64,-83,70,-83,71,-83,76,-83,79,-83,80,-83,104,-83,118,-83},
    &.{4,231,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{49,147,52,232},
    &.{1,-22,49,-22,51,-22,52,-22,54,-22,58,-22,60,-22,64,-22,66,-22,68,-22,69,-22,70,-22,71,-22,75,-22,76,-22,77,-22,78,-22,79,-22,80,-22,86,-22,93,-22,94,-22,95,-22,96,-22,97,-22,98,-22,100,-22,103,-22,104,-22,107,-22,108,-22,109,-22,110,-22,111,-22,112,-22,113,-22,114,-22,118,-22,119,-22,132,-22,133,-22,134,-22,135,-22,136,-22,137,-22,138,-22,139,-22,140,-22,141,-22,142,-22,143,-22,144,-22,145,-22},
    &.{51,-52,65,-52},
    &.{20,233,54,114},
    &.{22,237,54,235,66,238,67,234,68,236,69,239},
    &.{1,-143,49,-143,51,-143,52,-143,54,-143,58,-143,60,-143,64,-143,66,-143,68,-143,69,-143,70,-143,71,-143,75,-143,76,-143,77,-143,78,-143,79,-143,80,-143,86,-143,93,-143,94,-143,95,-143,96,-143,97,-143,98,-143,100,-143,103,-143,104,-143,107,-143,108,-143,109,-143,110,-143,111,-143,112,-143,113,-143,114,-143,118,-143,119,-143,132,-143,133,-143,134,-143,135,-143,136,-143,137,-143,138,-143,139,-143,140,-143,141,-143,142,-143,143,-143,144,-143,145,-143},
    &.{1,-157,49,-157,51,-157,52,-157,64,-157,70,-157,71,-157,75,-157,76,-157,77,-157,78,-157,79,-157,80,-157,104,-157,118,-157,132,-157,133,-157,134,-157},
    &.{1,-153,49,-153,51,-153,52,-153,64,-153,70,-153,71,-153,75,-153,76,-153,77,-153,78,-153,79,-153,80,-153,104,-153,118,-153,132,-153,133,-153,134,-153},
    &.{1,-156,49,-156,51,-156,52,-156,64,-156,70,-156,71,-156,75,-156,76,-156,77,-156,78,-156,79,-156,80,-156,104,-156,118,-156,132,-156,133,-156,134,-156},
    &.{1,-155,49,-155,51,-155,52,-155,64,-155,70,-155,71,-155,75,-155,76,-155,77,-155,78,-155,79,-155,80,-155,104,-155,118,-155,132,-155,133,-155,134,-155},
    &.{1,-154,49,-154,51,-154,52,-154,64,-154,70,-154,71,-154,75,-154,76,-154,77,-154,78,-154,79,-154,80,-154,104,-154,118,-154,132,-154,133,-154,134,-154},
    &.{1,-158,49,-158,51,-158,52,-158,64,-158,70,-158,71,-158,75,-158,76,-158,77,-158,78,-158,79,-158,80,-158,104,-158,118,-158,132,-158,133,-158,134,-158},
    &.{71,241,117,240,118,-140},
    &.{64,242},
    &.{118,243},
    &.{1,-151,49,-151,51,-151,52,-151,64,-151,70,-151,71,-151,75,-151,76,-151,77,-151,78,-151,79,-151,80,-151,104,-151,118,-151,132,-151,133,-151,134,-151},
    &.{4,244,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{70,-119,104,-119},
    &.{1,-136,49,-136,51,-136,52,-136,54,-136,58,-136,60,-136,64,-136,66,-136,68,-136,69,-136,70,-136,71,-136,75,-136,76,-136,77,-136,78,-136,79,-136,80,-136,86,-136,93,-136,94,-136,95,-136,96,-136,97,-136,98,-136,100,-136,103,-136,104,-136,107,-136,108,-136,109,-136,110,-136,111,-136,112,-136,113,-136,114,-136,118,-136,119,-136,132,-136,133,-136,134,-136,135,-136,136,-136,137,-136,138,-136,139,-136,140,-136,141,-136,142,-136,143,-136,144,-136,145,-136},
    &.{1,-169,49,-169,51,-169,52,-169,64,-169,68,-169,70,-169,71,-169,75,-169,76,-169,77,-169,78,-169,79,-169,80,-169,98,-169,104,-169,118,-169,132,-169,133,-169,134,-169,135,-169,136,-169,137,-169,138,-169,139,-169,140,-169,141,-169,142,-169,143,-169,144,-169},
    &.{4,128,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,44,245,45,25,46,27,48,13,54,33,60,39,66,50,69,45,70,-123,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,104,-123,105,127,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{32,248,33,247,45,246,46,27,48,13,54,33,60,39,69,45,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29},
    &.{1,-137,49,-137,51,-137,52,-137,54,-137,58,-137,60,-137,64,-137,66,-137,68,-137,69,-137,70,-137,71,-137,75,-137,76,-137,77,-137,78,-137,79,-137,80,-137,86,-137,93,-137,94,-137,95,-137,96,-137,97,-137,98,-137,100,-137,103,-137,104,-137,107,-137,108,-137,109,-137,110,-137,111,-137,112,-137,113,-137,114,-137,118,-137,119,-137,132,-137,133,-137,134,-137,135,-137,136,-137,137,-137,138,-137,139,-137,140,-137,141,-137,142,-137,143,-137,144,-137,145,-137},
    &.{1,-165,49,-165,51,-165,52,-165,64,-165,68,-165,70,-165,71,-165,75,-165,76,-165,77,-165,78,-165,79,-165,80,-165,98,-165,104,-165,118,-165,132,-165,133,-165,134,-165,135,-165,136,-165,137,-165,138,-165,139,-165,140,-165,141,-165,142,-165,143,-165,144,-165},
    &.{1,-167,49,-167,51,-167,52,-167,64,-167,68,-167,70,-167,71,-167,75,-167,76,-167,77,-167,78,-167,79,-167,80,-167,98,-167,104,-167,118,-167,132,-167,133,-167,134,-167,135,-167,136,-167,137,-167,138,-167,139,-167,140,-167,141,-167,142,-167,143,-167,144,-167},
    &.{1,-166,49,-166,51,-166,52,-166,64,-166,68,-166,70,-166,71,-166,75,-166,76,-166,77,-166,78,-166,79,-166,80,-166,98,-166,104,-166,118,-166,132,-166,133,-166,134,-166,135,-166,136,-166,137,-166,138,-166,139,-166,140,-166,141,-166,142,-166,143,-166,144,-166},
    &.{9,251,10,250,17,253,18,249,20,252,53,67,54,114,55,79},
    &.{1,-26,49,-26,52,-26},
    &.{22,254,54,235,66,238,67,234,68,236,69,239},
    &.{8,255,21,256,51,111,65,211},
    &.{8,257,51,111},
    &.{22,258,54,235,66,238,67,234,68,236,69,239},
    &.{19,260,54,259},
    &.{1,-31,49,-31,52,-31},
    &.{1,-5,49,-5,52,-5},
    &.{1,-28,49,-28,52,-28},
    &.{8,261,51,111},
    &.{19,262,54,259},
    &.{84,263},
    &.{8,264,51,111},
    &.{1,-112,49,-112,51,-112,52,-112,54,-112,58,-112,60,-112,64,-112,66,-112,68,-112,69,-112,70,-112,71,-112,75,-112,76,-112,77,-112,78,-112,79,-112,80,-112,93,-112,94,-112,95,-112,96,-112,97,-112,98,-112,100,-112,103,-112,104,-112,107,-112,108,-112,109,-112,110,-112,111,-112,112,-112,113,-112,114,-112,118,-112,119,-112,132,-112,133,-112,134,-112,135,-112,136,-112,137,-112,138,-112,139,-112,140,-112,141,-112,142,-112,143,-112,144,-112,145,-112},
    &.{1,-117,49,-117,51,-117,52,-117,54,-117,58,-117,60,-117,64,-117,66,-117,68,-117,69,-117,70,-117,71,-117,75,-117,76,-117,77,-117,78,-117,79,-117,80,-117,93,-117,94,-117,95,-117,96,-117,97,-117,98,-117,100,-117,103,-117,104,-117,107,-117,108,-117,109,-117,110,-117,111,-117,112,-117,113,-117,114,-117,118,-117,119,-117,132,-117,133,-117,134,-117,135,-117,136,-117,137,-117,138,-117,139,-117,140,-117,141,-117,142,-117,143,-117,144,-117,145,-117},
    &.{1,-115,49,-115,51,-115,52,-115,54,-115,58,-115,60,-115,64,-115,66,-115,68,-115,69,-115,70,-115,71,167,75,-115,76,-115,77,-115,78,-115,79,-115,80,-115,93,-115,94,-115,95,-115,96,-115,97,-115,98,-115,100,-115,102,265,103,-115,104,-115,107,-115,108,-115,109,-115,110,-115,111,-115,112,-115,113,-115,114,-115,118,-115,119,-115,132,-115,133,-115,134,-115,135,-115,136,-115,137,-115,138,-115,139,-115,140,-115,141,-115,142,-115,143,-115,144,-115,145,-115},
    &.{4,266,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{4,267,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{8,269,28,268,51,111,81,21},
    &.{51,-78,64,-78},
    &.{80,270},
    &.{8,271,51,111},
    &.{1,-21,49,-21,51,-21,52,-21,54,-21,58,-21,60,-21,64,-21,66,-21,68,-21,69,-21,70,-21,71,-21,75,-21,76,-21,77,-21,78,-21,79,-21,80,-21,86,-21,93,-21,94,-21,95,-21,96,-21,97,-21,98,-21,100,-21,103,-21,104,-21,107,-21,108,-21,109,-21,110,-21,111,-21,112,-21,113,-21,114,-21,118,-21,119,-21,132,-21,133,-21,134,-21,135,-21,136,-21,137,-21,138,-21,139,-21,140,-21,141,-21,142,-21,143,-21,144,-21,145,-21},
    &.{51,-54,65,-54,71,186,73,272},
    &.{22,273,54,235,66,238,67,234,68,236,69,239},
    &.{1,-47,49,-47,51,-47,52,-47,65,-47,71,-47},
    &.{22,274,54,235,66,238,67,234,68,236,69,239},
    &.{49,-45,51,-45,52,-45,65,-45,71,-45},
    &.{22,275,54,235,66,238,67,234,68,236,69,239},
    &.{70,276},
    &.{118,-138},
    &.{47,277,54,196},
    &.{4,278,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{1,-141,49,-141,51,-141,52,-141,54,-141,58,-141,60,-141,64,-141,66,-141,68,-141,69,-141,70,-141,71,-141,75,-141,76,-141,77,-141,78,-141,79,-141,80,-141,86,-141,93,-141,94,-141,95,-141,96,-141,97,-141,98,-141,100,-141,103,-141,104,-141,107,-141,108,-141,109,-141,110,-141,111,-141,112,-141,113,-141,114,-141,118,-141,119,-141,132,-141,133,-141,134,-141,135,-141,136,-141,137,-141,138,-141,139,-141,140,-141,141,-141,142,-141,143,-141,144,-141,145,-141},
    &.{70,-121,71,199,104,-121,106,279},
    &.{104,280},
    &.{8,281,51,111,86,282},
    &.{49,-88,52,-88},
    &.{49,283,52,284},
    &.{49,-35,52,-35},
    &.{49,-40,52,-40},
    &.{49,-39,52,-39},
    &.{49,-38,52,-38},
    &.{49,285,52,286},
    &.{51,-46},
    &.{1,-24,49,-24,52,-24},
    &.{8,287,51,111},
    &.{1,-25,49,-25,52,-25},
    &.{1,-30,49,-30,52,-30},
    &.{49,-41,52,-41},
    &.{49,288,52,289},
    &.{1,-27,49,-27,52,-27},
    &.{49,288,52,290},
    &.{4,291,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{1,-85,49,-85,51,-85,52,-85,64,-85,70,-85,71,-85,76,-85,79,-85,80,-85,104,-85,118,-85},
    &.{1,-114,49,-114,51,-114,52,-114,54,-114,58,-114,60,-114,64,-114,66,-114,68,-114,69,-114,70,-114,71,-114,75,-114,76,-114,77,-114,78,-114,79,-114,80,-114,93,-114,94,-114,95,-114,96,-114,97,-114,98,-114,100,-114,103,-114,104,-114,107,-114,108,-114,109,-114,110,-114,111,-114,112,-114,113,-114,114,-114,118,-114,119,-114,132,-114,133,-114,134,-114,135,-114,136,-114,137,-114,138,-114,139,-114,140,-114,141,-114,142,-114,143,-114,144,-114,145,-114},
    &.{1,-75,49,-75,51,-75,52,-75,64,-75,70,-75,71,-75,76,-75,79,-75,80,-75,104,-75,118,-75},
    &.{1,-72,49,-72,51,-72,52,-72,64,-72,70,-72,71,-72,76,-72,79,-72,80,-72,104,-72,118,-72},
    &.{1,-80,49,-80,51,-80,52,-80,64,-80,70,-80,71,-80,76,-80,79,-80,80,-80,104,-80,118,-80},
    &.{1,-81,49,-81,51,-81,52,-81,64,-81,70,-81,71,-81,76,-81,79,-81,80,-81,104,-81,118,-81},
    &.{51,-79,64,-79},
    &.{1,-84,49,-84,51,-84,52,-84,64,-84,70,-84,71,-84,76,-84,79,-84,80,-84,104,-84,118,-84},
    &.{51,-53,65,-53},
    &.{1,-49,49,-49,51,-49,52,-49,65,-49,71,-49},
    &.{1,-50,49,-50,51,-50,52,-50,65,-50,71,-50},
    &.{1,-48,49,-48,51,-48,52,-48,65,-48,71,-48},
    &.{22,292,54,235,66,238,67,234,68,236,69,239},
    &.{71,241,117,293,118,-140},
    &.{71,-142,118,-142},
    &.{70,-120,104,-120},
    &.{1,-133,49,-133,51,-133,52,-133,54,-133,58,-133,60,-133,64,-133,66,-133,68,-133,69,-133,70,-133,71,-133,75,-133,76,-133,77,-133,78,-133,79,-133,80,-133,86,-133,93,-133,94,-133,95,-133,96,-133,97,-133,98,-133,100,-133,103,-133,104,-133,107,-133,108,-133,109,-133,110,-133,111,-133,112,-133,113,-133,114,-133,118,-133,119,-133,132,-133,133,-133,134,-133,135,-133,136,-133,137,-133,138,-133,139,-133,140,-133,141,-133,142,-133,143,-133,144,-133,145,-133},
    &.{49,-92,52,-92},
    &.{4,294,24,56,25,18,26,19,28,47,29,55,30,5,31,32,34,48,35,36,36,37,37,54,38,17,39,41,40,26,41,7,42,46,43,12,45,25,46,27,48,13,54,33,60,39,66,50,69,45,74,14,81,21,82,28,83,4,85,52,87,16,88,42,89,38,90,11,91,43,92,59,98,57,99,30,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29,122,23,124,24,125,9,126,34,127,40,128,31,129,20,130,60,131,15},
    &.{33,295,45,246,46,27,48,13,49,-90,52,-90,54,33,60,39,69,45,103,53,107,6,108,44,109,35,110,10,111,22,112,8,113,51,114,49,119,29},
    &.{1,-87,49,-87,51,-87,52,-87,64,-87,70,-87,71,-87,76,-87,79,-87,80,-87,104,-87,118,-87},
    &.{9,251,10,250,18,296,20,252,49,-37,52,-37,53,67,54,114,55,79},
    &.{1,-34,49,-34,52,-34},
    &.{1,-23,49,-23,52,-23},
    &.{49,-43,52,-43,54,297},
    &.{1,-32,49,-32,52,-32},
    &.{1,-33,49,-33,52,-33},
    &.{8,298,51,111},
    &.{1,-51,49,-51,51,-51,52,-51,65,-51,71,-51},
    &.{118,-139},
    &.{49,-91,52,-91},
    &.{49,-89,52,-89},
    &.{49,-36,52,-36},
    &.{49,-42,52,-42},
    &.{1,-86,49,-86,51,-86,52,-86,64,-86,70,-86,71,-86,76,-86,79,-86,80,-86,104,-86,118,-86},
};

const parse_table = blk: {
    @setEvalBranchQuota(100000);
    var t: [NUM_STATES][NUM_SYMBOLS]i16 = .{.{0} ** NUM_SYMBOLS} ** NUM_STATES;
    for (sparse, 0..) |row, state| {
        var i: usize = 0;
        while (i < row.len) : (i += 2) {
            t[state][@intCast(row[i])] = row[i + 1];
        }
    }
    break :blk t;
};

fn getAction(state: u16, sym: u16) i16 {
    return parse_table[state][sym];
}
// X "c" excludes: shift instead of reduce when pre==0 and char matches
const x_excludes = [_]struct { state: u16, char: u8, shift: u16 }{
};

fn getImmediateShift(state: u16, char: u8) ?i16 {
    for (x_excludes) |x| {
        if (x.state == state and x.char == char) return @intCast(x.shift);
    }
    return null;
}
const start_states = [_]struct { sym: u16, state: u16 }{
    .{ .sym = 3, .state = 0 },
    .{ .sym = 4, .state = 1 },
};

fn getStartState(start_sym: u16) u16 {
    for (start_states) |entry| {
        if (entry.sym == start_sym) return entry.state;
    }
    return 0;
}

const accept_rules = [_]u16{ 143, 144 };

fn isAcceptRule(rule_id: u16) bool {
    for (accept_rules) |ar| if (rule_id == ar) return true;
    return false;
}
