// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  // ==============================================================================
  // rip: The multilanguage universal runtime powering the Rip ecosystem.

  // Author: Steve Shreeve <steve.shreeve@gmail.com> and my AI friends.
  //  Stats: July 13, 2025 (version 0.5.0) MIT License
  // ==============================================================================
  var DEBUG, Item, Language, NORMAL, Rule, SILENT, State, Symbol, VERBOSE;

  SILENT = 0; // Errors only

  NORMAL = 1; // Basic summary (default)

  VERBOSE = 2; // Detailed analysis

  DEBUG = 3; // Everything + internals

  Symbol = class Symbol { // Terminal or Nonterminal
    constructor(name, isTerminal = false, id = 0) {
      this.id = id; // unique symbol id
      this.name = name; // symbol name (eg - Expression)
      this.isTerminal = isTerminal; // true if terminal, false if nonterminal
      this.nullable = false; // LALR(1) nullable computation
      this.first = new Set(); // LALR(1) FIRST sets
      this.follow = new Set(); // LALR(1) FOLLOW sets
    }

  };

  Rule = (function() {
    class Rule { // A → B C D
      constructor(lhs, rhs, action = null, precedence = null) {
        this.id = Rule.idno++; // unique rule id
        this.lhs = lhs; // left-hand side symbol
        this.rhs = rhs; // right-hand side symbol sequence
        this.action = action; // semantic action
        this.precedence = precedence; // precedence for conflict resolution
      }

    };

    Rule.idno = 0;

    return Rule;

  }).call(this);

  Item = class Item { // Rule with a dot position and lookahead: [A → α • β, a]
    static makeCoreKey(ruleId, dot) {
      return `${ruleId}-${dot}`;
    }

    constructor(rule, dot = 0, lookahead = new Set()) {
      if (rule == null) {
        throw new Error("Item constructor requires a rule");
      }
      if (!(typeof dot === 'number' || dot < 0)) {
        throw new Error("Item dot position must be non-negative number");
      }
      if (!(dot <= rule.rhs.length)) {
        throw new Error(`Item dot position (${dot}) cannot exceed rule RHS length (${rule.rhs.length})`);
      }
      this.rule = rule; // associated production rule
      this.dot = dot; // dot position (• marker)
      this.lookahead = lookahead; // LALR(1) lookahead set
    }

    isComplete() {
      return this.dot >= this.rule.rhs.length; // reduction check (is dot at end?)
    }

    nextSymbol() {
      return this.rule.rhs[this.dot];
    }

    advance() {
      return new Item(this.rule, this.dot + 1, new Set(this.lookahead)); // new item with dot advanced
    }

    core() {
      return new Item(this.rule, this.dot, new Set()); // LR(0) core (item without lookahead)
    }

    coreKey() {
      return this._coreKey != null ? this._coreKey : this._coreKey = Item.makeCoreKey(this.rule.id, this.dot); // core key, supports deduplication
    }

    toString() {
      var rhs;
      rhs = this.rule.rhs.slice();
      rhs.splice(this.dot, 0, '•');
      return `${this.rule.lhs} → ${rhs.join(' ')} [${[...this.lookahead].join(',')}]`;
    }

  };

  State = (function() {
    class State { // Set of LR(0) items
      constructor() {
        this.id = State.idno++; // unique state id
        this.items = []; // collection of item
        this.coreMap = new Map(); // core-based deduplication (core key -> item)
        this.transitions = new Map(); // state transitions (symbol -> state)
        this.inadequate = false; // has shift/reduce conflicts?
      }

      
        // Add item to state, merging lookaheads if core already exists
      addItem(item) {
        var coreKey, existingItem, la, oldSize, ref;
        coreKey = item.coreKey();
        if (this.coreMap.has(coreKey)) {
          // Merge lookaheads with existing item
          existingItem = this.coreMap.get(coreKey);
          oldSize = existingItem.lookahead.size;
          ref = item.lookahead;
          for (la of ref) {
            existingItem.lookahead.add(la);
          }
          // Return true if lookaheads were actually added
          return existingItem.lookahead.size > oldSize;
        } else {
          // Add new item
          this.coreMap.set(coreKey, item);
          this.items.push(item);
          return true;
        }
      }

      // Get core item by rule and dot
      getCoreItem(ruleId, dot) {
        return this.coreMap.get(Item.makeCoreKey(ruleId, dot));
      }

    };

    State.idno = 0;

    return State;

  }).call(this);

  // ==============================================================================
  // UNIVERSAL LANGUAGE DEFINITION
  // ==============================================================================
  Language = class Language {
    constructor(language = {}, opts = {}) {
      var ref, ref1, ref2, ref3, ref4, ref5;
      this.language = language;
      this.timing("🔤 Language constructor");
      this.validateLanguage();
      // Input (foundational data)
      this.info = {}; // Language metadata
      this.rules = []; // Language rules
      this.operators = []; // Precedence/associativity
      this.start = null; // Start symbol
      
      // Output (derived during analysis)
      this.analyzed = false; // Analysis done?
      this.symbols = new Map(); // Symbol table
      this.tokens = new Set(); // Terminal symbols
      this.symbolRules = new Map(); // Lookup rules by symbol
      this.precedence = {}; // Symbol precedence table
      this.states = []; // State machine
      this.stateMap = new Map(); // State lookup
      this.propagateLinks = new Map(); // LALR(1) lookahead propagation
      this.inadequateStates = []; // Conflict states
      this.conflicts = []; // Conflict details
      this.table = null; // Parse table
      this.defaultActions = {}; // Default actions for states
      this.cache = new Map(); // Performance cache
      
      // Debugging level
      this.debug = this.parseDebug((ref = opts.debug) != null ? ref : NORMAL);
      // Statistics
      this.stats = {
        // Input processing
        sourceRules: 0, // Direct from grammar file
        expandedRules: 0, // Expanded/flattened
        errorRecoveryRules: 0, // Error recovery rules
        augmentedRules: 0, // Augmented start rule
        
        // LALR(1) computation
        closureCalls: 0, // Closure calls
        cacheHits: 0, // Cache hits
        stateCreations: 0, // State creations
        lookaheadComputations: 0, // Lookahead computations
        
        // Optimizations
        optimizationTime: 0 // Optimization time
      };
      
      // FIXME: Not sure which of these are used

      // Optimization
      this.optimizationConfig = {
        enabled: (ref1 = opts.optimize) != null ? ref1 : false,
        auto: (ref2 = opts.autoOptimize) != null ? ref2 : true,
        minStatesForAuto: (ref3 = opts.minStatesForAuto) != null ? ref3 : 20,
        algorithms: (ref4 = opts.algorithms) != null ? ref4 : ['auto'],
        skipIfSmall: (ref5 = opts.skipIfSmall) != null ? ref5 : true
      };
      this.timing("🔤 Language constructor");
    }

    // ============================================================================
    // LANGUAGE ANALYSIS AND CONSTRUCTION
    // ============================================================================

      // Transform input → output
    analyze() {
      if (!this.analyzed) {
        this.timing("🔍 Analysis");
        // Phase 0: Language Preparation
        this.createSpecialSymbols(); // Create fundamental LALR(1) symbols
        
        // Phase 1: Symbol and Rule Analysis
        this.buildSymbols(); // @rules → @symbols, @tokens
        this.buildPrecedence(); // @operators → @precedence
        this.buildSymbolRules(); // @rules → @symbolRules
        
        // Phase 2: LALR(1) State Machine Construction
        this.augmentStartRule(); // Add $accept → start $end
        this.buildStates(); // @rules → @states, @stateMap
        this.computeLookaheads(); // @states → @propagateLinks
        
        // Phase 3: Parse Table and Optimization
        this.buildTable(); // @states → @table
        this.resolveConflicts(); // @states → @conflicts, @inadequateStates
        this.buildDefaultActions(); // @states → @defaultActions
        this.analyzed = true;
        return this.timing("🔍 Analysis");
      }
    }

    // ============================================================================
    // PHASE 1: SYMBOL AND RULE ANALYSIS
    // ============================================================================

      // Create fundamental LALR(1) symbols
    createSpecialSymbols() {
      this.getSymbol('$accept');
      this.getSymbol('$end', true);
      this.getSymbol('error', true);
      return this.tokens.add('error');
    }

    // Extract symbols from rules and identify terminals
    buildSymbols() {
      var j, k, len, len1, lhsSymbols, name, ref, ref1, ref2, results, rule, symbol, x;
      ref = this.rules;
      // Add all symbols from rules
      for (j = 0, len = ref.length; j < len; j++) {
        rule = ref[j];
        this.getSymbol(rule.lhs, false); // Nonterminal
        ref1 = rule.rhs;
        // Assume terminal initially
        for (k = 0, len1 = ref1.length; k < len1; k++) {
          symbol = ref1[k];
          this.getSymbol(symbol, true);
        }
      }
      
      // Mark as terminal if never appears on LHS
      lhsSymbols = new Set((function() {
        var l, len2, ref2, results;
        ref2 = this.rules;
        results = [];
        for (l = 0, len2 = ref2.length; l < len2; l++) {
          rule = ref2[l];
          results.push(rule.lhs);
        }
        return results;
      }).call(this));
      ref2 = this.symbols;
      results = [];
      for (x of ref2) {
        [name, symbol] = x;
        if (!lhsSymbols.has(name)) {
          symbol.isTerminal = true;
          results.push(this.tokens.add(name));
        } else {
          results.push(void 0);
        }
      }
      return results;
    }

    // Create rule lookup by symbol
    buildSymbolRules() {
      var j, len, lhs, ref, results, rule;
      ref = this.rules;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        rule = ref[j];
        lhs = rule.lhs;
        if (!this.symbolRules.has(lhs)) {
          this.symbolRules.set(lhs, []);
        }
        results.push(this.symbolRules.get(lhs).push(rule));
      }
      return results;
    }

    // Process operator precedence and associativity
    buildPrecedence() {
      var assoc, group, j, k, len, len1, level, ref, results, symbol, symbols;
      level = 1;
      ref = this.operators;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        group = ref[j];
        [assoc, ...symbols] = group;
        for (k = 0, len1 = symbols.length; k < len1; k++) {
          symbol = symbols[k];
          this.precedence[symbol] = {level, assoc};
        }
        results.push(level++);
      }
      return results;
    }

    // Add augmented start rule: $accept → start $end
    augmentStartRule() {
      this.rules.push(new Rule('$accept', [this.start, '$end']));
      return this.stats.augmentedRules = 1;
    }

    // ============================================================================
    // PHASE 2: LALR(1) STATE MACHINE CONSTRUCTION
    // ============================================================================

      // Build LR(0) state machine
    buildStates() {
      var existingState, item, items, j, len, newState, nextSym, ref, results, startRule, startState, state, symbol, transitions, workList;
      // Find the augmented start rule ($accept → start $end)
      startRule = this.rules.find(function(rule) {
        return rule.lhs === '$accept';
      });
      if (!startRule) {
        throw new Error("No augmented start rule found");
      }
      // Create initial state with augmented start rule
      startState = new State();
      startState.addItem(new Item(startRule, 0, new Set(['$end'])));
      this.closure(startState);
      this.addState(startState);
      // Build all states
      workList = [startState];
      results = [];
      while (workList.length > 0) {
        state = workList.shift();
        // Group items by next symbol
        transitions = new Map();
        ref = state.items;
        for (j = 0, len = ref.length; j < len; j++) {
          item = ref[j];
          if (!(!item.isComplete())) {
            continue;
          }
          nextSym = item.nextSymbol();
          if (!transitions.has(nextSym)) {
            transitions.set(nextSym, []);
          }
          transitions.get(nextSym).push(item);
        }
        results.push((function() {
          var k, len1, results1, x;
// Create new states for each transition
          results1 = [];
          for (x of transitions) {
            [symbol, items] = x;
            newState = new State();
            for (k = 0, len1 = items.length; k < len1; k++) {
              item = items[k];
              newState.addItem(item.advance());
            }
            this.closure(newState);
            // Add or merge state
            existingState = this.findOrAddState(newState);
            state.transitions.set(symbol, existingState);
            if (existingState === newState) {
              results1.push(workList.push(newState));
            } else {
              results1.push(void 0);
            }
          }
          return results1;
        }).call(this));
      }
      return results;
    }

    // Compute closure of a state (LR(0) - no lookaheads yet)
    closure(state) {
      var coreKey, item, j, len, newItem, nextSym, nextSymbol, rule, rules, workList;
      this.stats.closureCalls++;
      // Check closure cache first
      coreKey = this.computeCore(state);
      if (this.cache.has(coreKey)) {
        this.stats.cacheHits++;
        return;
      }
      // Compute closure using standard algorithm
      workList = [...state.items];
      while (workList.length > 0) {
        item = workList.shift();
        if (item.isComplete()) {
          // Skip if item is complete
          continue;
        }
        // Get next symbol after dot
        nextSym = item.nextSymbol();
        nextSymbol = this.getSymbol(nextSym);
        if (nextSymbol.isTerminal) {
          // Skip if next symbol is terminal
          continue;
        }
        // Find all rules for this nonterminal
        rules = this.symbolRules.get(nextSym) || [];
        for (j = 0, len = rules.length; j < len; j++) {
          rule = rules[j];
          // Create new item: [A → • α, lookahead]
          newItem = new Item(rule, 0, new Set());
          // Add to state if not already present
          if (state.addItem(newItem)) {
            workList.push(newItem);
          }
        }
      }
      // Cache the closure result
      return this.cache.set(coreKey, true);
    }

    // Compute core hash for state deduplication
    computeCore(state) {
      var cores, item, j, len, ref;
      cores = [];
      ref = state.items;
      for (j = 0, len = ref.length; j < len; j++) {
        item = ref[j];
        cores.push(item.coreKey());
      }
      return cores.sort().join('|');
    }

    // Find existing state or add new one
    findOrAddState(state) {
      var coreKey, existingItem, existingState, item, j, la, len, ref, ref1;
      coreKey = this.computeCore(state);
      if (this.stateMap.has(coreKey)) {
        existingState = this.stateMap.get(coreKey);
        ref = state.items;
        // Merge lookaheads from new state into existing state
        for (j = 0, len = ref.length; j < len; j++) {
          item = ref[j];
          existingItem = existingState.getCoreItem(item.rule.id, item.dot);
          if (existingItem) {
            ref1 = item.lookahead;
            for (la of ref1) {
              existingItem.lookahead.add(la);
            }
          }
        }
        return existingState;
      } else {
        this.addState(state);
        return state;
      }
    }

    // Add state to state list
    addState(state) {
      this.stats.stateCreations++;
      this.states.push(state);
      this.stateMap.set(this.computeCore(state), state);
      return state;
    }

    // Compute LALR(1) lookahead sets
    computeLookaheads() {
      var item, j, k, la, len, len1, lookahead, ref, ref1, ref2, state;
      this.timing("📋 Compute Lookaheads");
      ref = this.states;
      // First pass: compute spontaneous lookaheads
      for (j = 0, len = ref.length; j < len; j++) {
        state = ref[j];
        ref1 = state.items;
        for (k = 0, len1 = ref1.length; k < len1; k++) {
          item = ref1[k];
          if (item.isComplete()) {
            continue;
          }
          // Get lookahead for this item
          lookahead = this.firstOfString(item.rule.rhs.slice(item.dot + 1));
          if (item.rule.rhs.slice(item.dot + 1).some((sym) => {
            return this.getSymbol(sym).nullable;
          })) {
            ref2 = item.lookahead;
            for (la of ref2) {
              lookahead.add(la);
            }
          }
          for (la of lookahead) {
            // Add spontaneous lookaheads
            item.lookahead.add(la);
          }
        }
      }
      // Second pass: propagate lookaheads
      this.propagateLookaheads();
      return this.timing("📋 Compute Lookaheads");
    }

    // Propagate lookaheads until convergence
    propagateLookaheads() {
      var changed, item, la, nextItem, nextState, nextSym, oldSize, results, state;
      changed = true;
      results = [];
      while (changed) {
        changed = false;
        results.push((function() {
          var j, len, ref, results1;
          ref = this.states;
          results1 = [];
          for (j = 0, len = ref.length; j < len; j++) {
            state = ref[j];
            results1.push((function() {
              var k, len1, ref1, ref2, results2;
              ref1 = state.items;
              results2 = [];
              for (k = 0, len1 = ref1.length; k < len1; k++) {
                item = ref1[k];
                if (item.isComplete()) {
                  continue;
                }
                nextSym = item.nextSymbol();
                nextState = state.transitions.get(nextSym);
                if (!nextState) {
                  continue;
                }
                // Find corresponding item in next state
                nextItem = nextState.getCoreItem(item.rule.id, item.dot + 1);
                if (!nextItem) {
                  continue;
                }
                // Propagate lookaheads
                oldSize = nextItem.lookahead.size;
                ref2 = item.lookahead;
                for (la of ref2) {
                  nextItem.lookahead.add(la);
                }
                if (nextItem.lookahead.size > oldSize) {
                  results2.push(changed = true);
                } else {
                  results2.push(void 0);
                }
              }
              return results2;
            })());
          }
          return results1;
        }).call(this));
      }
      return results;
    }

    // Compute FIRST set of a string of symbols
    firstOfString(symbols) {
      var first, j, la, len, result, symbol, symbolObj;
      result = new Set();
      for (j = 0, len = symbols.length; j < len; j++) {
        symbol = symbols[j];
        symbolObj = this.getSymbol(symbol);
        first = symbolObj.first;
        for (la of first) {
          result.add(la);
        }
        if (!symbolObj.nullable) {
          break;
        }
      }
      return result;
    }

    // ============================================================================
    // PHASE 3: PARSE TABLE AND OPTIMIZATION
    // ============================================================================

      // Build parse table from states
    buildTable() {
      var conflicts, existing, existingRuleId, item, j, k, la, len, len1, nextState, ref, ref1, ref2, ref3, resolved, state, symbol, table, x;
      this.timing("📋 Build Table");
      table = [];
      conflicts = {
        sr: 0,
        rr: 0
      };
      ref = this.states;
      for (j = 0, len = ref.length; j < len; j++) {
        state = ref[j];
        table[state.id] = {};
        ref1 = state.transitions;
        // Shift actions and GOTO
        for (x of ref1) {
          [symbol, nextState] = x;
          if (this.getSymbol(symbol).isTerminal) {
            table[state.id][symbol] = {
              type: 'shift',
              state: nextState.id
            };
          } else {
            table[state.id][symbol] = nextState.id; // GOTO
          }
        }
        ref2 = state.items;
        
        // Reduce actions
        for (k = 0, len1 = ref2.length; k < len1; k++) {
          item = ref2[k];
          if (!item.isComplete()) {
            continue;
          }
          // Special case for accept
          if (item.rule.lhs === '$accept') {
            table[state.id]['$end'] = {
              type: 'accept'
            };
            continue;
          }
          ref3 = item.lookahead;
          // Add reduce action for each lookahead
          for (la of ref3) {
            if (table[state.id][la] != null) {
              // Conflict! Try to resolve with precedence
              existing = table[state.id][la];
              if (existing.type === 'shift') {
                // Shift/reduce conflict
                resolved = this.resolveConflict(item.rule, la);
                if (resolved === 'reduce') {
                  table[state.id][la] = {
                    type: 'reduce',
                    rule: item.rule.id
                  };
                  this.conflicts.push({
                    type: 'shift/reduce',
                    state: state.id,
                    lookahead: la,
                    resolved: true,
                    resolution: 'reduce',
                    explanation: `State ${state.id}: Shift/reduce conflict on '${la}' resolved to REDUCE (precedence)`
                  });
                } else if (resolved === 'shift') {
                  this.conflicts.push({
                    type: 'shift/reduce',
                    state: state.id,
                    lookahead: la,
                    resolved: true,
                    resolution: 'shift',
                    explanation: `State ${state.id}: Shift/reduce conflict on '${la}' resolved to SHIFT (precedence)`
                  });
                } else {
                  // unresolved conflict
                  conflicts.sr++;
                  state.inadequate = true;
                  if (!this.inadequateStates.includes(state)) {
                    this.inadequateStates.push(state);
                  }
                  this.conflicts.push({
                    type: 'shift/reduce',
                    state: state.id,
                    lookahead: la,
                    resolved: false,
                    resolution: 'shift',
                    explanation: `State ${state.id}: Unresolved shift/reduce conflict on '${la}' - using default SHIFT`
                  });
                }
              } else if (existing.type === 'reduce') {
                // Reduce/reduce conflict - use first rule (earliest in grammar)
                existingRuleId = existing.rule;
                if (item.rule.id < existingRuleId) {
                  table[state.id][la] = {
                    type: 'reduce',
                    rule: item.rule.id
                  };
                }
                this.conflicts.push({
                  type: 'reduce/reduce',
                  state: state.id,
                  lookahead: la,
                  resolved: true,
                  resolution: `rule ${Math.min(item.rule.id, existingRuleId)}`,
                  explanation: `State ${state.id}: Reduce/reduce conflict on '${la}' resolved to rule ${Math.min(item.rule.id, existingRuleId)} (first declared)`
                });
                conflicts.rr++;
              }
            } else {
              table[state.id][la] = {
                type: 'reduce',
                rule: item.rule.id
              };
            }
          }
        }
      }
      if (conflicts.sr > 0 || conflicts.rr > 0) {
        console.warn(`Grammar has conflicts: ${conflicts.sr} shift/reduce, ${conflicts.rr} reduce/reduce`);
      }
      this.table = table;
      return this.timing("📋 Build Table");
    }

    // Resolve shift/reduce conflicts using precedence and associativity
    resolveConflict(rule, lookahead) {
      var rulePrecedence, tokenPrecedence;
      // Get precedence of the rule (from its precedence or rightmost terminal)
      rulePrecedence = this.getRulePrecedence(rule);
      // Get precedence of the lookahead token
      tokenPrecedence = this.precedence[lookahead];
      if (!(rulePrecedence && tokenPrecedence)) {
        // If either lacks precedence, can't resolve
        return false;
      }
      // Higher precedence wins
      if (rulePrecedence.level > tokenPrecedence.level) {
        return 'reduce';
      } else if (rulePrecedence.level < tokenPrecedence.level) {
        return 'shift';
      } else {
        // Same precedence - use associativity
        switch (rulePrecedence.assoc) {
          case 'left':
            return 'reduce';
          case 'right':
            return 'shift';
          case 'nonassoc':
            return 'error';
          default:
            return null;
        }
      }
    }

    // Get precedence for a rule
    getRulePrecedence(rule) {
      var i, j, ref, symbol;
      // If rule has explicit precedence, use it
      if (rule.precedence) {
        return this.precedence[rule.precedence];
      }
// Otherwise, use precedence of rightmost terminal
      for (i = j = ref = rule.rhs.length - 1; j >= 0; i = j += -1) {
        symbol = rule.rhs[i];
        if (this.tokens.has(symbol) && this.precedence[symbol]) {
          return this.precedence[symbol];
        }
      }
      return null;
    }

    // Resolve conflicts and mark inadequate states
    resolveConflicts() {
      this.timing("📋 Resolve Conflicts");
      // Conflicts are already resolved during table building
      // This method is for any additional conflict resolution logic
      return this.timing("📋 Resolve Conflicts");
    }

    // Compute default actions for performance optimization
    buildDefaultActions() {
      var action, actionTypes, actions, hasShift, j, len, reduceRules, ref, ruleId, state, symbol;
      this.timing("📋 Build Default Actions");
      this.defaultActions = {};
      ref = this.states;
      // A state can have a default action if:
      // 1. All actions in the state are reduces by the same rule, OR
      // 2. The state has no shift actions and only one unique reduce action
      for (j = 0, len = ref.length; j < len; j++) {
        state = ref[j];
        if (!this.table[state.id]) {
          continue;
        }
        actions = this.table[state.id];
        actionTypes = new Set();
        reduceRules = new Set();
        hasShift = false;
// Analyze all actions in this state
        for (symbol in actions) {
          action = actions[symbol];
          if (action.type === 'shift') {
            hasShift = true;
          } else if (action.type === 'reduce') {
            actionTypes.add('reduce');
            reduceRules.add(action.rule);
          } else if (action.type === 'accept') {
            actionTypes.add('accept');
            // Accept states cannot have default actions
            hasShift = true; // Prevent default action
          }
        }
        
        // Can use default reduction if:
        // - No shift actions
        // - Only reduce actions
        // - All reduces are for the same rule
        if (!hasShift && actionTypes.size <= 1 && reduceRules.size === 1) {
          ruleId = [...reduceRules][0];
          this.defaultActions[state.id] = [2, ruleId];
        }
      }
      return this.timing("📋 Build Default Actions");
    }

    // Get or create a symbol
    getSymbol(name, isTerminal) {
      var sym, symbol;
      if (sym = this.symbols.get(name)) {
        return sym;
      }
      isTerminal = isTerminal != null ? !!isTerminal : this.tokens.has(name);
      symbol = new Symbol(name, isTerminal, this.symbols.size);
      this.symbols.set(name, symbol);
      return symbol;
    }

    // Check if a symbol name is valid
    isValidSymbolName(name) {
      if (!((name != null) && typeof name === 'string')) {
        return false;
      }
      if (name.length === 0) {
        return false;
      }
      // Allow alphanumeric, underscore, hyphen, and some special characters for terminals
      return /^[a-zA-Z_][a-zA-Z0-9_?-]*$|^[+\-*\/(){}[\];,.'":=<>!&|?~^%$#@\\]+$/.test(name);
    }

    // ============================================================================
    // HELPER FUNCTIONS
    // ============================================================================

      // Determine how much to debug or log
    parseDebug(level) {
      switch (level) {
        case 0:
        case 'silent':
          return SILENT;
        case 1:
        case 'normal':
          return NORMAL;
        case 2:
        case 'verbose':
          return VERBOSE;
        case 3:
        case 'debug':
          return DEBUG;
        case true:
          return VERBOSE; // -V --verbose flag
        case false:
          return NORMAL; // default when verbose=false
        default:
          return NORMAL; // fallback to normal
      }
    }

    
      // Usage:
    //   @timing "📋 Phase description", => @fn()  # Function wrapper
    //   @timing "📋 Phase description"            # Start timer
    //   @timing "📋 Phase description"            # End timer and show duration
    timing(description, fn) {
      var duration, endTime, result, startTime;
      if (this.timers == null) {
        this.timers = new Map();
      }
      if (fn != null) {
        // Function wrapper mode - only time if verbose or higher
        if (this.debug >= VERBOSE) {
          startTime = Date.now();
          result = fn.call(this);
          endTime = Date.now();
          duration = endTime - startTime;
          console.log(`${description}: ${duration}ms`);
          return result;
        } else {
          return fn.call(this);
        }
      } else {
        // Manual timing mode - only time if verbose or higher
        if (this.debug >= VERBOSE) {
          if (this.timers.has(description)) {
            // End timer
            startTime = this.timers.get(description);
            endTime = Date.now();
            duration = endTime - startTime;
            console.log(`${description}: ${duration}ms`);
            return this.timers.delete(description);
          } else {
            // Start timer
            return this.timers.set(description, Date.now());
          }
        }
      }
    }

  };

  // Return nothing for manual timing mode

}).call(this);
