// The stash surfaces' diagnostics, worded from records: a TS2345
// covering exactly a recorded `__ripSourceKey` literal is a stash-key
// miss; a TS2345 covering exactly a recorded route value names the
// nearest static route the way tsgo's own annotation form does; a
// member miss covering exactly a recorded `@stash.<name>` is on the
// stash. The literal is read from the generated bytes, the keys from
// the stash module's own compile, the routes from the walker — the
// checker's sentence is never read, so its wording cannot matter.
// Driven through the one mapping road (mapTsDiagnostic) over real
// compile() output.
import { test, expect } from 'bun:test';
import { compile } from '../../../../src/compile.js';
import { mapTsDiagnostic } from '../../src/diagnostics.js';
import { lineStartsOf, offsetToPosition } from '../../src/translate.js';

const source = [
  "import { currentStash, currentRouter as cr } from 'rip/app'",
  '',
  'outside = ->',
  "  currentStash()?.source('userz')",
  "  cr()?.push('/cartz')",
  '',
  'Page = component',
  '  go: ->',
  "    @stash.source('userz')",
  "    @stash.source('userz.name')",
  "    @stash.source('zzz')",
  "    @router.push '/nowhere'",
  '    @stash.userz',
  '    @stash.rest()',
  '    @stash.user.bogus',
  '  render null',
  '',
].join('\n');
const result = compile(source, { path: 'p.rip', runtimeDelivery: 'none', face: 'ts', routesUnion: '"/" | "/cart"', appStashSpec: './stash.rip' });
const KEYS = { keys: ['cart', 'user'], complete: true };
const goodWith = (stashKeys) => ({
  source,
  code: result.code,
  mappings: result.mappings,
  srcLineStarts: lineStartsOf(source),
  genLineStarts: lineStartsOf(result.code),
  strict: true,
  routeWraps: result.routeWraps,
  sourceKeys: result.sourceKeys,
  stashMembers: result.stashMembers,
  stashKeys,
  routeEntries: [
    { shape: '/', text: '"/"', display: '/' },
    { shape: '/cart', text: '"/cart"', display: '/cart' },
  ],
});
const good = goodWith(KEYS);
// The checker's sentence is a placeholder on purpose: no rewrite reads it.
const at = (span, code, message = 'the checker said something') => ({
  code, message, severity: 1,
  range: {
    start: offsetToPosition(good.genLineStarts, span[0]),
    end: offsetToPosition(good.genLineStarts, span[1]),
  },
});
const genSpanOf = (bytes, nth = 0) => {
  let from = -1;
  for (let i = 0; i <= nth; i++) { from = result.code.indexOf(bytes, from + 1); expect(from).toBeGreaterThan(-1); }
  return [from, from + bytes.length];
};
const spanOfMember = (name) => { const [, e] = genSpanOf(`this.stash.${name}`); return [e - name.length, e]; };

test('the compile records every wrapped source-key literal (both receivers) and every ambient stash member name', () => {
  expect(result.sourceKeys.map(([a, b]) => result.code.slice(a, b))).toEqual(['"userz"', '"userz"', '"userz.name"', '"zzz"']);
  expect(result.stashMembers.map(([a, b]) => result.code.slice(a, b))).toEqual(['source', 'source', 'source', 'userz', 'rest', 'user']);
});

test('a key miss on a recorded literal reads as one, with the nearest key; the sentence tsgo wrote is irrelevant', () => {
  for (const nth of [0, 1]) {
    expect(mapTsDiagnostic(good, at(genSpanOf('"userz"', nth), 2345)).message).toBe("'userz' is not a stash key — did you mean 'user'?");
  }
  expect(mapTsDiagnostic(good, at(genSpanOf('"userz.name"'), 2345)).message).toBe("'userz.name' does not start with a stash key — did you mean 'user.name'?");
  // Nothing near: the keys are listed — only when the record holds the whole stash.
  expect(mapTsDiagnostic(good, at(genSpanOf('"zzz"'), 2345)).message).toBe("'zzz' is not a stash key — the keys are cart, user");
  expect(mapTsDiagnostic(goodWith({ keys: ['cart', 'user'], complete: false }), at(genSpanOf('"zzz"'), 2345)).message).toBe("'zzz' is not a stash key");
  expect(mapTsDiagnostic(goodWith(null), at(genSpanOf('"zzz"'), 2345)).message).toBe("'zzz' is not a stash key");
  // Another code on the same span, or the same code on an unrecorded span, keeps tsgo's words.
  expect(mapTsDiagnostic(good, at(genSpanOf('"userz"'), 2322)).message).toBe('the checker said something');
  expect(mapTsDiagnostic(good, at(genSpanOf('"/nowhere"'), 2339)).message).toBe('the checker said something');
});

test('a route miss names the nearest static route after tsgo\'s own sentence; a far one keeps the sentence alone', () => {
  expect(mapTsDiagnostic(good, at(genSpanOf('"/cartz"'), 2345, 'mismatch.')).message).toBe(`mismatch. Did you mean '"/cart"'?`);
  expect(mapTsDiagnostic(good, at(genSpanOf('"/nowhere"'), 2345, 'mismatch.')).message).toBe('mismatch.');
});

test('a member miss on a recorded stash member names the stash: a key, a method, or the list', () => {
  expect(mapTsDiagnostic(good, at(spanOfMember('userz'), 2551)).message).toBe("'userz' is not on the stash — did you mean 'user'?");
  expect(mapTsDiagnostic(good, at(spanOfMember('rest'), 2339)).message).toBe("'rest' is not on the stash — did you mean 'reset'?");
  expect(mapTsDiagnostic(goodWith({ keys: ['cart', 'user'], complete: true }), at(spanOfMember('userz'), 2339)).message).toBe("'userz' is not on the stash — did you mean 'user'?");
  // A miss on a member OF a member (`@stash.user.bogus`) is not on the stash: unrecorded, tsgo's words stand.
  const [, e] = genSpanOf('this.stash.user.bogus');
  expect(mapTsDiagnostic(good, at([e - 5, e], 2339)).message).toBe('the checker said something');
});

test('a stash module records its own keys: plain, quoted, shorthand, through a wrapping call; a spread or computed key marks the set incomplete', () => {
  const keysOf = (text) => compile(text, { path: 'stash.rip', runtimeDelivery: 'none', face: 'ts' }).stashKeys;
  expect(keysOf("export stash = { user: 1, 'quoted': 2, cart }\n")).toEqual({ keys: ['user', 'quoted', 'cart'], complete: true });
  expect(keysOf("export stash = createStash { user: 1 }\n")).toEqual({ keys: ['user'], complete: true });
  expect(keysOf("stash = { user: 1 }\nexport { stash }\n")).toEqual({ keys: ['user'], complete: true });
  expect(keysOf("base = { a: 1 }\nexport stash = { user: 1, ...base }\n")).toEqual({ keys: ['user'], complete: false });
  expect(keysOf("k = 'x'\nexport stash = { user: 1, [k]: 2 }\n")).toEqual({ keys: ['user'], complete: false });
  // Not an object literal, or no stash at all: no record.
  expect(keysOf("export stash = makeStash()\n")).toBeNull();
  expect(keysOf("x = 1\n")).toBeNull();
});
